### ISSUE TITLE
[Death Knight][DK] Death Grip

### ISSUE THREAD

**Issue by Shaadya** [SunwellTracker/issues#101]
Decription: 
while being in water it drips a mob in front you but on the bottom of th lake/sea

How it works: 
while being in water it drips a mob in front you but on the bottom of th lake/sea

How it should work: 
it should pull a mob in front of you at your level

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by thanhtotti** [comment]
I can confirm this bug. You can reproduce this bug by Death Grip mobs mid-water. The mob will be pulled to the bottom of the water medium instead of "toward you". 

It's extremely difficult to find a source for this bug, but I play in retail for years and DG didn't work like that at all, Disappointed at dev's lazy copy-paste reply. Looking forward to this issue be re-opened.
