### ISSUE TITLE
Naxx KT 10 Guardian Adds

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1060]
Decription: Ads are spawning way way too early and for that reason tank dies and boss cannot be done.

How it works: Guardians that should spawn at 45% KT hp spawns at 90% hp and they just stack their damage buff and it's impossible to kill the boss.

How it should work: Guardians should spawn when KT gets to 45% hp and it becomes a dps race after that. As mentioned here or any other guide.  http://wowwiki.wikia.com/wiki/Kel%27Thuzad_(tactics)
![bug](https://user-images.githubusercontent.com/37425406/37884295-987e66b8-30af-11e8-8f25-16fadd80e335.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Morflol** [comment]
It's intended, they boosted Naxx.
You can find a list of the changes here : http://sunwell-community.com/index.php?/topic/31-angrathar-boosted-30/

**Comment by AtaIante** [comment]
@Morflol  No, it's not intended, you've read only the main post - admins said crystal clear that they don't want to alienate casual players, so there should be no change in mechanics in 10 man raids. New mechanics (such as guardians that spawned at 90% instead of 45%) should have been implemented only on 25 man raids.

**Comment by Dootz** [comment]
according to Graal - "Test Master", that's intended change.
