### ISSUE TITLE
[Gloves of the Lost Conqueror] FPS issue 2018

### ISSUE THREAD

**Issue by shadownib** [SunwellTracker/issues#1086]
Decription: Fps issue by showing / over mouse specific item ( never see fps issue like this seems to be interesting for you Sunwell 😋 )

How it works: first video https://www.youtube.com/watch?v=K3M_sWxdKcw and second video - https://www.youtube.com/watch?v=jr6oxvVVV7s

How it should work: without FPS drop ?

Source (you should point out proofs of your report, please give us some source):

**Comment by shadownib** [comment]
Now I'll try the clear client from sunwell site ( without legion mods ) 
Seems the reason is not in the Mods.   https://www.youtube.com/watch?v=YedwHM0oYoc

**Comment by Azathothh** [comment]
It's caused by addons: 
turn your addons off -> login on a char where problem happens -> close wow -> clear cache folder -> login again - it should work properly after that.
Also it's not a place to report hardware/software problems - it's better to post stuff like that here -> http://sunwell-community.com/index.php?/forum/10-help-desk/
