### ISSUE TITLE
[Quest] Grizzly Hills - Conquest Hold Quest chain/series

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1115]
**Decription:** 
Many WotLK NPCs and quests don't become available till others have been completed before them. These prelim quests may be from same NPC or different NPC/object.
Some quest hubs with complicated questing structure like _Zim'Torga_ in Zul'Drak are working perfectly. However some places like _Conquest Hold_ in Grizzly Hills and _The Crystal Vice_ in Dragonblight have NPCs dumping all or most of the quests they can give on the player all at once.

**How it works:** 
Windseer Grayhorn's quests - https://i.imgur.com/ihSNtOa.jpg

**How it should work:** 
Windseer Grayhorn's quests - https://www.youtube.com/watch?v=h8SNPSzzzHY

Quest [Good Troll Hunting](http://www.wowhead.com/quest=12208/good-troll-hunting) should not be available before completing [My Enemy's Friend](http://www.wowhead.com/quest=12412/my-enemys-friend#comments).
Quest [Ruuna the Blind](http://www.wowhead.com/quest=12161/ruuna-the-blind#comments) should not be available at NPC. It is part of chain started by dropped quest item [Mikhail's Journal](http://www.wowhead.com/quest=12423/mikhails-journal).
[Onward to Camp Oneqwah](http://www.wowhead.com/quest=12451/onward-to-camp-oneqwah) should be offered only after all the main storyline quests in the hub have been completed.
*Onward to Camp Oneqwah https://www.youtube.com/watch?v=WyJaafGWQTA - No quests available in minimap. Only Good Troll Hunting, which should also unlock at the same time.**

EDIT - Quest structure can be seen in this wowhead comment: http://www.wowhead.com/quest=12236/ursoc-the-bear-god#comments

**Comment by MrTide** [comment]
Hello Are you sure you have done all of these 
There's only about 2 or 3 quest chains you need to do before you can do the Conquest Pit line. Here's a simple guide to unlocking it, since information seems to be all over the place in the comments above, and I just finished it not too long ago.

1) Do Gray Worg Hides on the way to Voldrune to do A Show of Strength and The Flamebinder's Secrets.
2) Return to Conquest Hold, turn in quests, get new ones.
3) Travel east of Voldrune and complete A Minor Substitution.
4) Head into Voldrune and complete The Thane of Voldrune.
5) Return to Conquest Hold, turn in quests. Grab 5 Flour and 1 Coal from the vendors there, and complete Jun'ik's Coverup and Delivery to Krenna
6) Grab My Enemy's Friend and complete it. Make sure you get the journal for Mikhail's Journal which drops off the hunters during this quest.
7) Return to Conquest Hold, turn in quests, get new ones.
8) Head north and complete Tactical Clemency and Attack on Silverbrook
9) Return to Conquest Hold, turn in quests.
http://www.wowhead.com/quest=12427/the-conquest-pit-bear-wrestling
First comment

**Comment by Dootz** [comment]
Sidenote: Quest order in goblin hub need to be checked aswell.
https://github.com/SunwellTracker/issues/issues/1090

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by nimeral** [comment]
Ruuna the Blind is still slightly bugged: available after Gorgonna, without doing Tactical Clemency.
https://www.wowhead.com/quest=12425/ruuna-the-blind#comments:id=465446
