### ISSUE TITLE
Loot table during Kalu'ak Fishing Derby broken

### ISSUE THREAD

**Issue by Carravan** [SunwellTracker/issues#1125]
Description: During the Kalu'ak Fishing Derby, taking place every Saturday from 2pm to 3pm ST, every loot table that contains "Pygmy Suckerfish" should also contain "Blacktip Shark", so that the event can be completed.

How it works: I've started fishing in Imperial Manta Ray pools as soon as the northrend-wide yell announced that the event is on and stopped at 3:10pm, 10 minutes after the event ends. I've caught so many fish that I ran out of inventory space 45 minutes in, but no shark hooked, Whilst I can't say it with 100% certainty, I believe that the shark is not currently on the loot tables. 

How it should work: According to my experience from retail servers, the shark should have a fair chance to be caught within the first 2-3, max.10 minutes after the event has started, assuming players are actively trying to fish as fast as possible.

Source (you should point out proofs of your report, please give us some source): Retail experience. I don't know how else I can prove to you that something is not the loot table.

**Comment by Carravan** [comment]
Pygmy Suckerfish is ID 40199
Blacktip Shark is ID 50289

**Comment by TheRealYasri** [comment]
Not sure If I should post seperately, but they might be linked. The Stranglethorn Fishing Extravaganza was also bugged. The schools for the fish did not spawn like they should. Could have something to do with time zone changes because they worked last week.

Fish and the Pools for them.
https://db.darkwizard.pl/?item=19807#?ref=sunwell.pl
https://db.darkwizard.pl/?object=180248
