### ISSUE TITLE
Ammunition Isn't Being Applied Correctly to Hunter Weapon Damage

### ISSUE THREAD

**Issue by dragonz77** [SunwellTracker/issues#1132]
**Decription:** 
Ammunition is currently not being applied to a hunter's weapon

**How it works:** 
Ammunition's damage isn't being applied to weapon damage calculation formulas

**How it should work:** 
Ammunition's damage should be applied within the weapon damage calculation formula

eg:
Minimum Range = (((Minimum damage + Scope damage bonus) / Weapon Speed) + (Ranged Attack Power / 14) + Ammo DPS bonus) * Weapon Speed

Maximum Range = (((Maximum damage + Scope damage bonus) / Weapon Speed) + (Ranged Attack Power / 14) + Ammo DPS bonus) * Weapon Speed

**Source (you should point out proofs of your report, please give us some source):** 
https://www.twitch.tv/videos/245245470

**Comment by Soufly** [comment]
I also tested that,and its actually bugged.That bug especially for MM is huge DPS loss,compared to the Survival build.

**Comment by Vanggaard9300** [comment]
better get a fix asap and ofc value for agi aswell

**Comment by Azathothh** [comment]
So you're saying ammunition doesn't change your dmg, and post a video where we can clearly see that it does? At 1:59 when you switch arrows ranged damage is increased (right above "speed", and right from "strength"). I see you're mousing over your weapon after that, so I guess you've thought it should increase on weapon tooltip - nope, it shouldn't.

Please provide some calculations or logs proving that it doesn't work.

**Comment by dragonz77** [comment]
If you look at the damage logs I provided, the damage increases are minuscule.
The issue isn't 'My damage doesn't change on tooltip' because you can see on the character sheet that it does, the question is that this damage change is incorrect.  My average damage difference between those arrows is less than 100 damage, for specs like Survival and BM their core damage mechanics are not affected as much but for MM this is reducing its performance by at least 15% of what it should be.

Please direct me to whatever information I or other concerned hunters like myself can provide you, because telling us that our character sheet numbers change doesn't make it correct or help anyone when the actual performance of the class is saying otherwise.

**Comment by Cwiercpasiec** [comment]
This report is invalid. Currently ammunition's damage affects weapon damage. 
This is my hunter on PTR, shooting with Rough Arrows (1,5 dps)
![wowscrnshot_040118_182724](https://user-images.githubusercontent.com/26198742/38175346-85a0fd90-35db-11e8-8810-bbfeccabee87.jpg)
And now with Iceblade Arrows (91,5 dps)
![wowscrnshot_040118_182829](https://user-images.githubusercontent.com/26198742/38175374-c0bdc1b0-35db-11e8-916a-c003401f928e.jpg)
You can clearly see, that the damage is increased. Here, I marked it in Combat Log, so you don't have to search it:
![wowscrnshot_040118_182828](https://user-images.githubusercontent.com/26198742/38175395-12c16408-35dc-11e8-9d0d-1d0df3b0eddc.jpg)

Now don't get me wrong, I didn't calculate it and don't know if ammunition ads not enough damage, too much damage or it works perfectly fine, but this report states, that ammunition does not affect damage, which is obviously not true.

**Comment by dragonz77** [comment]
Cwiercpasiec that's perfect! Soufly and I spent a while last night trying to confirm this and you show it easily. 

Key point I'm bringing up is that 'Ammunition isn't being **applied correctly** to hunter weapon damage," the issue is that it should be theoretically higher for instance your damage is an example.

Your auto shot hits were 39-40 with a 1.5 dps arrow 

the increase with a 91.5 dps arrow should be (your weapon speed) 2.3 x 91.5 = 210.45

but your damage increase is only 120 damage, with dummy armor as a factor in damage reduction it shouldn't be that low in comparison to your original shots with 1.5 arrow. 

This could simply be a general miscalculation of weapon damage with hunters where something is being missed, but I feel that it stems from ammo because Chimera/Aimed/Steady/Auto should all be greatly affected by ammo and they are currently marginally changing with ammo difference of 66 DPS

The difference of my average total DPS between using a 1 DPS arrow and a 67.5 DPS in a 3 min fight would roughly be around 1.5-2K DPS difference but I spent the whole night in heroics alternating and I will check in raids tonight the damage difference was around 100-200 TOTAL DPS difference per 3 min fight.

**Comment by Cwiercpasiec** [comment]
Your report states:
"How it works:
Ammunition's damage isn't being applied to weapon damage calculation formulas" Which obviously not true and I've shown you why in my first post. Damage didn't increase by 210 because of armor on dummy. You said "with dummy armor as a factor in damage reduction it shouldn't be that low in comparison to your original shots with 1.5 arrow." aaand that's not how it works here. You want something to be rapaired, provide some source, numbers etc., don't just guess. It is possible to calculate, how much exactly these shots hit, but I'm too lazy for this. Instead of calulating I prefered to find some targets with extremely low armor, so I tested damage with both types of arrows on level 1 mobs. Here are some screenshots:
Here is how much damage  were my shots doing, it varies from 64 to 68
![wowscrnshot_040118_201700](https://user-images.githubusercontent.com/26198742/38176453-809cde04-35ef-11e8-8742-48516f05a7ae.jpg)

And here I changed arrows to the 91,5 dps ones, damage varies from 270 to 274
![wowscrnshot_040118_202011](https://user-images.githubusercontent.com/26198742/38176481-0daf1848-35f0-11e8-9038-1c25310d56f1.jpg)

So damage increase is 274 - 68 = 206
Actual damage increase (before armor reduction) should be 2.3 * 90 = 207 (you forgot to subtract damage of low level arrows). From screenshots you can see that everything is working fine here. Please, don't make a fuss about this 1 dmg, it's probably caused by small number of attempts. The reason you and Soufly spent so much time to prove this bug is that simply there is no bug here.

**Comment by CMcDonald11** [comment]
Cwiercpasiec apparently your education on mathematics never occurred. Ur attempting to state that bosses have 50% damage mitigation to physical they do not. Next you state the damage is correct without recognizing the basic of how ammo is calculated in weapon damage.

**Comment by CMcDonald11** [comment]
If a dev would open their source or link their current equation for calculation it would be immediately apparent as to why it is occurring. Currently via damage calculations and testing it shows that using increased arrows is a flat additive in the form of dps to total damage.

**Comment by CMcDonald11** [comment]
This is incorrect becus in the equation you dive by speed in order to apply dps increase stats at a 1 second interval. Then you multiply by the speed at the very end to calculate for total hit not dps

**Comment by Soufly** [comment]
After so much calculation can we state that this is bug or not ?

**Comment by Cwiercpasiec** [comment]
First of all, I never stated that bosses should have 50% damage reduction. I have simply shown how much damage you actually do with both types of arrows on targets with armor and nearly without armor. That's not what I think, that's how it works now and I never said this is how much mitigation SHOULD dummy have, but how much it ACTUALLY HAS.  With my second post you can actually forget about the first one, because it is enough to disprove this bug report.  By the way, dummy took about 41% less damage than level 1 mobs, funny how you try to insult my math education and can't even calculate percentages properly, isn't it?

Second of all, what I wrote in my second post was regarding this line here:
"the increase with a 91.5 dps arrow should be (your weapon speed) 2.3 x 91.5 = 210.45", so I used author's calculations. Now, in this case it doesn't really matter, if you use whole damage equation (this one: Minimum Range = (((Minimum damage + Scope damage bonus) / Weapon Speed) + (Ranged Attack Power / 14) + Ammo DPS bonus) * Weapon Speed) or simply add to your previous damage (ammo DPS bonus * Weapon Speed), because in this case nothing else changes. This is simple math and someone as enilghtened as you shouldn't have problems with understanding this, right? Well, here is an example:

Our equation: 
Minimum Range = (((Minimum damage + Scope damage bonus) / Weapon Speed) + (Ranged Attack Power / 14) + Ammo DPS bonus) * Weapon Speed

Our stats (numbers are random, we just need them to calculate damage):
Minimum damage: 23
Scope Damage bonus: 0
Weapon Speed: 2,3
Ranged Attack Power: 42

Our Arrows (we will calculate damage for Rough Arrows - 1,5 dps and for Iceblade Arrows - 91,5 dps):
1. Rough Arrows: 1,5 DPS
2. Iceblade Arrows: 91,5 DPS

Calculations - damage output with 1.Rough Arrows:
Minimum Range = (((23 + 0) / 2,3) + (42 / 14) + 1,5) * 2.3 = (10 + 4,5) * 2,3 = 14,5 * 2,3 = 33,35 DPS

Calculations - damage output with 2.Iceblade Arrows:
Minimum Range = (((23 + 0) / 2,3) + (42 / 14) + 91,5) * 2.3 = (10 + 94,5) * 2,3 = 104,5 * 2,3 =240,35 DPS

So our output damage will increase by 240,35 - 33, 35 = 207 DPS.

Now let's calculate damage increase just by subtracting (weapon damage * lower ammo DPS bonus) from (weapon damage * higher ammo DPS bonus). This is the way I did it and you pointed it out as wrong. Here we go:

Damage increase = (2,3 * 91,5) - (2,3 * 1,5) = 210,45 - 3,45 = 207

As you can see, results are the same, so both methods are correct. This happens because of basic maths, funny how you couldn't get it right.

For the next time, please, think before you write, as you clearly didn't even tried to count anything here and you just wasted your time, my time and probably some people had to read this and lost some IQ points too. Also try to find some source or anything to prove you're right or disprove someone...
