### ISSUE TITLE
Quest "The Bloodcurse Legacy" cannot be accepted

### ISSUE THREAD

**Issue by whitestar87** [SunwellTracker/issues#1184]
Decription: The quest "the Bloodcurse Legacy" cannot be accepted.

How it works: 
Player recieves "A letter from the admiral" in their mail shortly after completing quest "urgent delivery" When you right click the quest starter, however, it says "You don't meet the requirements for that quest"

How it should work: 
Should right click letter to accept quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Works fine for me. What probably happened is that you completed quest http://www.wowhead.com/quest=9672/the-bloodcurse-legacy before. This quest is different from the one you get from the item, but you can complete only one of them. There are no other requirements for this quest, so that's my best guess.
