### ISSUE TITLE
A quest bug

### ISSUE THREAD

**Issue by PredatorBoSs** [SunwellTracker/issues#1185]
Decription: 
Well, there is a last quest in the quest chain in Zul'Drak called "The Storm King's Vengeance" . While i was riding Gymer everything was fine until i ran in to 1 minor and 1 big bug.

How it works: There is a mob u need to kill an elite called Thrym while riding Gymer. For some reason i can not see this mob. Even GM tried helped me to see what is the problem. I attacked Thrym (i wasn't riding Gymer) and GM killed him i didn't even get the quest completion. He didn't want to mess with it. For some reason right now Thrym is not even a part of a quest of killing him and in a different phases u can't even see him. Second minor bug is the storm cloud. When u grab the Storm cloud u can just throw it. 

How it should work: One part of the Gymer abilities says when u grab a Storm cloud says it heals Gymer and regenerate energy. I'm not sure about this but i think is like a glitch when you toss a mob it just explodes in your hand.  

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
You can't see him, because he's summoned after dealing with Prince Navarius - and this one is for quest, you can only see these mobs while riding Gymer. 
There is also Thrym walking on a road near, which can be seen when you're not controlling Gymer - it seems that you've attacked this one and he shouldn't be counted towards this quest!
http://www.wowhead.com/quest=12919/the-storm-kings-vengeance#comments:0

Also here's some info how reports should be named : https://sunwell.pl/page/bugtracker
"A quest bug" doesn't tell anything and reports named like that can't be found easily through search option
