### ISSUE TITLE
Malygos crashes 25m

### ISSUE THREAD

**Issue by gabbat** [SunwellTracker/issues#1215]
Decription: Raiders are randomly crashing (often once, often multiple times) during p2 of malygos and the start of p3

How it works: people crash

How it should work: people should not crash

Source (you should point out proofs of your report, please give us some source): 
any guild that progressed on malygos

**Comment by iamaio** [comment]
Can confirm, happened to me and some other raid members. Also this is a critical bug and should be given top priority because of 2 things:
1. Isn't replicable, the dcs are random so I doubt it is easily fixed and it should be looked at sooner rather then later.
2. With malygos "buffed" enrage timer if this bugs occurs once it's a 100% wipe... and last evening in several hours of tries it happened at least once a try. So as of now, not only people have to play the fight perfectly but they also have to hope for the bug not to occur in any player.
