### ISSUE TITLE
[Dying - Falling of Hellfire Peninsula] My ghost is falling down forever.

### ISSUE THREAD

**Issue by kedor89** [SunwellTracker/issues#1235]
Decription: 
After you die, if your ghost fall off the map, i can't do anything. 
I cant really play now.

How it works: 
Just make a character, die. Then as ghost, try to get to your corpse, and fall off map. 
Then you fall infinitely.

How it should work: 
I should get placed back somewhere, at spirit healer or something. 

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/ZyrNRrz.jpg

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/983

**Comment by xys007** [comment]
I confirm this bug still exist.
When a player falls out of the map he hit some invisible plane and he should instantly die. Nothing should prevent player from dieing. Even paladin's Divine Shield cannot prevent him from dieing instantly.

But when a priest with Spirit of Redemption talent hits this plane, he does not instantly die. Spirit of redemption triggers turning priest into a Spirit of Redemption. It does not cause problem yet, but after Spirit of Redemption fades or is manually removed, priest is turned into ghost form with 2 hp, but he is not moved to nearest graveyard. He is stuck on this plane, can't move, can't logout because game says can't logout while falling. The only solution is ALT+F4 but it also removes player from battleground or raid, marks player as a deserter. So this is quite unpleasant solution. Auto-Unstuck also does not work because "player is moving".

Proper behavior is that Spirit of Redemption should not be triggered when falling out of map. (Why should it anyway).

Easiest way to reproduce this bug is to dismount from flying mount somewhere outside the edges of Outland. But it happens anywhere where player falls out of map. For example in The Oculus instance which is specifically designed in this way to kill falling players. Also happened to me when i was feared into textures in Warsong Gulch battleground.
