### ISSUE TITLE
[Shadow Priest Dots] - Not Effected by haste at all

### ISSUE THREAD

**Issue by Punkndrublic** [SunwellTracker/issues#1304]
Decription:
When Casting Devouring Plague, Vampiric Touch, or Shadow Ward Pain, No amount of haste affects them as it should. 

How it works:
Currently SWP ticks 6 times, VT ticks 5 times, and DP ticks 8 times. I have tested using pots, food and gear. You get the same amount of ticks whether you have zero haste, or 1000

How it should work: 
There should be Break points where you get extra ticks. Shadow form States that it grants DP and VT the ability to benefit from haste, This does not happen in anyway, shape, or form currently... not even in the wrong way, like adding damage. 

Devouing Plague should get new ticks at:  322, 701, 1,080, 1,459
Shadow Ward Pain should get new ticks at:  6, 511, 1,016, 1,521
Vampiric Touch should get new ticks at:  57, 663, 1,269

https://www.mmo-champion.com/threads/782954-DoT-haste-breakpoints

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
Your source regards Cataclysm. On WotLK haste did not affect DoTs and HoTs unless you had a talent/glyph changing it (for example shadoform lets DP and VT to benefit from haste or Glyph of Quick Decay lets Corruption to benefit from haste). Also on WotLK haste only reduced time between ticks and didn't add any ticks.
http://forum.warmane.com/showthread.php?t=322682 Here you can read about it.

**Comment by Punkndrublic** [comment]
Ok so assuming I remembered incorrectly and there were not more ticks, just Faster Ticks, It's Still Broken. With 1000 haste, SWP still only ticks 6 times, and takes 18 seconds to do that, zero haste still 18 seconds. Also you are not Correct about this Being From Cata, the date of the post and the Poster Says 3.3.5 Also look at the Numbers.... Just looked up Gear in Cata, and it had like 361 haste on one piece of gear, 2500-3000 haste was possible. The fact is you are just out and out Wrong, i played as a Shadow priest in Wrath, haste was the Shit. Definitely got MORE dot ticks

**Comment by Cwiercpasiec** [comment]
First of all, Shadow Word: Pain does not benefit from haste. Here you can read the patchnote:
http://wowwiki.wikia.com/wiki/Shadowform
"Patch 3.3.0 (08-Dec-2009): This talent also now causes Devouring Plague and Vampiric Touch to benefit from haste. Both the period length and the duration of these spells will be reduced by haste. In addition, the mana cost has been reduced from 32% to 13% of base mana."
SW:P is not mentioned here. 
Here are full 3.3.0 patchnotes: http://wowwiki.wikia.com/wiki/Patch_3.3.0
As I mentioned, haste didn't affect DoTs on WotLK, but on patch 3.3 blizzard added some talents/glyphs that let haste to reduce time between ticks of some "over time" spells. Shadow Word: Pain was not one of them. This also tells us why in this guide https://forum.twguild.org/index.php?topic=6520.0 someone didn't mention anything about DoTs being shorter. Simply this guide was written before 3.3 changes and haste didn't affect DoTs back then. 

I linked a discussion from 2016 because I hoped it would be enough for you, guys talking there agreed that additional ticks were added on Cata, noone argued about this. Because it was not enough for you, I had to do more research, to prove that you are wrong. So yes, I linked 2016 forum because I was lazy.

Now, for the final proof, here is a video from 2010, when people on retail were playing WotLK:
https://www.youtube.com/watch?v=OHCcv2YrppI
At 1:31 priest uses his racial, that's when it is easily visible, that Vampiric Touch lasts about 9.5 seconds, so no additional ticks were actually added (according to your source, linked in the first post, VT shouldn't last less than 12 seconds, right?).

**Comment by Punkndrublic** [comment]
Ok so you have first off proven your point, and second provided the Sunwell Guys with pretty much concrete Evidence that Shadow priests are Broken and that dots (VT and DP) are not being effected by haste as is referenced multiple places that they should be, even if it's a shorter overall duration and not extra Ticks. Hopefully they will take notice and fix this issue.

**Comment by Cwiercpasiec** [comment]
Vampiric Touch and Devouring Plague should benefit from haste ONLY if the caster was in Shadowform and this is how it works on Sunwell. Here are some screenshots: 
VT cast in Shadowform (14s):
![wowscrnshot_050118_013042](https://user-images.githubusercontent.com/26198742/39455291-f3bb614c-4cdf-11e8-9af0-36a13eda6de7.jpg)

VT cast without Shadowform (15s):
![wowscrnshot_050118_013052](https://user-images.githubusercontent.com/26198742/39455311-09493d36-4ce0-11e8-8b3a-81361a786093.jpg)

DP cast with Shadowform (22s):
![wowscrnshot_050118_013107](https://user-images.githubusercontent.com/26198742/39455324-1a33d796-4ce0-11e8-91e0-1b0f4f73e12b.jpg)

DP cast without Shadowform (24s):
![wowscrnshot_050118_013112](https://user-images.githubusercontent.com/26198742/39455334-2a68c7e8-4ce0-11e8-82b5-213e8538b31a.jpg)

My priest has only 234 haste, so the difference is not really that big, but still it's noticeable.

**Comment by Punkndrublic** [comment]
The Tool tip Does not Change though does it, and What UI addon is that to view your dots like that

**Comment by Cwiercpasiec** [comment]
Yup, tooltip does not update, but I'm not sure if should. AddOn is PlateBuffs (but for PvE I'd reccomend TellMeWhen or PowerAuras, PlateBuffs are not really visible on bigger targets).

**Comment by Punkndrublic** [comment]
I was not able to find a Version of Power aura's that worked, But thank you for the info.
