### ISSUE TITLE
Omen of Clarity

### ISSUE THREAD

**Issue by helos23** [SunwellTracker/issues#1348]
Decription: 

How it works: When I use Hurricane, Typhon, Starfall it never proc

How it should work: When I use Hurricane, Typhon, Starfall, I have a chance to proc Omen of Clarity

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I'm not sure if those issues i connected but Omen of Clarity was reported on Feronis bugtracker (report is in polish - https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/754) but it ended with two links:

> http://www.mmo-champion.com/threads/622133-Omen-of-Clarity-Hurricane-Ninja-Nerf
> http://eu.battle.net/wow/en/game/patch-notes/3-0-3
> Druid: Omen of Clarity now has a reduced chance to be triggered by Hurricane.

**Comment by helos23** [comment]
We have patch 3.0.3 or 3.3.5 ?   If 3.0.3  why another class work as 3.3.5   ( affi warlock corruption ticks faster when have more haste, shaman can stop cast with wind shear   should earth shock,   ect...

**Comment by Cwiercpasiec** [comment]
Angrathar has patch 3.3.5a and content 3.0 (naxx). Simply every skill, talent, glyph, etc. works in the way it worked (or at least should, there are some bugs ofc) on 3.3.5a, but players do not have acces to (most) items and vendors which were added post patch 3.0. It has to be this way, because changing it according to every patch would require too much work. Also this would require downgraded client version, as talents/skills/glyphs etc. tooltips would be wrong and even some tallents would have to be moved higher or lower. And that's not all.
Either way, Dootz linked patchnote 3.0.3 because Clearcasting proc from AoE wasn't changed after this patch, so basically it worked like that on 3.3.5a. If u think that's wrong, you should provide some proof (like a patchnote, logs from retail, video from retail, whatever proves your point). That's what the source is for (you conviniently left it empty, didn't you?).
