### ISSUE TITLE
Freya - Ancient Water Spirit

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#1470]
Decription: Ancient Water spirit doesn't behave like it should.

How it works: Ancient Water Spirit uses Tidal Wave **always** on the tank (in that angle). Ancient Water Spirit is also immune to stun-effects. 

How it should work: Ancient Water Spirit should target a random player with Tidal Wave. Ancient Water Spirit should be stunnable but not interruptable [source](http://wowwiki.wikia.com/wiki/Freya_(tactics))

Source (you should point out proofs of your report, please give us some source): 
https://world-of-warcraft.alteredgamer.com/wow-bosses/40950-wow-ulduar-raid-boss-guide-freya/ 
"**It will randomly charge someone in the raid**"

https://youtu.be/HJ1gxZZSRtI?t=159 "**Ancient Water Spirit will periodically charge and knockback a player including any other raidmembers near him.**"

During both Ensidia's and Method's killvideos of Freya HM they use stunns on the Ancient Water Spirit to keep it in place: https://youtu.be/w2w2973jfBo?t=132 , https://youtu.be/7wxv88pA3Ew?t=186

**Comment by ntt1** [comment]
Pretty uneducated report - ancient water spirit should be affected by all sorts of cc, not only stuns, except interrupt:
http://www.wowhead.com/npc=33202/ancient-water-spirit#comments


"The Ancient Water Spirit can be affected by the following (not limited to) in order to stop Tidal Wave: Stuns, Fears, Gouge, Blind, Counterspell, Arcane Torrent, Silence Shot, Wyvern Sting, Scatter Shot.

Kick does not work, at least not for me. This probably means conventional interrupts are not an option. Kick does work, however, on the Storm Lasher. "

If you were looking to make this boss easier for your raid, now every 4th Tidal Wave will destroy your raid, as you wont be able to interrupt it because of DR.

Extremely questionable decision from the developers as well to decide to implement the fix on the middle of the raid week, without checking all the facts.

**Comment by Chryslol** [comment]
How often does the Ancient Water Spirit use Tidal Wave? Check the videos, when being stunned during Tidal Wave the cooldown of Tidal Wave triggers (probably). Does it here aswell or does the mob spam it until it goes trough? 

Good points tho.

**Comment by ntt1** [comment]
The gap between Tidal Wave is 10 seconds, DR reset is 15 seconds, you can do the math.

**Comment by Chryslol** [comment]
https://youtu.be/7wxv88pA3Ew?t=22

Method literally chain a stunn on the Ancient Water Spirit every 10 seconds intervall. You can clearly see the animation of it being stunned aswell.
