### ISSUE TITLE
Hunters can NEED on spell power mail items

### ISSUE THREAD

**Issue by rookasas** [SunwellTracker/issues#1472]
Decription: Today a hunter has needed on a spell power mail item and won it against me (a shaman healer), then he quit and never responded to my messages.

How it works: Hunters need on items completely useless to their class then sell it to vendor.

How it should work: Only shamans should be allowed to need on spell power mail items.

Source (you should point out proofs of your report, please give us some source): https://ibb.co/d192fy

**Comment by Cwiercpasiec** [comment]
Not a bug, blizzlike behavior.
Random post from blizz forum:
https://us.battle.net/forums/en/wow/topic/1020863715
"One thing I would love to see implemented by Blizzard is a new looting system where in order to roll on specific items, the player would have to queue specifically for that role in the dungeon. Things to take into account would be: shaman healers rolling on agility/haste/crit items (provided enhancement shaman need no intellect now) against a hunter and a rogue (which definitely would need it more in the current situation)."

**Comment by rookasas** [comment]
My apologies then. Is there a chance that devs would consider the implementation of a role based rolling system? I think it would improve the overall experience of the players slightly.
