### ISSUE TITLE
[General Vezax] Corrupted Wisdom

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1491]
Decription: 
Corrupted Wisdom isn't reducing heals by 90% for Paladins with Judgements of the Wise talent.

How it works: 
https://db.darkwizard.pl/?spell=64646
Seems to only affect Holy Shock on this server.

How it should work: 
Should not affect Holy Shock, but instead Holy Light and Flash of Light

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/spell=64646/corrupted-wisdom
https://www.mmo-champion.com/threads/639080-Vezax-s-Corrupted-Wisdom

**Comment by Kokaina** [comment]
Fixed.

**Comment by stopskii** [comment]
OP's post says:
> How it should work:
> Should not affect Holy Shock, but instead Holy Light and Flash of Light


From what I can tell, Holy Shock _should_ be affected along side Holy Light and Flash of Light.

Quote from OP is contradictory to info provided by 2 of the links included in the OP's post. Both of these links say Holy Shock is in fact affected:
https://db.darkwizard.pl/?spell=64646
http://www.wowhead.com/spell=64646/corrupted-wisdom
On wowhead, click see more. You can see that it also affects Holy Shock.
No where in the links in OP's post does it say Holy should should not be affected.
I have not tested this out on Frosthold server yet because Ulduar is not released.
The mmo-champion link does not mention holy shock and whether or not it is affected.
