### ISSUE TITLE
CC bug in PVP

### ISSUE THREAD

**Issue by mbark1996** [SunwellTracker/issues#1519]
Decription: 
i will try to make it simple , EXAMPLE , im a mage , i polymorphed a player , he will get a 9 seconds CC , if i polyed him again while he is INSIDE the poly , THE first poly will break and he will get a new one with less DR , this is the first time i ever seen this in arena ,
How it works: 
note i think it happens in every cc like the sap or fear , so spamming the cc dosent work cus i will break my cc when i cc which is not correct if you dont understand /w CAZZERT and i will duel you to show you thank you .

How it should work: 

when i spam cc on someone the cc should not break into a new one with less DR it just appears that i  him and nothing happens thats how it should work not breaking it and cc the target again with less DR .
Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
False report.

There's something called "Diminishing returns". Google it. Reapplying your CC breaks the old one and overwrites it with the next DR duration wise.

**Comment by Azathothh** [comment]
Ujellyx seems like you didn't understood what author meant. 
mbark1996 says that if you cast for example polymorph for the first time - so it lasts 10sec - and then cast it once again while duration of previous one is still LONGER than 5sec then it would fail with "a more powerful spell is already active" error (since applying it 2nd time would reduce duration because of DR). If you would cast it 2nd time when 1st one had 4sec left then 2nd one would be applied with 5sec duration.
https://www.youtube.com/watch?v=85I5zuJQIb4  - it happened here at 0:00 and 0:09 (it's not Wotlk though - something between patch 2.0.1 - 2.2.0)
https://youtu.be/YZzh2MzAfrs?t=6m14s - when paladin hits druid 2nd time - 2nd stack of Nature's Grasp is used, druid gets "A more powerful spell is already active" error, duration of Entangling Roots doesn't change (bad quality, but this one is wotlk)

**Comment by ujellyx** [comment]
That's not at all what OP said... 
"if i polyed him again while he is INSIDE the poly , THE first poly will break and he will get a new one with less duration"

I don't see a bug here. You can reapply CC even when the first one has higher duration...

**Comment by Azathothh** [comment]
Yeah, he could explain it much better than he did, i agree :P 
But i've seen what he wrote on our forum " for example if i polymorph someone he gets 9s poly but if i casted the poly again while he still have 9s poly , the polymorph breaks and he gets a second one for 5 second" and you've seen that as well

"I don't see a bug here. You can reapply CC even when the first one has higher duration..." That's exactly where the bug is ( of course nobody is saying that you shouldn't be able to reapply CC again until previous is gone) - already gave one example how it should work but i guess i'll try again:
Polymorph : 1st cast 10sec, 2nd cast 5sec, 3rd cast 2.5sec
10sec polymorph applied -> you shouldn't be able to apply it again when duration of 1st is between 5sec-10sec , spell will fail with "A more powerful spell is already active" error -> when duration of 1st one is LESS than 5sec you should be able to apply 2nd one which will last 5sec -> again next polymorph will fail if it will be applied  when duration of 2nd one is between 2.5sec-5sec

**Comment by ujellyx** [comment]
Yeah, now I get it :)

**Comment by mbark1996** [comment]
so is this going to be fixed ?

**Comment by Azathothh** [comment]
Yes, but i can't give you any ETA. You will either find info here or issue will be closed when it's fixed.
Please don't spam/bump etc. unless you have some more informations regarding issue that you would like to share.
