### ISSUE TITLE
Spells do not reset the swing timer

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#156]
Decription:  
Spells do not reset the swing timer.

How it works: 
Currently, some spells do not reset the swing timer, so if you start attacking while casting, you will perform a melee attack just as the casting finishes. Not all spells behave this way, for example, i found that lightning bolt and chain lightning do not, while healing spells do reset the swing timer properly.

How it should work: 
All spells that are cast should reset the swing timer after the spell is cast.

**Comment by Kokaina** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/4679
Any comment?

**Comment by Elaatu** [comment]
Ma Pan dowód?

**Comment by mondegoftw** [comment]
Spells should only reset the swing timer for certain classes. If they did for every class, hybrid specs like Retribution or Enhancement would be almost unplayable.

For priests, warlocks, mages and possibly druids the swing timer should be reset, but not for other classes.

**Comment by sonrakus** [comment]
Spells with a cast time should reset it, instant spells should not. No instant spell should reset the swing timer, the act of casting itself should.

**Comment by Kokaina** [comment]
Sonrakus is right here, instant spells don't reset swing timer but spells with cast time shall do.

mmochamp:
https://www.mmo-champion.com/threads/624759-*Enhancement-Shaman-FAQ-(3-3)*
Lava Burst will always have a cast time, it will reset your swing timer, that means no white damage, no windfury procs, no maelstrom stacks ie: no dps whilst casting, this is just bad and other than situations where you are rooted, trapped or otherwise unable to be in melee range it shouldn't be used by an Enhancement Shaman. You may wonder how on earth you can track all these different cooldowns, well of course there are plenty of cooldown tracking addons out there including the one written for Enhancement Shamans (by myself) called ShockAndAwe - you can download it from here.

elitejerks: https://archive.is/6SLfn
The use of the instant cast spell does not interrupt the swing timer of the shaman's auto attacks. If a cast is made with fewer then 5 stacks the swing timer continues and if the cast timer clips the swing timer then the swing timer is reset. If you are using 2 slow weapons then you may be able to slip a 4 stack MW cast between swings but if you are using a fast offhand it is not advisable since if either swing timer is clipped the dps loss will most likely outweigh any benefit gained from casting it early.
Unlike many PPMs, Maelstrom Weapon scales with weapon haste. It can also proc from Stormstrike or Lava Lash. An enhancement shaman with raid haste buffs and using all available instant attacks will see 5 stacks very frequently. Slow weapons give the best results, as slow weapons will have a higher proc rate per swing. More viable at level 80 when most Enhancement Shaman will have significantly more intellect, and a larger mana pool, from their gear.
Chain Lightning will produce more base damage than Lightning Bolt, but Lightning Bolt has a higher coefficient than CL. This means that LB will scale rapidly compared to CL and in a single target environment LB will produce superior DPS.
edit for clarification: Casting with fewer than 5 stacks will reset the swing timer however and therefore results in a significant decrease in DPS...
