### ISSUE TITLE
[Npc] Legion Commander Yorik - sometimes doesn't reset after event

### ISSUE THREAD

**Issue by tymczak** [SunwellTracker/issues#1577]
Decription: 
It's the last part of series of chain quests starting with a quest "Into Hostile Territory"

How it works:
You go to turn-in the quest to Legion Commander Yoric, but you can't interact with this npc, you don't have "?"sign or anything, you can't take the follow up "An End And A Beginning"

How it should work: 
You go to turn-in the quest to Legion Commander Yoric, giving him quest item called Thel'zan's Phylactery, after finishing the quest you get the follow up "An End And A Beginning"

![wowscrnshot_062218_222820](https://user-images.githubusercontent.com/40502771/41797817-b948d67e-766b-11e8-8108-9c7d078fc593.jpg)

**Comment by Azathothh** [comment]
Looks like there's no problem with Finality quest - problem is with Legion Commander Yorik - you couldn't complete it because he didn't reset after event started by someone else in "An End And A Beginning" https://db.darkwizard.pl/?quest=12473.
Seems like rare issue (he should be working now).

https://db.darkwizard.pl/?npc=27857 - Legion Commander Yorik
