### ISSUE TITLE
[Hunter] Sending in pet doesn't make you "unsappable"

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#1615]
Decription: 
On retail a pet class could become unsappable just by sending in the pet. Although this was probably not intended by Blizzard it was how it worked. This probably effects other pet classes aswell.
I'd understand, as this was a "bug" on retail, that this won't be changed here, but it's worth a try as it was part of the real WotLk experience.

How it works: 
Sending in the pet doesn't change the fact, that you can get sapped.

How it should work: 
Only sending in the pet shouldn't put you in combat, BUT it should make you unsappable.

Source (you should point out proofs of your report, please give us some source): 
http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/
http://www.arenajunkies.com/topic/154952-pet-combat-sap-bug/
http://www.arenajunkies.com/topic/72876-pet-combat-bug/

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/524
https://github.com/SunwellTracker/issues/issues/553
from comments it looks like it was working for warlock/dk some time ago.

**Comment by Akha72** [comment]
So in report 553 we got dev's response:
You're now able to sap a player whos not in combat even if he sent his pet on target, because we decided to resolve that bug that blizzard had in the past. Also resolved an issue where guardians would instantly set victim in combat rather than when they actually hit him, as far as sending pet on target behind LoS, ill write it down as ToDo after our movement rewrite. Closing for now

yet in changelog:
All Stealth auras usable in combat (Vanish/Shadowmeld) will allow to evade already flying spells.

So what is the reasoning behind preserving some blizzlike features and 'fixing' other ones?
