### ISSUE TITLE
Mjordin Combatant [mob] randomly buffed, significatnly in icecrown 

### ISSUE THREAD

**Issue by anticlutch** [SunwellTracker/issues#1723]
Decription: 
The mob named Mjordin Combatant NEVER had a jump attack ability on retail or as recently as 3 days ago on Sunwell-Angrathar. All of the sudden I'm farming these mobs and there are three significant changes;

How it works: 
They have a much larger aggro radius
They do significantly more damage
They now have an ability where they jump at you from range and land on your character attacking you.
 
How it should work: 
Damage needs to be put back to normal.
Aggro range needs to be put back to normal.
Jump ability needs to be removed.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/RofB7b4

I had been farming these for 10+ days then had two ish days off. There were two server resets in those two days where I didn't farm the mobs and now the mobs are changed.
I can only pull 1/3rd to 1/2 of the mobs without dying and have to segment the group up.
2 days ago I could pull every mob and not drop below 70% hp. Now I drop to 15% with only a small portion of the whole.

Why was this changed?
Why does Sunwell not want me farming there?

**Comment by Dootz** [comment]
Their AI was updated with last server update.
1. The aggro range hasn't changed
2. They do more damage probably because now they correctly use their abilities.
3. As you can see in the linked video from 2011 they are using this ability

https://youtu.be/qBX42r2j3bk?t=32s
http://www.wowhead.com/npc=30037/mjordin-combatant#abilities
