### ISSUE TITLE
NPC: Dreghood Geomancer

### ISSUE THREAD

**Issue by FolMing** [SunwellTracker/issues#1799]
Decription: 
These NPCs don't stop attacking you after Illidari Taskmaster is killed.

How it works: 
Geomancers continue to attack you

How it should work: 
Geomancers should flee after killing Illidari Taskmaster

Source (you should point out proofs of your report, please give us some source): 
Well, Brutes run away, why Geomancers shouldn't?

**Comment by Dootz** [comment]
well, Brutes run away because it is documented behavior:
https://www.wowhead.com/npc=16938/dreghood-brute#comments:id=177065
http://wowwiki.wikia.com/wiki/Dreghood_Brute
in case of Geomancers i wasn't able to find such information:
http://wowwiki.wikia.com/wiki/Dreghood_Geomancer
https://www.wowhead.com/npc=16937/dreghood-geomancer#comments
