### ISSUE TITLE
Timedelay after landing

### ISSUE THREAD

**Issue by lordhelmchench** [SunwellTracker/issues#1839]
Decription: when flying with a flightmaster mount there is a timedelay after arriving at the destination and the moment when the game let me play again.

How it works: the longer the flight is, the longer it takes till the game registers the arrival at the arriving point. If flying across have the map (from Lights hope (E. Plaguelands) to Flame Crest (Burnng steppes), the wait time is about 20-30 seconds.

How it should work: Flying, arriving and mount despawns.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/jmCwoviQ0fc

**Comment by Anachrony** [comment]
Could be lag, or some other client side issues.

**Comment by Dootz** [comment]
I got the same issue playing on a retail earlier this year. Not saying it means anything, but it might be just a connection related thing rather than server side issue. You could check how long it takes from your end to server with ping command in command prompt. Just ping our domain at logon.sunwell.pl. You can also test a few other things. At first, you can try to disable add-ons (maybe some of them are loading information for the new place as you arrive), Next, you can try to lower your game graphics quality. I know it might sound weird in 2018 but sometimes there's a lot to render on your screen if. Do you experience such delays only after landing or maybe in other situations like entering instances?
