### ISSUE TITLE
[Mechanic?] Mob hit table

### ISSUE THREAD

**Issue by zenots** [SunwellTracker/issues#1846]
Decription: Something is wrong with the mob hit table, but I'm not exactly sure what. They appear to have 6.8% more hit rating then they should. At least, this has come to my attention on heroic anub'arak adds.

How it works: The mobs seem to require a 108.4% avoidance total to mitigate all incoming attacks. Based off logs from last night, where I had 104.55% avoidance and took 3.812% unavoided attacks.

How it should work: The adds should be unable to hit me with a total of 101.6% avoidance, and bosses should be 102.4%.

Source (you should point out proofs of your report, please give us some source): 
https://www.mmo-champion.com/threads/679886-Heroic-Anub-arak-25-Tank-gearing-question
https://www.mmo-champion.com/threads/668302-Block-and-anubarak
https://www.wowhead.com/forums&topic=130182

https://media.discordapp.net/attachments/465115108922753024/496439037419323412/unknown.png screenshot of log, can link entire log if requested.

**Comment by zenots** [comment]
I tried again tonight with 108.55% avoidance, and still had a total of 3% unblocked attacks. So it seems like the issue might be that there's some kind of minimum hit chance that mobs are being given? Considering at 104.55% I had 3.8% unblocked, and now at 108.55% I still have 3% unblocked.

http://www.worldoflogs.com/reports/hgfslmkgozv80xiy/details/13/?enc=bosses&boss=34564

**Comment by zenots** [comment]
Adding a log of the kill, where I had 109.54% total avoidance out of the 101.6% "required".
http://www.worldoflogs.com/reports/7dmeta7m2c1ff6at/details/1/?s=5561&e=6142
Where I have 35, or 1.6%, unblocked/unavoided attacks. I'm really not sure where the issue is coming from, as it's quite a difficult thing to test on my end (especially on a boss we're trying to progress on and get 50/50 ;P)

**Comment by Azathothh** [comment]
I don't understand where do you see any problem in the log from the kill (last link that you've posted) :
http://www.worldoflogs.com/reports/7dmeta7m2c1ff6at/xe/?s=5561&e=6142&x=type+%3D+TYPE_DAMAGE%0D%0AAND+targetName+%3D+%22Zenwar%22%0D%0AAND+sourceName+%3D+%22Nerubian+Burrower%22
it shows that not a single melee hit from Nerubian Burrowers were unblocked.


Part of logs from previous logs (raid 03.10.18) :
![obraz](https://user-images.githubusercontent.com/37483678/46914440-ee528280-cf9d-11e8-89ab-6fd4533c29b8.png)
Again - all attacks are blocked, and then 4 in a row aren't, timestamps shows that these adds were new ones(or maybe submerged earlier?) which may indicate that it's caused by bad positioning.

**Comment by zenots** [comment]
I mean, I don't know what's causing the expression editor to be missing hits, but 
![055c967a015020ccdb8b1532ca9833d5](https://user-images.githubusercontent.com/40509263/46915084-7f146880-cf74-11e8-9657-650ed17a755a.png)
clearly shows 35 unblocked hits, and you can see my only sources of damage taken were Anub's Leeching Swarm + Penetrating Cold, and Burrower melees. And that was with 109.55% avoidance.

While the previous log shows 149 unblocked attacks with 108.44%.

You can confirm these hit numbers by looking at the buffs gained tab, in the kill log you see I had 159 applications of Expose Weakness, and 126 blocked attacks + 35 unblocked attacks for a total of 161. (2 got resisted or something)

**Comment by Azathothh** [comment]
It's not a problem with expression editor missing hits (it's not missing anything), but rather with what is counted as a "hit" by worldoflogs and what's not. Seems like these 35 "hits" is completely absorbed damage - simply there were no dmg to be blocked, so combat log won't show that 0dmg was blocked.
Here - you can count it up:
http://www.worldoflogs.com/reports/7dmeta7m2c1ff6at/xe/?s=5561&e=6142&x=missType+%3D+MISS_ABSORB%0D%0AAND+sourceName+%3D+%22Nerubian+Burrower%22%0D%0AAND+targetName+%3D+%22Zenwar%22

**Comment by zenots** [comment]
No that's simply a coincidence that I fully absorbed 35 attacks as well (as you can see on the far right), WoL considers fully abosrbed attacks as misses. You can see I took a total of 58985 damage from those 35 unblocked attacks.

For reference, the other log my absorbs and unblocked did not match. http://www.worldoflogs.com/reports/hgfslmkgozv80xiy/xe/?enc=bosses&boss=34564&x=missType+%3D+MISS_ABSORB%0D%0AAND+sourceName+%3D+%22Nerubian+Burrower%22%0D%0AAND+targetName+%3D+%22Zenwar%22 Shows 137 lines 
![30d83ade68ee0ac44e0a8a1f94bfb935](https://user-images.githubusercontent.com/40509263/46915886-6742e180-cf80-11e8-9726-9fed4b1a16b0.png)
Shows 137 absorbs and 149 unblocked.

**Comment by Azathothh** [comment]
No, it's not a coincidence - fully absorbed attacks are shown in misses as absorbs, you are right here, but it's shown in "hits" as well with amount of fully absorbed damage added to "Total" (under Hits).
"You can see I took a total of 58985 damage from those 35 unblocked attacks." just open logs from that fight and check full absorbs: http://www.worldoflogs.com/reports/7dmeta7m2c1ff6at/xe/?s=5561&e=6142&x=missType+%3D+MISS_ABSORB%0D%0AAND+sourceName+%3D+%22Nerubian+Burrower%22%0D%0AAND+targetName+%3D+%22Zenwar%22
58985 damage absorbed in full absorbs - is that a coincidence as well?

And in raid from 03.10.18 it shows 137 absorbs and 149 unblocked because 12 were not blocked and not absorbed fully (i've even pasted screen above with 5 of such hits).
First try : 7 unblocked hits , 2nd try: 1 unblocked hit, 3rd try: 4 unblocked hits
7+1+4=12 ,   12 unblocked+137 fully absorbed hits = 149 "unblocked"
Here you can see those 12 unblocked and not fully absorbed hits: http://www.worldoflogs.com/reports/hgfslmkgozv80xiy/xe/?enc=bosses&boss=34564&x=fullType+%3D+SWING_DAMAGE%0D%0AAND+targetName+%3D+%22Zenwar%22

**Comment by zenots** [comment]
http://www.worldoflogs.com/reports/tey7s0w4dymtihaa/xe/?s=10672&e=11282&x=type+%3D+TYPE_DAMAGE%0D%0AAND+targetName+%3D+%22Zenwar%22%0D%0AAND+sourceName+%3D+%22Nerubian+Burrower%22 here is the log of the first attempts, where I had the more reasonable 103% avoidance.

**Comment by zenots** [comment]
Where I took 9 unblocked / unabsorbed attacks.

**Comment by Azathothh** [comment]
You could tell that you've recorded it - would be much easier and quicker to just check video to see that they've been hitting you in your back : https://www.twitch.tv/videos/317931824?t=04h24m04s
Got a recording from 30.09 as well?
Also which macro/addon are you using to check your current total "avoidance" (it's still called avoidance but technically it's wrong, since it was reffering to crushing blows in tbc)?
I've tested 3 different ones found with help of google and they are all showing different results ;)

**Comment by zenots** [comment]
Yeah, I definitely will admit that I had been hit in the back a couple times early on, but there were also times where I would not move, with the mobs not moving, and then I just take huge hits. That was when I was at 103% with 3.4k block value, which SHOULD mean I take 0~ damage.

I don't have my own recordings of 30/09 since twitch auto-purged them, but I do have some youtube recordings from other perspectives that I'll link at the bottom.

/run ChatFrame1:AddMessage(format("Unhittable at 102.4%% - you have %.2f%%", GetDodgeChance() + GetBlockChance() + GetParryChance() + 5 + 1/(0.0625 + 0.956/(GetCombatRating(CR_DEFENSE_SKILL)/4.91850*0.04))))

That is the macro I am using, and yeah it's to calculate uncrushability, not actual avoidance. I use 

/run ChatFrame1:AddMessage(format("Total avoidance: %.2f%%", GetDodgeChance() + GetParryChance() + 5 + 1/(0.0625 + 0.956/(GetCombatRating(CR_DEFENSE_SKILL)/4.91850*0.04))))

to calculate actual avoidance.


https://www.youtube.com/watch?v=dwLBoDIwp0w&feature=youtu.be here is a recording of one of our attempts from 30/09, at 38s my health spikes as if I took an unblocked attack and you can see neither me nor the mobs moved. It's hard to tell for sure but my health should never take that much damage, especially with 3 stacks (which I should have had 0 of considering my block value and avoidance).

At 3:04~ you can see ajjtem taking a 16k unblocked hit, he was also at 103% avoidance.
6:48~ ajjtem takes 2 more unblocked hits, with 0 movement.
Then my death at the end was me getting hit on the side due to hpal with RF pulling the mob past me then dying. :P

**Comment by zenots** [comment]
One thing I did notice that might just be coincidental, but maybe worth considering? All of 3 those time stamps of unblocked attacks, happens within 3-4s of the mobs no longer being stunned. Really I wish I could have tested more while I was still closer to the 101.6% avoidance required, but I was definitely taking more damage in those attempts (excluding the times where I instantly die due to being hit from behind), despite having much more shield block value. (I sacrificed block value to stack more avoidance very early, considering the logs definitely made it look like I was taking unblocked attacks. I hate World of Logs... why would they show full absorbs under hits?)
