### ISSUE TITLE
[Battleground][Strand of the Ancients][PvP] Bugs in Strand of the Ancients

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#185]
Decription: 
Found many bugs during the earlier SotAs BGs..
1-LoS in destroyed gates
2-Passenger players.
3-Passenger player facing.
4-Turret damage scaling
5- Vehicle HP scaling

How it works: 
1-LoS in gates: After a gate is destroyed the remnants still count as LoS towards charge and other spells sometimes, impeding proper casting until you cross to the other side.
2-Players in the passenger seats are completely untargeteable by direct spells and AoE until demolisher is destroyed. You can't even target yourself for healing or anything while in passenger seat.
3-Players have issues with their casting while in demolisher.
4-Turret damage should be increased with level but it isn't.
5-Vehicles (turrets and demolishers) should scale their HP with the gear of the driver but they don't.

How it should work: 
1-Once a gate is destroyed it should not impede casts from one side of the gate to the other.
2-Passengers should be individually targetteable by spells or AoE (from players or turrets) while riding the passenger seats of the demolisher. They should also be able to target themselves 
3-You can cast while moving on passenger seat but have facing issues so you can't properly direct your spells.
4-Turret damage should be a base 4000 and increase 200 dmg per level of the player on it
5-Vehicles HP should scale with the gear of the rider, The more geared they are, the more HP the vehicles should have.

Source (you should point out proofs of your report, please give us some source): 
1- https://www.youtube.com/watch?v=klIjRpZYNxM (3:45) (Ragnaros US realm video)
You can see players using spells and channeled from one side of the gate to the other after it was destroyed.

2-http://wowwiki.wikia.com/wiki/Strand_of_the_Ancients
"It can hold up to 3 passengers, including the driver. Passengers are exposed and can be targeted individually. However, the side passengers can cast while the vehicle is moving if they're in it."

3-This is a bug that doesn't really demand proof. Players can cast spells with no facing restriction with no issues but those  that require you to be facing your target can be really tricky to use even after moving facing with mouse (dragging right click).

4-http://wowwiki.wikia.com/wiki/Strand_of_the_Ancients
"Patch 3.0.8 (2009-01-20):
Antipersonnel Turrets will now gain vehicle immunities, use falloff damage, and damage increased to 4000 + 200 per level to compensate for falloff."
https://www.youtube.com/watch?v=klIjRpZYNxM (0:10-0:30) (Same video)
You can see how turret damage is greatly increased, doing up to 8k dmg on hit when hitting demo with center of the rocket. The 200 per level is from every level over 70, since that is the minimum lvl to queue SotA.

5-http://wowwiki.wikia.com/wiki/Battleground_Demolisher
This link is to the NPC from the Wrath of the Lich King Battleground Demolisher, as you can see it is level 70-80 located in SotA. You can see it's HP varying between 60k (base) and 192k tops.
You can also use the video as reference, where you can see demolishers having 172k+ HP or more, so the player riding it does determine total HP. Remember this is endgame wrath considering players HP (PoV lock had 32k HP for example)
You can also notice how the turret he used had 87k HP

Be aware that endgame wrath had damage and health values way bigger at level cap than early stages. Blizz mage these changes on vehicles so they could hold the damage even though they don't have resilence.

**Comment by akrom23** [comment]
> 3-This is a bug that doesn't really demand proof. Players can cast spells with no facing restriction with no issues but those that require you to be facing your target can be really tricky to use even after moving facing with mouse (dragging right click).

Cannot reproduce.

> 4-http://wowwiki.wikia.com/wiki/Strand_of_the_Ancients
"Patch 3.0.8 (2009-01-20):
Antipersonnel Turrets will now gain vehicle immunities, use falloff damage, and damage increased to 4000 + 200 per level to compensate for falloff."
https://www.youtube.com/watch?v=klIjRpZYNxM (0:10-0:30) (Same video)
You can see how turret damage is greatly increased, doing up to 8k dmg on hit when hitting demo with center of the rocket. The 200 per level is from every level over 70, since that is the minimum lvl to queue SotA.

5-http://wowwiki.wikia.com/wiki/Battleground_Demolisher
This link is to the NPC from the Wrath of the Lich King Battleground Demolisher, as you can see it is level 70-80 located in SotA. You can see it's HP varying between 60k (base) and 192k tops.
You can also use the video as reference, where you can see demolishers having 172k+ HP or more, so the player riding it does determine total HP. Remember this is endgame wrath considering players HP (PoV lock had 32k HP for example)
You can also notice how the turret he used had 87k HP

Need more info about scaling. Right now, every 1 item level above 170 inceases hp/damage by 1%.
We need info about players' item level.
