### ISSUE TITLE
Redemption quest bug.

### ISSUE THREAD

**Issue by AreYouOnDrugs** [SunwellTracker/issues#1859]
Decription: I can't get redemption quest chain from NPC Brother William. 

How it works:  I can't get redemption quest chain from NPC Brother William. 

How it should work: I should get it from him. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,
the only quest that I can find he's starting is https://www.wowhead.com/quest=2998/tome-of-divinity
If you think he's supposed to start a quest called Redemption please provide more information (like a link to the quest description from wowhead or other websites for example), because there are many quests with Redemption in the title.

**Comment by Azathothh** [comment]
This chain is working properly. I'm 100% sure that you've already done that part of chain and thats why you can't see it.
Just write a ticket in-game and GMs will be able to tell you on which part of this chain you are (my guess is part with Stephanie Turner in Stormwind).
(btw. there's no npc in wow named Brother William, probably you've meant Brother Wilhelm)
