### ISSUE TITLE
Engraved Gauntlets. drop

### ISSUE THREAD

**Issue by komsomol5460** [SunwellTracker/issues#1883]
Decription: 
few sources the item;
drop with Blackrock Spire, Blasted Lands, Blackrock Depths not available
How it works: 
https://db.darkwizard.pl/?item=10232#dropped-by

How it should work: 
https://www.wowhead.com/item=10232/engraved-gauntlets#dropped-by:0+3-10-9+1
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed, live on Angrathar. Thank you for the report.

**Comment by komsomol5460** [comment]
hi, when to wait for changes in the game?

**Comment by Dootz** [comment]
should be in game now, but I'll re-check later today.

**Comment by komsomol5460** [comment]
https://db.darkwizard.pl/?item=10232#dropped-by
the database unchanged, how to learn about changes:3

**Comment by Dootz** [comment]
Hi, i'm sorry it took me so long. Due to TBC beta I forgot about it. Creatures listed here: https://www.wowhead.com/item=10232/engraved-gauntlets#dropped-by:0+3-10-9+1 will have a chance to drop Engraved Gauntlets from next server update/restart/crash. The database at db.darkwizard is based on static data, and won't change. We might need to update it sometime in the future, as there were many changes made throughout Angrathar's lifetime.
