### ISSUE TITLE
Loot-filled Pumpkin drops Valor

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#1885]
Decription: Loot-filled Pumpkin drops Valor

How it works: Loot-filled Pumpkin drops 2 x Emblem of Valor

How it should work: Loot-filled Pumpkin should drop 2 x Emblem of Conquest

Source (you should point out proofs of your report, please give us some source): no real proof, but it would make much more sense these days since everything drops Conquest; also http://wowwiki.wikia.com/wiki/Emblem_of_Valor

"Any dungeons that previously dropped [Emblems of Heroism] or Valor, such as Naxxramas or Heroic Halls of Stone, will now drop [Emblems of Conquest] instead. Emblems of Conquest can still be converted to Valor or Heroism."

**Comment by nimeral** [comment]
But it was only added in patch 3.3.3 because the dungeon finder was. Since we have the dungeon finder, IMO it should work in a consistent way. Like it was with
http://wowwiki.wikia.com/wiki/Keg-Shaped_Treasure_Chest
few weeks ago.

**Comment by Azathothh** [comment]
Well, we shouldn't add any emblems in http://wowwiki.wikia.com/wiki/Keg-Shaped_Treasure_Chest as well, but we can't turn back the time now.

When DF was introduced daily dungeon quests from Dalaran were removed and 2xEmblem of Frost were awarded from first random heroic made through DF.
Such events are counted as "daily Dungeon Finder" as well - so prize for it can be received only once.
Emblems were added to http://wowwiki.wikia.com/wiki/Keg-Shaped_Treasure_Chest because doing event through DF would mean not being able to get 2xEoF (cause daily DF prize was already claimed).
On Angrather there's no problem with that, cause we still have daily quests in Dalaran, so there's no need to add extra emblems in Loot-filled Pumpkin
