### ISSUE TITLE
[Quest] Zuluhed the Whacked

### ISSUE THREAD

**Issue by ZhengSim** [SunwellTracker/issues#2038]
Decription: Currently not able to complete. Required to unlock the Netherwing faction quests.

How it works: Accepting the quests does nothing.

How it should work: It should start an event in which you kill Zuluhed and loot his key to free Karynaku. https://www.youtube.com/watch?v=Iy45YwUZKfE

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/50086851-a7337880-01fe-11e9-95e3-c27143d4ddf0.png)
Works fine for me..

This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues

**Comment by tordhe** [comment]
Same problem as described above is still in game
