### ISSUE TITLE
Tiny Abomination in a Jar

### ISSUE THREAD

**Issue by Geigerkind** [SunwellTracker/issues#2160]
Description: 
This trinket proc should count as melee attack. Meaning it should also proc everything that is related to a melee attack. For a paladin for example T10 2-Set; Seal etc. other procs.

How it works: 
Currently its counted as spell cast and not as melee attack. Thus not procing all melee attack related buffs

How it should work: 
This trinket proc should count as melee attack. Meaning it should also proc everything that is related to a melee attack. For a paladin for example T10 2-Set; Seal etc. other procs.

Source (you should point out proofs of your report, please give us some source): 
Says it in the tooltip

**Comment by Geigerkind** [comment]
First two week push

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/51995460-07cafc00-24b3-11e9-9602-4ad029e7bcea.png)
17:15:43 seal proc from melee -> manifest anger -> seal proc from manifest anger

If something is wrong, and you wan't it to be fixed - maybe instead of "bumping" provide some informations/proofs/sources cause you didn't add any of these

**Comment by Geigerkind** [comment]
Indeed, seems to work now. Odd. Last time I tested it I could not get this result. Well good enough.
