### ISSUE TITLE
BG queues not blizzlike

### ISSUE THREAD

**Issue by Xentorq** [SunwellTracker/issues#2224]
Decription: As of patch 3.2.0, the queues of Battlegrounds got split in two, one for normal players and one for those who lock their exp.

How it works: those who stop their exp gain and those who did not ends up fighting together.

How it should work: they should have their own queue.

Source (you should point out proofs of your report, please give us some source): 
Quote: "Players with experience gains turned off who compete in Battlegrounds will face off only against other players with experience gains turned off" https://wow.gamepedia.com/Patch_3.2.0

When will this fixed? I know many people interested in this fix.

**Comment by dispelx** [comment]
Are you really a fool? compare server blizzard with cross realms and a huge online with a pirated server 3k online.
With this fix, the administration will kill the server, as well as all twinks bracket.
BG for 15/40 people will simply stop starting due to the lack of players.
And on this all the administration should go to please one whiner like you?
You wrote on the forum that you want to leave the server because of this, well, so leave, no one here keeps you.

**Comment by Akha72** [comment]
It will not kill twink brackets. Brackets where there are no twinks are already dead (like 40-49) while the most populated ones (70-79, 10-19, 60-69) have enough twinks to get bgs popping without leveling players. If you get queues separated you will only make it more difficult for low lvl players to get into bgs.
And let's be honest, the only time you get more exp from bgs than rdf grind is during CtA weekends so during that time it could be implemented, still good luck getting leveling players to join different bgs than WsG or AB.
This issue has been raised a number of times  with no good arguments for making such a change.

**Comment by Xentorq** [comment]
Dispelx, your reply perfectly represent the twinks population. You guys are toxic and like to play abusively, killing levelers and having fun to the detriment of others. I will stop here and not reply to you anymore.

Akha72, actually when it's late 70-79 BGs start with the only support of levelers, so twinks are not needed to start them.

I recognize you guys are probably twinks but you have to understand you are not the only ones entitled to have fun. Respect the others players opinions. Twinks do not want separated queues, of course. How could you have your abusive fun if they were? I suggest you to go back to your previous server, as I know your tiny community moves from a server to the next one, like gypsies, everytime a server stops supporting it.

**Comment by Xentorq** [comment]
I even found your character. Delfineq, level 79. A twink of course. Your opinions are biased.

**Comment by Akha72** [comment]
I was almost tempted to treat you seriously but then you couldn't resist insulting people you disagree with. Good job (besides 70-79 bracket, which is the most populated one because of obvious reason there are six more, why ignore them?)
And by all means separate queues, you'll make twinking community a much great favour than you'll make levelling players.

**Comment by Xentorq** [comment]
Cool, but I happen to be the only one who has been insulted (by dispelx). 
Anyway I came here to report this bug and the source is provided in the main message: there is actually nothing to discuss. I gave my contribution as a player and I trust the developers efficiency to fix the bug. Have a nice day.

**Comment by Akha72** [comment]
Yeah, because calling other people abusers and gypsies is a compliment. And since it is not a bug but a consciouss decision from our dev team I doubt they will change it just because you asked them to and provieded zero arguments for such a change. Oh and btw, it's a duplicate.

**Comment by Xentorq** [comment]
First of all the Gypsies are a noble ethnicity and not an insult, they have a great respect in my country but it's known they are often nomadic. And no argument is needed because it's a bug...
Btw, how do you know this is a voluntary decision from the server?

**Comment by Akha72** [comment]
FYI in many countries it's considered an insult and Roma is the proper name, but hey - nice try. An argument is needed since your idea will leave non-twink bgs empty except CtA weekends, yet for some reason you seem ignore that, maybe because it does not fit your thesis.
This idea of separating queues was presented a number of time to the dev team, ever since the launch of Feronis (the previous realm) and they decided not to do it, so there may be a reason for that.

**Comment by Xentorq** [comment]
Source?

**Comment by Akha72** [comment]
Feel free to check Angrathar bugtracker since your didn't even bother to do so before writing this report, you can also check forum, Feronis forum and old bt (mantis).
