### ISSUE TITLE
XP lock and twinks in bg?????

### ISSUE THREAD

**Issue by Maci3jj** [SunwellTracker/issues#2239]
Decription: Hello I see that it was reported before but it looks like there was no answer from the owners so I'm asking myself...........

How it works: people blocking xp slaughters people who are not blocking xp in battlegrounds = twinks vs not twinks

How it should work: it shouldn't happen!!!!!!!!!!!!!!!!!!!!!

Source (you should point out proofs of your report, please give us some source): it's official in the 3.2 patch notes!!!:

Players with experience gains turned off who compete in Battlegrounds will face off only against other players with experience gains turned off.

SOURCE: BLIZZARD!!! http://us.battle.net/wow/en/game/patch-notes/3-2-0

why are you making normals play with twinks? answer pls
I'm in alliance and we lose everytime
it's very bad and shame to the server
so....
FIX THIS

**Comment by KuroiMatoO** [comment]
Can't tell for sure since I'm playing on this server for just 2 weeks, but maybe they did it because there are not enough people to begin with. I tried to enter bg almost every day and succeed only 1 time. But yeah, that's bullshit.

**Comment by Maci3jj** [comment]
Man twinks are a minority!! how many bg do you think they help to start?..... 0
But dozens of ppl stop playing because of them. This server is not serious, no developer has ever tried to play their own game with their customs rule, im sure of it, otherwise they would fix this $h1t

**Comment by Akha72** [comment]
'Hello I see that it was reported before but it looks like there was no answer from the owners so I'm asking myself' -> go check Bugtracker rules and stop spamming.

'Man twinks are a minority!! how many bg do you think they help to start?..... 0
But dozens of ppl stop playing because of them. This server is not serious[...]' - In brackets where there are no twinks there are almost no bgs so unless you can support your false claims with evidence simply refrain from such pointless rants.

**Comment by Warglaive** [comment]
Just enter any 70-79 Battleground and see for yourself, there are like 9 Horde twinkers VS 2-3 alliance twinkers, so there is really no chance for victory. I'm not complaining tho, its PvP server, but its not balanced at all, sadly. And in the end there will be less and less BGs at level 70-79, because of that issue.

**Comment by Nadiirr** [comment]
A more appropriate place for this conversation would be the forums as we have discussion there and devs are only fixing bugs. 

While your source checks out, I'm not sure that we will implement a separate queue for those who have disabled experience.

**Comment by Riztazz** [comment]
This feature will not be implemented anytime soon. Blizzard had big battlegroups to select players from, we don't;p
