### ISSUE TITLE
Cold snap SHALL RESET GCD

### ISSUE THREAD

**Issue by hyxgod** [SunwellTracker/issues#2243]
Decription: 
Are you seriously declining this?? Here is proof since you dont believe in it. Cold snap shall reset GCD. so u can instanly use a spell when pressing COLDSNAP.

How it works: 
HAVING GCD

How it should work: 
^^^^^^^^^^^^^^

Source (you should point out proofs of your report, please give us some source): Here's the proof since you dont take your time & only declining my report. 2007 VIDEO 06:14 of the vid https://www.youtube.com/watch?v=zJOf0RM5pSM Using cone of cold INSTANT after coldsnap. this also 10.38 --- https://www.youtube.com/watch?v=462JFev7AE4 If your gonna decline this also, prove me wrong

**Comment by Azathothh** [comment]
"Here's the proof since you dont take your time & only declining my report." it's first time when you're reporting it on our Angrathar wotlk bugtracker... if you want to report a bug on Nightbane tbc server please do it on tbc bugtracker here: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues

First video: he's using Ice Block after Cold Snap not Cone of Cold like you're saying, also he doesn't have a GCD at the moment when he's using Cold Snap, so how is it supposed to reset GCD if there's no GCD?

Second video: at 10:37 you can see that after Cold Snap is used - CD from Frost Nova is removed BUT there's applied part of GCD which still wasn't over after Fire Blast spell.
On screenshot you can see that moment, when Cold Snap was used but there was still GCD on frost spells:
![obraz](https://user-images.githubusercontent.com/37483678/54197313-e272da00-44c3-11e9-8483-55e762500b09.png)
