### ISSUE TITLE
[Wintergrasp] Not teleporting to start zone.

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#2269]
Decription: 
Hello there! This is a big problem because you are not teleported to the start zone.
For example:
If i am on south tower and the battle starts (i will accept it) and i don't get teleported, i am still on South Tower. This is a big problem for defenders because attackers can destroy cannons inside when Wintergrasp starts, they should get teleported to the start zone.
If Horde control Wintergrasp and i am (Alliance) near Fortress and i press accept to join the battle, i don't get teleported, which you can kill everything inside, it should teleport you.. Or when you are on mount, you don't get dismounted, which is bugged as fuck..
Viceversa. Horde/Alliance

How it works: 
If i am on south tower and the battle starts (i will accept it) and i don't get teleported, i am still on South Tower. This is a big problem for defenders because attackers can destroy cannons inside when Wintergrasp starts, they should get teleported to the start zone.

How it should work: 
If Alliance control (Wintergrasp Fortress):
You should get teleported at Fortress!
As Horde you need to get teleported to Horde/Alliance camp.
And Viceversa Horde/Alliance:

Source (you should point out proofs of your report, please give us some source): 
I don't have any source, but i can make a new video about that, what happens (here, on this server "Angrathar").

**Comment by Azathothh** [comment]
Could you post any proofs that it should work like you wrote? It was working before like you've described, but it was changed because of this report: https://github.com/SunwellTracker/issues/issues/718
If you'll look into these videos from retail Wotlk, you'll be able to see that there was no teleport to starting zone for people already waiting in WG for battle start:
https://www.youtube.com/watch?v=e4s5HVt26pI
https://www.youtube.com/watch?v=Wm03136FTI4

**Comment by alexandru58** [comment]
On Feronis server you are teleported to start zone.. It works fine on Feronis!! I will give you the proof when i will be home. :)

**Comment by Piootrek** [comment]
Closed due lack of proofs.
