### ISSUE TITLE
Sindragosa's Blistering Cold killing people in beacon

### ISSUE THREAD

**Issue by snaplemouton** [SunwellTracker/issues#2280]
Description: As the title says, Blistering Cold is killing people in the beacon in last phase.
This seems to only be happening to hunters for some reason.

How it works: Blistering Cold is hitting certain characters inside their beacon in last phase.

How it should work: Beacon should render the player immune to all damage except suffocation while inside the Beacon.

Source (you should point out proofs of your report, please give us some source): I can probably find video stream evidence of the problem happening if required.

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/55953991-ccd90780-5c5d-11e9-9658-2b7f4aa28946.png)
Hunter in ice tomb in last phase - getting only Asphyxation dmg.
Tried with other classes as well. Characters in ice tomb were always getting damage only from Asphyxation.
Can't reproduce it with informations that you've provided. Please add some video (would be amazing if you've got video with open combat log) or logs from fight when you think that it bugged out.

**Comment by snaplemouton** [comment]
I don't have any combat log, but here's 2 different stream where I get killed by blistering cold:
https://www.twitch.tv/videos/407284591?t=02h12m00s
https://www.twitch.tv/videos/404810950?t=00h27m16s
Maybe it's because of the character model and female Draenei gets killed by hit cause of hit box or something?

**Comment by Azathothh** [comment]
On 2nd video it looks like both tombs are in range of Blistering Cold but only you've been killed...
Tried to reproduce it with draenei male hunter / draenei female hunter,  getting hit (or rather not getting hit) by Blistering Cold with Asphyxation/ without Asphyxation, by jumping/moving/using feign death/etc. before being hit with Icetomb - nothing worked - i've never been hit with blistering cold.
It could be caused by some buff or aura - but i won't be able to find it without logs from that raid :<

Is it happening to you every time or only on this one raid? Anyone else encountered such problem recently?

**Comment by snaplemouton** [comment]
Every time, 10 man or 25 man, normal or heroic (Havn't done 25 heroic so I don't know for that one). It has happened about 8 or 9 times so far, the number of times that I've been picked for iceblock right before a blistering cold. I've seen it happen to a few other players as well, though I can't remember the specific class/race/etc.
If you want, we can test directly with my character?
