### ISSUE TITLE
Transmog bug: Vile Fumigator's Mask

### ISSUE THREAD

**Issue by afflictive** [SunwellTracker/issues#2283]
**Decription:** 
My head transmog does not work correct.

**How it works:** 
My "Vile Fumigator's Mask" transmog its not full.
Look like left side of this picture:
https://i.imgur.com/UBG1tCa.png

**How it should work:** 
Should look like right side of this picture:
https://i.imgur.com/UBG1tCa.png

**Source (you should point out proofs of your report, please give us some source):** 

My movie:
https://youtu.be/aq5yds9z1

https://www.wowhead.com/item=50741/vile-fumigators-mask#screenshots:id=738383
https://wowwiki.fandom.com/wiki/Vile_Fumigator%27s_Mask
https://www.wowdb.com/items/50741-vile-fumigators-mask

**Comment by afflictive** [comment]
Correct linkt to move: https://www.youtube.com/watch?v=aq5yds9z1-s

**Comment by Azathothh** [comment]
Well, it's not really a bug - transmog does only change model of an item and this "backpack" ISN'T part of Vile Fumigator's Mask model. It's a spell id: 71947 [Gas Mask Visual (Purple)] applied on you while wearing Vile Fumigator's Mask (that's why you can't see it in 3d view on wowhead (https://www.wowhead.com/item=50741/vile-fumigators-mask#modelviewer))
https://www.wowhead.com/spell=71947/gas-mask-visual-purple
