### ISSUE TITLE
Daily Quest:Assault by Grounds

### ISSUE THREAD

**Issue by rancz** [SunwellTracker/issues#229]
Decription: Daily quest in icecrown for horde, you escort a group of kor'kron Infantry to the top,

How it works: 
You start the quest and only the leader goes up, the rest doesn't follow, and you need them to reach the top to complete the quest.

How it should work: 
Kor'kron infantry should be following the squad leader but instead they just stay at the bottom, and they need to reach the top in order to complete the quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Oradd** [comment]
The problem is that there should be a squad leader and 5 Alliance/horde infantry. It only spawns a squad leader and 2 infantry atm since the other 3 are stuck as [https://puu.sh/zlq9Z/d691f8da16.jpg](url) shows. 

It should work as following video is showing [https://www.youtube.com/watch?v=LSAZEVjeu70](url). 

The quest isnt completeable unless you wait for another to pick up the quest and you do it once more. You cant start it again unless u abandon which will simply repeat the incompleted quest you just did.

**Comment by hugedude** [comment]
Still broken.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by MrTide** [comment]
Update: Still broken
