### ISSUE TITLE
Auctioneer GetAll scan

### ISSUE THREAD

**Issue by NinjaWitaSniper** [SunwellTracker/issues#239]
Decription: 
The Auctioneer Addon GetAll scan should scan the entire auction house in less than a minute at most. But on your server its only starting a normal scan, which can take upwards of 15-20 minutes.

How it works: You click the GetAll scan button, but it starts a normal scan.

How it should work: You click the GetAll scan button, and it scans the AH in seconds.

Source (you should point out proofs of your report, please give us some source): 
GetAll on my old server: https://youtu.be/tJPYcx6vBhg

GetAll on Sunwell: https://youtu.be/1_4gPsVGZxI

**Comment by nimeral** [comment]
And Auctionator scan doesn't seem to work at all, only scans like 5 items.

**Comment by feralxgodx** [comment]
I think that scan speed is entirely dependent on how fast sunwell provides the addon with data. its not bugged addon.

**Comment by NinjaWitaSniperisdumb** [comment]
This is intentional because scanning the auction house can cause severe load on the server. This is done on other servers such as warmane but since you are too ignorant to listen to me and keep spamming discord I had to do this. Here is a screenshot of the code which would do this https://i.imgur.com/WgSLuqA.png.

Now please for the love of god stop spamming this shit on discord

**Comment by Valmere** [comment]
Fast (GETALL) scans aside, half the available auction house addons will not FULL SCAN at all. Even the ones available for download on sunwell's own addon page refuse to scan with the exception being that bloated auctioneer suite.
