### ISSUE TITLE
[Warrior] Improved Thunder Clap Talent (Angrathar)

### ISSUE THREAD

**Issue by Buttpommel** [SunwellTracker/issues#24]
Decription: 
The talent is not correctly modifying or displaying the ability as it should.

How it works: 
The talent reduces the rage cost, as well as the damage and attack time modifiers for the Thunder Clap talent. Although, only the rage cost is reduced while both the damage and attack time modifiers remain the same. This is a huge detriment to Prot Warriors specifically affecting their early tanking.

How it should work: 
The talent SHOULD reduces the rage cost, as well as the damage and attack time modifiers for the Thunder Clap talent.

Source (you should point out proofs of your report, please give us some source): Grab the talent and see for yourself.

**Comment by Cwiercpasiec** [comment]
Damage of Thunder Clap is increased by the talent.

Screenshot without talents: https://imgur.com/a/GgWBI
Screenshot with talents: https://imgur.com/a/ei9LZ
207 * 1,3 (30% increased damage) = 269,1 which is rounded to 269.

The only thing which might be bugged (but i guess it's not) is debuff increasing time between attacks. When you mouseover the skill on your action bar it says the debuff is 20%, but on enemy it says 10%. My guess is that it's only because tooltips of buffs/debuffs are not counting upgrades from talents etc., but they actually work as they should.

**Comment by Buttpommel** [comment]
Awesome, thank you so much man!
