### ISSUE TITLE
Replenishment from ret pal is not working

### ISSUE THREAD

**Issue by Eaglesring** [SunwellTracker/issues#2417]
How it works: 

We are getting from ret pal 0-0,2% mana regen

How it should work: 

U should be getting 1% from your 100% mana

Source (you should point out proofs of your report, please give us some source): 

https://www.youtube.com/watch?v=F5vJPCPoMaI
As u can see im getting 66 mana which is like 0,2% (1%=334 mana)

SS from some bosses:

fest 25hc- https://ctrlv.cz/bVtj
DB 25hc- https://ctrlv.cz/pQLn
PP 25hc- https://ctrlv.cz/ocYe
(Zeferot, Midzi are ret paladins)

PS:
It was working fine until today raid. People were having mana problems and when i checked recount there was just something wrong with ret paladin for sure

**Comment by Eaglesring** [comment]
Well EDIT: it should be 1% of mana per 5 sec so it was working fine on that video ... But it wasnt working in ICC. As u can see on skada we wasnt getting almost anything from ret paladins and even mages are having mana issue now ... Mby its not jumping to 10 ppl or its jumping to mdps

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/65325975-9f9b6880-dbb0-11e9-9107-4c1287782dea.png)
![obraz](https://user-images.githubusercontent.com/37483678/65325989-a7f3a380-dbb0-11e9-9e03-b1b2ee522c62.png)
Replenishment gives 1% mana PER 5 SEC so "As u can see im getting 66 mana which is like 0,2% (1%=334 mana)" 66mana x 5 = 330 so ~1% (not exactly same because of rounding)
Everything is fine with replenishment from paladins. 
You can't get replenishment from both priest and paladin at same time, looks like there may be something wrong with priest replenishment, not paladin

**Comment by Eaglesring** [comment]
As i said ye seems like its working but something is just wrong ... even mages are ooming now and not only in our guild

**Comment by Eaglesring** [comment]
I tested it with priest and it was same

**Comment by Eaglesring** [comment]
Look at this video (look from 2:33) https://www.youtube.com/watch?v=jxi-a-YTbFs replenishment is just stuck at 14 sec (for example 2:33-2:37, 2:46-2:52 )  (i think im still getting new one) or it just randomly disappearing like 2:39 , 2:52 , 3:22 what is this ?? 
I think u shouldnt be getting new replanishment before the old one expire becuase ret pal and spriest should be enough for 20 ppl but if its working like this its pretty random and still dont know why its dissapiering. There is a lot more just watch this buff whole time .. its just not normal

**Comment by Eaglesring** [comment]
Im gonna make new topic and make it better
