### ISSUE TITLE
[Core - Mechanic] Fake "Empty Slot" on some corpses using Group Loot and above, cannot Salvage corpse with Profession as result

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2458]
Decription: 
An issue which causes a fake "Empty Slot" to appear on corpses at random if using Group Loot or above, which also prevents Salvage.

How it works: 
https://imgur.com/a/RRXXTtX
The corpse was empty after the dropped Item was rolled for and distributed to the winner, but a fake "Empty Slot" was still there despite there being nothing. Loot System was set to Need Before Greed (auto-set and unchanged since entering the Dungeon via RDF). This prevented me to use Skinning to Salvage the corpse.

How it should work: 
Corpses shouldn't bug out like this while in a Group using Group Loot or above Loot System.

Steps to reproduce:
1. Be in a Group;
2. Set Loot System to Group Loot/Need Before Greed etc.;
3. Kill anything;
4. Have it looted until this bug happens.
Extra: Test with corpses that can be Salvaged -- when this bug occurs, the additional result should be that you are unable to Salvage the corpse due to this fake "Empty Slot".

**Comment by Azathothh** [comment]
Even if you see it empty, it doesn't mean that it's empty.
With any loot rules different than Free for All (in your case it was Need Before Greed), common and junk quality items are distributed in Round-Robin system 
![obraz](https://user-images.githubusercontent.com/37483678/66349880-28105c00-e95a-11e9-9c2e-3dcec09f72de.png)  ![obraz](https://user-images.githubusercontent.com/37483678/66349914-3d858600-e95a-11e9-9305-fd1f653c62b0.png)
In King Dred tooltip you can see "Loot: Reluvethel" which means that there was common or junk item in this corpse, but it was Reluvethel turn to loot it. 
If such player won't open the corpse - his loot stays there and it's not visible for other players, also you can't use skinning because it's not empty.
If such player opens the corpse and loot it - corpse is empty and you can use skinning.
If such player opens the corpse but doesn't loot it - once loot window is closed, common or junk items left inside become visible for everyone in party and possible to be looted by everyone. Then, after it's empty, it's possible to use skinning.

https://wowwiki.fandom.com/wiki/Loot#Looting_While_In_A_Party
"Abandoned loot on a corpse prevents it from being skinned, and it is considered polite for a party to loot all corpses if a skinner is in the party. "
