### ISSUE TITLE
Spell queue system

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#2508]
Decription: The retail spell queue system does NOT exist on sunwell

How it works: 
Does NOT exist

How it should work: 
There should be a spell queue system(client side,instead of server side),which was introduced in patch 2.3,and it was removed during cataclysm.

Source (you should point out proofs of your report, please give us some source): 
https://wowhats.wordpress.com/2010/03/07/lag-and-world-of-warcraft/  ,  https://wowhats.wordpress.com/2010/03/07/lag-wow-and-you/

**Comment by keepokappalul** [comment]
https://www.twitch.tv/scribblejam/clip/AmusedLachrymoseAxeNomNom?filter=clips&range=all&sort=time - quick example.As u can see the mage(scribble) can queue his next arcane blast at the end of the cast.(rising gods video).

**Comment by Wojtyas** [comment]
Hi there,
This is blocked by us in purpose.

That was the system implemented by Blizzard during WotLK because they had performence issues those days. We won't change that because we don't encounter this nowadays.

Blizzard was asked about this before vanilla launch recently. It is well described what was the issue and why they did it. https://www.wowhead.com/news=290910/spell-batching-in-classic-wow

Conclusion:
It was side effect of performance cuts by Blizzard and we're not going to implement that.

**Comment by Triaku** [comment]
He wasn't describing spell batching, but spell queueing which is a whole different thing lol. It's important to be able to link together casts and without it causes higher ping to be srsly worse. Never mind that Spell batching is important and can be tuned down to 100ms to get the same effect without laggy gameplay.

**Comment by Soufly** [comment]
@Wojtyas Triaku is right,spell queue system was added in patch 2.3,and removed in cataclysm.Its a different thing.Warmane has this system for example.

**Comment by Soufly** [comment]
''In patch 2.3, a system was added whereby the client would no longer ever prevent the player from sending new casting instructions to the server (except for during a “hard” 1000ms lock after each cast is begun).  Instead, you can send the instructions at any time and, if there is not much time left on the spell cast, the server will “queue” the next instruction instead of rejecting it.  This duplicates the behaviour of the stopcasting macros without requiring the same sort of split-second precision timing and without any of the risk.''

**Comment by Soufly** [comment]
This does not exists here @Wojtyas .

**Comment by Soufly** [comment]
This does not exist here,and its affecting the whole game @Wojtyas .
