### ISSUE TITLE
[Warrior, Spell] Heroic Strike and bonus Dmg to Dazed targets

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2509]
Decription: 
Heroic Strike dont do bonus Dmg to Dazed targets.

How it works: 
Heroic Strike dont do bonus Dmg to Dazed targets.

How it should work: 
Heroic Strike Should do bonus Dmg to Dazed targets.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/forums&topic=156304

**Comment by Aridam** [comment]
What have you tested with? Shield Bash?

If you've tested with Piercing Howl, then that's wrong - - for some reason Blizz didn't make it give the bonus to Heroic Strike/Steady Shot. It was classified as a Snare even though everything about it made it seem it was a Daze. Although your link does have a mention that Howl doesn't work anyway.

**Comment by BialyADI** [comment]
With Shield Bash there is no bonus Dmg from Heroic Strike.

**Comment by Aridam** [comment]
Bought [this](https://db.darkwizard.pl/?item=2131) to have the shortest Min-Max Weapon Damage range and tested.

First I HS-ed a few times without Shield Bash to observe the Damage, then I Bashed and HS-ed again while the Daze was active -- Damage wasn't higher, despite SB's effect being a legitimate Daze that should've given the bonus.

Bug confirmed.

Affected Ranks of Heroic Strike which benefit from Daze effects on the Targets (Ranks 10-13):
https://db.darkwizard.pl/?spell=29707
https://db.darkwizard.pl/?spell=30324
https://db.darkwizard.pl/?spell=47449
https://db.darkwizard.pl/?spell=47450

As far as I know, only Piercing Howl shouldn't give the bonus Damage, as per the provided link in the original post mentioning it -- everything else should give the bonus Damage.

Might also want to check if Steady Shot is bugged the same way, since its bonus Damage follows the exact same principle.

**Comment by Aridam** [comment]
Bump.

**Comment by Aridam** [comment]
Video evidence:
https://gfycat.com/wellgroomednarrowkestrel
https://gfycat.com/happygoluckyunsungeft
