### ISSUE TITLE
Inner cd in instances.

### ISSUE THREAD

**Issue by shandrise** [SunwellTracker/issues#2510]
Decription: 
It doesnt work

How it works: 
Ppl can kick everyone at 1st minute abusing it to skip current instance. When ppl leave after 15 mins when inner cd ended - they receive https://www.wowhead.com/spell=71041/dungeon-deserter

How it should work: 
It should start when player join to instance. Duration is 15 mins. During this 15 mins player cant reg another instance and skip current. When it ended player can leave and dont receive Dungeon deserter or reg another instance.

Source (you should point out proofs of your report, please give us some source):  https://www.wowhead.com/spell=71041/dungeon-deserter

**Comment by Aridam** [comment]
You mean [Dungeon Cooldown](https://ptr.wowhead.com/spell=71328/Dungeon-Cooldown) - - this gets applied to people who used the Random option of the RDF tool, while those who used Specific shouldn't get this. It's placed once the Group is formed and the Dungeon is chosen (_not_ when you hit the queue button). Supposedly, it should be removed once the final Boss has been killed (like in a short Instance), as well as it shouldn't apply if you're just a replacement for someone in an already-formed Group. 
https://ptr.wowhead.com/spell=71328/dungeon-cooldown#comments:id=916130

**Comment by Nadiirr** [comment]
This is great information. Thank you very much guys. <3

**Comment by Riztazz** [comment]
We had that disabled due to people being.. not very nice. I'm brining it back, realm restarts in 10 minutes or so hence it will be live shortly, closing

**Comment by Aridam** [comment]
Shouldn't be a bother if people actually attempted to clear Dungeons, since as said [here](https://www.wowhead.com/spell=71328/dungeon-cooldown#comments:id=916130), it's supposed to be removed when you defeat the final Boss of the Random Dungeon in question, or are merely a replacement of an already-established Group in the case of somebody having left. Not to mention [here](https://www.wowhead.com/spell=71328/dungeon-cooldown#comments:id=893364) it says that it shouldn't stop you from using the Specific portion of the RDF tool.

Besides, if people really don't like each-other that much, they can use the Ignore feature and not be paired up through the RDF tool.
