### ISSUE TITLE
Army of the Dead scuffed

### ISSUE THREAD

**Issue by ranku505** [SunwellTracker/issues#2584]
Decription: 
The Army of the dead is useless as it is, because its just taunting nonstop.

How it works: 
They get in combat when someone in the group gets in combat, but they should only get in combat when i get in combat.
And they are taunting nonstop, when they should just be generate alot of threat.

How it should work: 
If you wait 2/3 seconds for the tank to start tanking, you can start attacking with the army without stealing the agro from tank.
Because right now, if i use army of the dead on Heroics they take agro and bosses cleave and we all die.
In Naxx will be even worst, meaning the skill wont be used at all.
They do generate alot of threat. but they shouldn't be taunting it off the boss.
On angrathar was working properly like in retail, but here they are scuffed.
I remember poping army, tank would start tanking, and i would get in combat like 3 seconds after, thats when the army would attack, and they were NEVER stealing agro from main Tank.
Please review this before Naxx release :(

Source (you should point out proofs of your report, please give us some source): 
You had in on Angrathar working properly.
And im sure there will be videos of DK's fighting bosses with army at the beggining and they wouldn't taunt, and make boss cleave and wipe the entire raid.

**Comment by Aridam** [comment]
https://www.wowhead.com/spell=42650/army-of-the-dead#comments:id=989522
> -It is nearly impossible to take aggro from the ghouls. Even through taunting (wich will fail most of the time), if you actually manage to get aggro, one of the ghouls will take it back in less than a second. This is not true against raid bosses. The Ghouls won't taunt mobs that are flagged as "Boss" in-game (level ?).

So basically anything not tagged as "Boss" (which would be Level ?? Raid Bosses) can get swarmed and overtaken by them - - even Dungeon Bosses. Otherwise, against Raid Bosses (Adds do not count), only cause a high amount of Threat (use Omen and see), but the Tank should still be able to keep Aggro given enough time to generate enough Threat (as said above), and if in danger, a Taunt every now and then should resecure their Aggro again, without fail.

As got control, I believe you're unable to control them, save for having the Talent which makes your Ghoul from Raise Dead permanent - - commanding it seems to work on the Army ones too, as they seem to "follow" the permanent one.
https://www.wowhead.com/spell=42650/army-of-the-dead#comments:id=714121

**Comment by ranku505** [comment]
Lets hope they look into this to fix it and make it work like it did in Angrathar (before Naxxramas comes out)

**Comment by Aridam** [comment]
AotD Spell ID: https://wotlk.evowow.com/?spell=42650

**Comment by ranku505** [comment]
Bump.
Any news or updated from devs ?

**Comment by ranku505** [comment]
bump
raids tomorow still army is useless

**Comment by ranku505** [comment]
lol no comments.

**Comment by Riztazz** [comment]
Gonna take a look at those this week
