### ISSUE TITLE
Intimidating Shout breaking on absorb hit.

### ISSUE THREAD

**Issue by xmachinex87** [SunwellTracker/issues#2594]
Decription: 
Intimidating Shout breaks on absorb hit, if paladin has sacred shield or if priest has absorb bubble.

How it works: 
IS breaks on absorb hit instantly.

How it should work: 
It should stay on target as long as absorb is up and he takes no direct damage

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/391b4cf5b5b0b35d12d01db18454e234

**Comment by Aridam** [comment]
Absorbed Damage shouldn't count as valid Damage taken by the Target affected by the _targetted_ IS (ergo the stationary one that breaks even on 1DMG unlike the others "fleeing in fear") - - it's supposed to break on Damage done _to_ them, _not_ the Absorb Shield.

Confirmed. Big issue because it removes a sometimes-crucial buffer against the targeted IS on Shielded Targets.

Good catch.

**Comment by xmachinex87** [comment]
Thanks

**Comment by Aridam** [comment]
Issue confirmed.

Attacked [these](https://db.darkwizard.pl/?npc=6000) until they used [this](https://db.darkwizard.pl/?spell=11974) (Absorb Shield), used Intimidating Shout _on them as a Target_ (meaning it'll break on _any_ Damage, unlike the non-Target victims), did low-enough Damage to not break the Shield, but my IS still broke despite the Target not actually taking _direct_ Damage.
https://gfycat.com/anxiousweebaiji
