### ISSUE TITLE
[Warlock][Fear]

### ISSUE THREAD

**Issue by herewegoaganebugs** [SunwellTracker/issues#2600]
Decription: When you cast fear on an enemy target (tested in duels in dalaran sewers, and duels in the world) you cant cast another fear immidietly u have to wait like 5 seconds or more before you are able to cast another fear, u get the message "a more powerful spell is active".

How it works: 
https://gyazo.com/75bd7f9af8493930eb016006b42c6cc3

How it should work: 
You should be able to spam fear as much as you like after casting it once, and nothing should happen to the target but nevertheless u are still castng fears, and once target drops below the second dr mark second dr gets applied. here is proof of warlock spamming fear incase rogue trinkets 
https://youtu.be/QHfkeFnqabg?t=135
Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/1519 Azathothh's comments and provided footage. Affects Fear as well.

**Comment by herewegoaganebugs** [comment]
so how does it actually work, u shouldnt be able to cast a second fear/poly at all (like it is now) or the cast should go off but do nothing to the target untill the dr of spell is 5>

**Comment by Aridam** [comment]
If the Fear is 10s the next one you try to apply in its first 5s will go through with the cast but end as failed with the error "A more powerful spell is already active", because the second, 1/2 DR Fear starts from 5s. If however you finish the cast when it goes down to say, 4, then it should be successful and apply the second one since it's longer, at 5s.

Same goes for Poly and Entangling Roots/Nature's Grasp. Not sure about other CCs. Would need more data.

**Comment by Azathothh** [comment]
@Aridam You're right, but the problem currently is that you can't even start another cast until less than 50% of first fear is left. That's the part which is bugged.

**Comment by Aridam** [comment]
Oh I see. Well then, that's confirmed at least.
