### ISSUE TITLE
Frosthold - Vanilla mining nodes (mainly thorium

### ISSUE THREAD

**Issue by Zackthecellist89** [SunwellTracker/issues#2603]
Decription:
The spawn density and ratio of mining deposits are not working correctly. The main issue is with thorium.

How it works:
There are 10x more truesilver veins than thorium and mithril together. For example, in all silithus there's barely a thorium vein. The spawn locations are filled with truesilver and gold veins (uncommon quality). It's a major hassle to farm thorium, thus a stack goes for 100g in the AH. Also, gold veins spawn even in Silithus (they shouldnt).

How it should work:
There should be significantly more thorium veins, and way less truesilver and gold veins.

Source (you should point out proofs of your report, please give us some source):
http://db.darkwizard.pl/?object=175404
http://db.darkwizard.pl/?object=324

**Comment by Zackthecellist89** [comment]
If the respawn times listed on your own database are accurate, then Burning Steppes' node respawns are way off.

**Comment by Aridam** [comment]
There are Zones/areas of Zones with multiple "shared" spawnpoints for up to several different Mining Veins. Each of them is supposed to have a chance to respawn there, but not on top of each other clipped into one another (many servers have this issue). Buncha other things and generally complex stuff I don't currently remember more details of right now. 

If you think the respawn rates are wrong, or there are missing spawns if Veins shared with others in given spawnpoints, or just anything that's not pure bad luck on respawns regarding what I said above details, show examples of that and also of what it should be like.

'Cause it sucks hardcore for Mining if there's indeed an issue revolving around any of this.

**Comment by Zackthecellist89** [comment]
Even the archived information on wowhead doesn't actually list node respawns, hence my citing of sunwell's database of what their node respawn times "should" be. I think it's possible that certain node types can respawn incorrectly, such as small thorium veins respawning as truesilver - truesilver should only ever respawn from mithril veins, and it should happen at a fairly low chance.
This isn't just an issue of people failing to mine truesilver veins until the zone is filled with them, I've witnessed in Silithus mining 2-3 truesilver veins near cenarion hold, then watching them respawn in nearby small thorium spots within 30 seconds. This has occurred multiple times and is probably not a coincidence.

**Comment by Aridam** [comment]
[This](https://www.wowhead.com/forums&topic=66791#p776957) says Truesilver could respawn from Mithril and Thorium -- _less often_ from Thorium than from Mithril in comparison -- but it's indeed supposed to be a _rare_ spawn. Seems to have been present and unchanged all the way from [Vanilla itself](https://classic.wowhead.com/object=2047/truesilver-deposit#comments:id=542). Bonus [post-Wrath mention](https://us.battle.net/forums/en/wow/topic/4081808757) in case someone assumes it might've been patched out mid-WotLK.

Worth to mention is that apart from shared spawns for Veins, there are also _supposed to be_ caps for all Veins in a given Zone or area of a Zone -- skipping by one you don't want might mean one less of the ones you _do_ want, due to it causing a set cap to be reached, preventing any other Veins from actually being spawned unless any already-spawned one gets salvaged. I'm not sure if this is actually present and working here, but if it is, that might also be an extra reason for this, by selectively skipping unwanted Veins.

**Comment by Zackthecellist89** [comment]
Per Burning Steppes timers, the respawns seem way off compared to the 15 minute respawns listed on sunwell's database, though given the 45m-1hr timers in all other zones it's likely that the Burning Steppes data there is what's incorrect. 

This still doesn't address the issue of truesilver veins respawning shortly after being mined, and presumably continuing to take up some of the zone's node cap. This is a phenomenon I've observed several times on Frosthold, mainly in Silithus and Winterspring.
