### ISSUE TITLE
Basic Chemistry

### ISSUE THREAD

**Issue by ashlacon** [SunwellTracker/issues#2608]
Decription: The Basic Chemistry quest is a recommended 5 person group quest, and requires at least 2 people to complete (due to the cooldown of the vial). It only gives 1 person in the party completion credit when the cauldron is neutralized. Additionally a player receives credit for the neutralized cauldron, their quest item no longer counts. This means that at least one person in the group will be unable to complete the quest.

How it works: Only one person in the group gets quest completion credit.

How it should work: The quest should be marked as complete for the whole group.

Source (you should point out proofs of your report, please give us some source): Just spent over an hour attempting the quest and it worked in this manner every single time.

**Comment by Aridam** [comment]
Is this all present during [Neutralizing the Plague](https://db.darkwizard.pl/?search=neutralizing+the+plague#?ref=sunwell.pl) as well (i.e., the Daily after completing this one)?

@Riztazz, should this be added to [mine](https://github.com/SunwellTracker/issues/issues/2488) as with the last one I made before as well? Since you said you would be fully rewriting the Quests.

**Comment by hellomotow** [comment]
No issues with me. It asks you to do it about every 40 seconds and it's a 30s CD if I remember correctly? I know for sure in my experience (twice) there was 5-10 seconds where it was off CD.

**Comment by ashlacon** [comment]
After completing the quest some of the people in the party went and picked up the daily, and we didn't get credit for it. while people doing the non-daily version of it continued to get credit one by one.

**Comment by Riztazz** [comment]
@Aridam yup
