### ISSUE TITLE
[WARRIOR][WEAPONS SWAP][DISARMED MECHANIC]

### ISSUE THREAD

**Issue by armswarriorwoltk** [SunwellTracker/issues#2613]
Decription: 

Every class who can manage weapons should be able to swap their weapons while getting disarmed.

How it works: 

Actually we can't swap weapons while suffering any disarm effect from players, like rogue class with dismantle, shadow priest with psychic horror, etc ..

How it should work: 

While suffering Disarmed debuff aura, we should be able to switch from 2 hands weapon to any 1 hand + shields, or reverse like 1 hand + shields to some 2 hands weapon.

We can only swap them, meaning we just equip them in character panel.

Proofs : 

retail video during season 

https://youtu.be/XWpYHrRlakU?t=282

you can clearly see Gforce equipping shield and h during disarm

Thoses videos were recorded today on warmane servers, blackrock

https://www.twitch.tv/videos/516103003 ==> showing dismantle from a rogue on warrior target

you can see he can go from two hands to 1hand + shields while suffering an dismantle debuff aura and he's still able to swap his weapons

https://www.twitch.tv/videos/516104126?filter=archives&sort=time == > showing disarm from a rogue on warrior target

you can see he can go from two hands to 1hand + shields while suffering an disarmed debuff aura and he's still able to swap his weapons

https://www.twitch.tv/videos/516105444?filter=archives&sort=time ==> same with shadow priest disarm

https://www.twitch.tv/videos/516106412?filter=archives&sort=time ==> same <with hunter disarm

**Comment by Aridam** [comment]
> warmane

> blackrock

Sure, buddy. Obviously Warmane is Retail. Yeah. Right.

**Comment by armswarriorwoltk** [comment]
Same mechanic on every server, and same on every server you played / still play

**Comment by armswarriorwoltk** [comment]
Same mechanic since season 5, can’t talk for burning crusade or vanilla.
Anyway i already found 2 old pvp vid recorded in season 8 where an arms warrior actually swap into 1hand + shield during disarm i just need to highlight it when i got my hands on a pc, no idea if you will come with same behavior and shitstorm

**Comment by Aridam** [comment]
https://www.mmo-champion.com/threads/770111-Sword-amp-Board-while-disarmed?p=9044886&viewfull=1#post9044886
https://www.mmo-champion.com/threads/770111-Sword-amp-Board-while-disarmed?p=9045049&viewfull=1#post9045049
This was back in October of 2010.
Patch 3.3.5a came out June 29, 2010.
https://wow.gamepedia.com/Patch_3.3.5a
So in other words, this is a 3.3.5a source.

https://eu.battle.net/forums/en/wow/topic/1417585309
This is an early Cataclysm source (check date) just to further ridicule your bullshit. This _also_ confirms that you couldn't swap out affected Weapon Slots during Disarm effects. In other words, this change _persisted **through**_ late-WotLK into early-Cata AT LEAST. Read it, lazyass.

Add my sources from my original report which got this FIXED to the table, against which you initially made an invalid report calling it "bugged", now doing the same with this one.

Please reroll your Class -- this, coming from a Warrior main.

No, Warmane isn't Retail, or better, or even anything close to its total percentage of working content.
No, its content isn't what "should" work because it's "competitive".

The prior mechanic _did_ exist in Season 5, _but it got **changed eventually after**_ -- this is what my _original_ report that got this fixed highlighted, and why I mentioned Swifty showcasing the bug last time -- because that's how it _used to_ work, but afterwards,

it

_was_

_**changed**_.

**Comment by armswarriorwoltk** [comment]
You just link random forums discussion while i going to provide ingame vidéos actions

**Comment by Aridam** [comment]
You are fuckin' hopeless, m'dude.

I'm raising my hands off this. Nice troll, but I'm done.

**Comment by armswarriorwoltk** [comment]
Again in links people are either saying they can’t, or they can, or you can only do this, or only this etc

**Comment by Aridam** [comment]
Gforce 5 is fuckin' Season 7 you twat -- that's _before_ this was changed, when the trick to switch during Disarm/Dismantle was possible.

https://youtu.be/IijlbG7yrlc?t=320
Klinda 7. Season 8 -- Lolmourne and whatnot, beautiful stompfest by a beautiful player, you get the point -- it's Season 8, not Season 7 you moron.
Pay close fuckin' attention 'cause I'm sick and tired of this.
First, he Bladestorms.
Then, he gets Dismantled -- look at the Debuffs, it's there.
Now watch VERY CLOSELY, IN THE SLOWEST OF MOTIONS OR PAUSE-UNPAUSE I DON'T GIVE A SHIT, _AT THE RED ON-SCREEN ERRORS_:
"Must have a Shield equipped"
"Cannot equip that with a two handed weapon"
"You can't do that while Disarmed"
He is trying to swap to his Shield and use Shield-based Abilities ("Must have a Shield equipped"). HE CAN'T -- HE'S FUCKIN' DISMANTLED. HIS 2H WAS STILL ON SO NOW IT'S STUCK. "Cannot equip that with a two handed weapon" is because he's trying to equip his Shield while he's got his 2H on. HE CAN'T DO THAT, BECAUSE IT WAS EQUIPPED WHEN HE GOT DISMANTLED, BECAUSE IT'S **STUCK**.
_AFTER_ the Dismantle, he equips the 1H + Shield and _THEN_ uses his defensive CDs. HE COULDN'T DURING THE DISMANTLE.

Now shut the fuck up.

**Comment by armswarriorwoltk** [comment]
he could press anything related to shields macro then get that error, also we don't see what he's clicking etc when i provided somethign accurate and againg you complain its blabla chinese wow blablabla season 7 when you show me some early cata content comon pls

**Comment by xmachinex87** [comment]
Aridam, shut the fck up, foreal, you are the reason warrior is getting ruined. Fixes that are important dont go through or are delayed because of your whining, or you report some sht that ruins some warrior ability, like not being able to use SHIELD wall while having disarmed WEAPON = you can use SHIELD and SHIELD spells like block reflect wall. Imagine if rogue shp had to push through vampiric touch so they just use disarm so you cant reflect. I have NEVER seen this on any server ever and I have played vs many gladiator rogues. this would change the meta and the use of disarm so fkn MUCH. Fck you and all you stand for you miserable neckbeard cnt. You are obviously not part of GM team with how you behave and if yes then fck you even more. Go to hell.

**Comment by xmachinex87** [comment]
degenerate

**Comment by Aridam** [comment]
> that fucking zoom ain't close from any proof
https://youtu.be/rNVoMGRg4QE?t=244

Same shit, no zoom. Can see what he's trying to use:

**"shield" macro (the one with the "+" icon), to switch to D. Stance + equip 1H-Shield setup,

then Shield Block -- only managed to switch to Defensive Stance,

has Shadowmourne on after Dismantle wears off.**

No more excuses now.

@xmachinex87 this was working on Dragonblight. I encountered this and thought it was a bug, so I reported it on their bugtracker. I was asked to give proof. I complied and went to dig up more information, and that's how I learned that this was actually how it worked in S7 (not China), _**definitely**_ in S8. I can't show the report because they've closed all their services, including their bugtracker. But if you've played there, then you would've seen it.

Meat of the matter is, I don't care. I gave my counter-proof, wasting my time on this to try and prevent some asshole from reverting something I went and spent time and effort in helping diagnose so the devs can fix it and make the game better and more authentic -- if you don't like it, well, go and ask Blizz and blame them retrospectively for something more than nine years back because you want to be OP and mindlessly go about your business while going "BUT MUH OTHER PRIVATE SERVERS HAD IT WORKING MUH" -- you can shut the fuck up with that 'cause it's entirely possible for a server to have fixes either very-few others have, or none at all, making it the first.

A lot about the meta in private servers we've all played in has been wrong for many years. So, either adapt to how it _should have been as it was on Retail back then_, or just don't play a Class that's involved with this mechanic. Because to me it seems you just don't want to deal with it. Too bad.

> you are the reason warrior is getting ruined

That's rich. So basically all the fixes in recent times have been me misleading the devs into fixing something not broken? The only thing that gives that even a _little_ merit, is the very-recent reverted/broken fixes, but that's how it is with code -- you fix something, it _may **or** may not_ break something else, and you can't know unless someone does that again, notices it's different again, and goes to say "Hey this is broken again what's up with that".

Now instead of wasting your time _and_ mine, Mister Gladiator, go ahead and divert some of your precious attention towards betting the Warrior Class, instead of, obviously, arguing for nothing over here. Go on. I'd like to see you try that. Just don't go trying to break stuff like @armswarriorwoltk over here is trying to do. I could always use the help, and the devs definitely could, 'cause they can't fix anything without being pointed towards _exactly what is wrong, how it's wrong, why it's wrong, and why it **shouldn't** be wrong_.

Worthless worm.

**Comment by Aridam** [comment]
Close this -- not a valid issue.
