### ISSUE TITLE
Glyph of Frost Nova (isnt working)

### ISSUE THREAD

**Issue by AdlerRabelo** [SunwellTracker/issues#2622]
![combat log](https://user-images.githubusercontent.com/58469362/70059461-9d498780-15bf-11ea-9001-a64eb5efad9e.png)
Decription: 
the glyph says that your Frost Nova targets can take an additional 20% damage before the Frost Nova effect automatically breaks.

How it works: 
Any hit by any spell schools breaks the frost nova, we cant do shatter combo or any combo with frost nova on target because at the 1st hit frost nova breaks. This impact direcly on mages gameplay.

How it should work: 
for example: if we have Glyph of the Frost Nova equiped
and we frost nova an enemy and i hit 100 by any spell school, it means frost nova should not break and will continue till the end or after i hit more 20 damage by any school spells (it means 20% more from 1st hit by spells)

i have been testing this since lvl 20 when i use the glyph and never works, please fix it.

Source (you should point out proofs of your report, please give us some source): 

see my combat log print screeen, my frost nova dissipates after fire blast

**Comment by Azathothh** [comment]
"see my combat log print screeen, my frost nova dissipates after fire blast"
it doesn't mean that your glyph isn't working, it just means that your frost nova isn't strong enough (even with glyph) to not break after dealing 312dmg.

No glyph: 
![obraz](https://user-images.githubusercontent.com/37483678/70198592-8d40bd80-170f-11ea-8d0a-3992319a0541.png)
It's breaking when i've dealt 1297 dmg

With glyph:
![obraz](https://user-images.githubusercontent.com/37483678/70198690-cc6f0e80-170f-11ea-9cea-c132bd9ebf77.png)
It's not breaking after dealing 1297 dmg because glyph is working and increased amount of dmg that target can take before Frost Nova breaks

**Comment by AdlerRabelo** [comment]
The glyph is lvl 15 so a lvl 15 frost nova should work just ine not just high spell ranks or be a lvl 80.
