### ISSUE TITLE
[Item / Loot] Icecrown "4 big pack" loot table changed 

### ISSUE THREAD

**Issue by kmkmkm0** [SunwellTracker/issues#2624]
Decription: So there is these nice big pack in icecrown for aoe farming was fine few day ago but now they barely loot anything .

talking about there spot :
https://ibb.co/SXTZ30Z
https://ibb.co/L94ydbx
https://ibb.co/zGwzP4p
https://ibb.co/gds43Fr

How it works: they dont loot thing anymore

How it should work: they looted few days ago.

Source (you should point out proofs of your report, please give us some source):

**Comment by kmkmkm0** [comment]
more test needed but weird

**Comment by kmkmkm0** [comment]
ok i killed them all 3 time now , they rly dont loot thing isnt just me unlucky ...

**Comment by kmkmkm0** [comment]
round 4 recap loot :
pack 1 : 2 fur clothing scrap , 1 thick fur clothing scrap
pack 2: 2 frostwave , 1fur clothing scrap
pack 3 : 3 vyrkul bone , 2 frostwave , 4 fur clothing scrap , 4 thick fur clothing scrap & 1 green 
pack 4: 4 frostwave , 3 fur clothing scrap , 1 thick fur clothing scrap

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2616

**Comment by Dootz** [comment]
https://www.wowhead.com/npc=30957/death-knight-initiate#comments:id=578064
https://www.wowhead.com/npc=30957

Hi, they were exploited to level up and aquire a lot of items. We decided to implement changes based on wowhead ( no loot ) and comments ( experience ,loot nerfed - only gold ).

**Comment by kmkmkm0** [comment]
Yes, it s a nice spot.
Like it wasn t a probleme on your other server but now it is ?
If it you considere it as an "exploit" then remove the gold form people who farmed this spot or leave it at what it was .. i dont know. 
This change now is strait up bullshit is you ask me .

**Comment by Aridam** [comment]
@kmkmkm0 
That argument kinda invalidates _all_ fixes if you ask _me_, rather, especially the big ones (Random Dungeon Cooldown got the same treatment) -- as in, why fix this and that if people before used that to their advantage, rather than leave it as-is or at least compensate in some manner for, as if, seemingly making a bad mistake by "allowing" people to abuse it, or just being a dick on purpose.

That's how it was like on Retail, too, at the time -- pretty sure people who used this as an exploit didn't get reprimanded or punished for it afterwards. It's part of the concept behind ongoing-content patch changes, hotfixes, and even stealth/ninja/undocumented fixes.
