### ISSUE TITLE
Hunter pets don't stand behind target

### ISSUE THREAD

**Issue by Tylo2** [SunwellTracker/issues#2635]
Decription: 
When someone else is tanking the target, the pet simply runs up to the target and, as soon as it's in melee range, stops moving and starts attacking. This leads to the pet quite often standing in front of the target, causing attacks to get parried which is a problem on bosses for example.

How it works: 
When someone else tanks an enemy the pet runs up and starts attacking from whatever direction it came from, regardless of where the boss is facing. To reproduce the bug, just have someone tank a mob or a boss and send your pet in to attack.

How it should work: 
Unless the pet is tanking the target, it should position itself in such a way that it's attacking from behind.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/6kZsaJJ
(Sorry for bad quality, let me know if you need me to remake it)

**Comment by Aridam** [comment]
Videos for reference:
https://youtu.be/TWJ59rs04ag?t=44
https://www.youtube.com/watch?v=SMTRbp0uel0&feature=youtu.be&t=26

[TC issue](https://github.com/TrinityCore/TrinityCore/issues/19925) to correlate with this.

As mentioned in the TC issue, however, Pets are supposed to not auto-reposition if they're the focus of the same Target they're attacking -- allowing otherwise would cause an infinitely-repeating issue where the Pet would try to reposition behind the Target that has them on focus, while the Target keeps turning to face the Mob. **In PvP, Pets automatically don't reposition themselves, as seen [here](https://youtu.be/zxIMtOriauw?t=106).**

**Comment by Tylo2** [comment]
Thank you for those clarifying videos Aridam, they're great! Also thank you for explaining the problem a bit better than I was able to.

**Comment by bonfax4** [comment]
There's also an issue where pets wont properly atack a running target, even if dash is up
