### ISSUE TITLE
Fix bugs?

### ISSUE THREAD

**Issue by jounko93** [SunwellTracker/issues#2639]
Do you guys fix older bug reports or should we repost them theres bunch of major bugs 20+days old and nothing is done to them, yet u are fixing some minor stuff all the time or are they too hard to fix?

Source (you should point out proofs of your report, please give us some source):

**Comment by Zeorgbugfinder** [comment]
spells and talents are so horrible on this server
everything else is better than on other private servers but spells and talents(the most important thing) is the worst on this server

**Comment by Aridam** [comment]
> spells and talents are so horrible on this server

Sword Spec and Sweeping Strikes are a couple (out of some more) aggravating examples to name -- they each have like a few bugs. This server has one of the better iterations of Sweeping Strikes compared to a few others though -- _at least it's actually a usable Talent to an extent_.

> everything else is better than on other private servers but spells and talents(the most important thing) is the worst on this server

Agreed, though there are quite a few core issues (as in relating to Stats/AI/global mechanics etc.) and some Spell and Talent bugs (some of which are also very-key due to an established meta requiring them, or purely because of some important mechanic). I wouldn't say it's the _worst_, though because I've seen worse elsewhere with no regards -- let alone hope -- of fixes.

> Do you guys fix older bug reports or should we repost them theres bunch of major bugs 20+days old and nothing is done to them, yet u are fixing some minor stuff all the time or are they too hard to fix?

Actually there might be some even-older reports which have been fixed but eventually got broken again, but due to lack of player feedback in the occurrence of a past fix getting broken being given to same said reports, you can't expect even the devs to know that something got broken rather than it's in fact working as they had initially fixed it. I've seen people complain on Discord but if I go and search this bugtracker for possible reports based on claims, either it's an old report which may or may not have been fixed (but assumedly has been broken, given the claims), or just, there's not even a single bugreport whatsoever. Hell, I've seen people ask/complain about Hunter Pet smart AI that's supposed to send them to the back of their Targets, but a report on that _finally_ got made by someone a few days back and I was able to provide my research on the matter. I don't play Pet Classes so I couldn't know if or if not that even worked here, so I couldn't go and check for myself -- it's just that people don't bother.

As for minor fixes, I mean, if they're minor and easy to code, might as well get them out of the way while still (hopefully, assumingly) working on the major ones. Prevents having thousands of open issues and all that.

Some issues may sound easy, logical and intuitive to fix on paper, but they can and _may or may not_ be a whole other story in actual code.

This isn't really a bugreport though -- this should've been a forum topic, or a question on the Discord server towards the staff, or a DM to a staff member who may or may not be able to tell you or to at least tell you who to talk to instead.

**Comment by Nadiirr** [comment]
If there's an old bug you'd like to see fixed you can provide more info for it. 

Yes, we do go through the whole list of bug reports. We have different developers working on different things and we want to address everything, but have to focus our time and resources on certain things. 

Feel free to PM me on discord and I'm happy to address any concerns you have about things not being fixed in a timely manner. 

Thank you, and we're trying! <3
