### ISSUE TITLE
[DRUID] Talent Omen of Clarity doesnt work

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SunwellTracker/issues#2641]
Decription: Talent Omen of Clarity doesnt work as it should

How it works: 
Talent Omen of Clarity NEVER proc on hurricane, starfall, typhoon

How it should work: 
Talent Omen of Clarity SHOULD proc on hurricane, starfall, typhoon

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/o0XrDt4
talent SAYS it procs on EVERY dmg spell
this is so big nerf to druid
im litteraly out of mana in raids as balance druid in long fights
in pvp its even worse... balance druid really needs mana in pvp
pls fix this talent its the most important druid talent it should work on 100%

**Comment by styxel** [comment]
There has been some talk about blizzard making hurricane only proc from the initial cast of hurricane rather than every tick of the spell cant find it right now but im pretty sure i saw it some where havent tested hurricane here so no idea of this issue is True. Anyway yes ooc is pretty broken atm its not proccing from a lot of things
https://github.com/SunwellTracker/issues/issues/2500

**Comment by Aridam** [comment]
> There has been some talk about blizzard making hurricane only proc from the initial cast of hurricane rather than every tick of the spell cant find it right now but im pretty sure i saw it some where havent tested hurricane here so no idea of this issue is True.

[Here you go.](https://www.mmo-champion.com/threads/622133-Omen-of-Clarity-Hurricane-Ninja-Nerf)

Also yeah, refer to #2500 -- that's the original report which got confirmed.
