### ISSUE TITLE
Gambling Debt quest broken

### ISSUE THREAD

**Issue by zygfrydmina** [SunwellTracker/issues#2647]
Decription: 
Quest NPC needs to get beaten to about half HP and turn friendly. Then he shoud give a quest item called ' "Silvermoon" Harry's debt'.

How it works: 
NPC turns friendly, but doesn't give the item. Quest is uncompletable (consulted with GM Azureuz).

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Reference: https://www.wowhead.com/quest=11464/gambling-debt#comments:id=375653
One of the replies below it:
> He turns friendly again at 50%...so be careful!

**Comment by Azathothh** [comment]
@zygfrydmina are you 100% sure that you've done exactly what you've been supposed to do? It works fine for me.
![obraz](https://user-images.githubusercontent.com/37483678/70439285-f61d9200-1a8f-11ea-825b-2a0de59c32fa.png)
When npc turns friendly you have to speak with him and use "Pay up, Harry!" gossip option. Also you must have empty bag slot otherwise you won't get it obviously.

**Comment by amed80** [comment]
![image](https://user-images.githubusercontent.com/8395873/78460831-254db400-76bc-11ea-83fb-a197f2324a36.png)
still broken

**Comment by kaileeno** [comment]
Quest is not working correctly. After beating him you got to choose same option as before which means you start battle over and over again. Waiting for fix, need my loremaster :)
