### ISSUE TITLE
Isle of Conquest (Horde) ghost spawn

### ISSUE THREAD

**Issue by Rosenkrantz** [SunwellTracker/issues#2673]
**Description:** whenever player dies and is put at the top right graveyard, they are put too far from Spirit Healer; as in, you have to walk as a ghost ~20yds towards the graveyard to start the countdown to resurrection. Sounds like a minor thing, but it can really throw people off and cause them to miss 30s timer, especially that in no other battleground you have to move to be res'd.
(Also an unconfirmed bit: I think people should never spawn in this graveyard if horde controls ANY other one - and I got assigned to resurrect there dying near the keep, while we controlled the keep graveyard. Can't confirm whether it's incorrect, but feels very wrong - if anyone looking at this has any info, please submit)

**How it works:** people spawning in top right graveyard are too far from spirit healer to be instantly resurrected.

**How it should work:** people should spawn close enough to be resurrected.

**Source (you should point out proofs of your report, please give us some source):** ...only experience and common sense, unfortunately, but no other battleground in history of WoW ever spawned players outside of automatic resurrection range.

**Comment by Aridam** [comment]
https://wow.gamepedia.com/index.php?title=Isle_of_Conquest&oldid=2530657#Secondary_Objectives (this is supposed to be the last revision before Cata-related edits to the page)
> There are five graveyards in the Isle of Conquest that are attached to different points of interest on the map: the Horde base, the Alliance base, an oil spill island in the center of the map (attached to the siege workshop), the Airship Hanger, and the Docks.
Two additional graveyards of last resort, used only when a faction does not have full control of any of the five primary graveyards, can be found on the northeast and southwest corners of the map, for the Horde and Alliance respectively. These two graveyards cannot be captured by the opposing faction.

So people are supposed to spawn at the closest Graveyard of control that they have based on where they die, otherwise they'll all be sent to the Faction-corresponding "last resort" ones if they have none under control.

Regarding the main issue at hand, it really does sound stupid for a GY to spawn Players too far from the Spirit Guides and require them to move in before they miss the Resurrection Timer. However, I've personally been unable to find video evidence showing that particular GY and where it spawns Players compared to its Spirit Guide's position to be able to relate to this report, so that's annoying.

**Comment by Rosenkrantz** [comment]
So far the main point has been fixed (ghosts are spawned close enough for a res), but I've never seen any player get resurrected in any other graveyard than the last resort one, and it actually warps gameplay tactics a lot - alliance is locked into Docks, and horde is locked into Hangar due to players always respawning near these respective bases.
