### ISSUE TITLE
Fa la la la Ogri'la

### ISSUE THREAD

**Issue by saraasolange** [SunwellTracker/issues#2694]
Decription:  I didn't get the achievment doing it correctly, something has to be bugged. I did as I used to do it in the past, and didn't get the achi.

**Comment by Aridam** [comment]
Provide more info rather than a short, abrupt and lacking-in-data report.

For instance, did you do as said here?
https://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila#comments:id=922739

For your information, you shouldn't have to do the entire Quest while using a Flying Mount with the Buff up -- you just need to do that _before you hand in_.

**Comment by saraasolange** [comment]
I just want to solve the problem, I did with the reindeer all the time, what's the difference? I didn't want to put here, gm sent me here, just want to get the achiv, that's all.
