### ISSUE TITLE
Arena Season 3 Set Vendor (Vengeful)

### ISSUE THREAD

**Issue by RAZWANN** [SunwellTracker/issues#2695]
Decription: 
The NPC "Meminnie" (https://www.wowhead.com/npc=19857/meminnie) located in Blade's Edge Mountains is supposed to sell all the Vengeful Gladiator's Armor pieces, but she does not sell the Shoulders.

How it works: 
She is selling Off-Hands, Legs, Helmet, Hands and Chest pieces. What she is not selling is the Shoulder pieces. The prices are still set like they were in TBC (900 Arena Points for hands for example), but that is not necessarily a bug.

How it should work: 
She should be selling the Shoulder pieces aswell:
http://db.darkwizard.pl/?item=33699
http://db.darkwizard.pl/?item=33726
http://db.darkwizard.pl/?item=33753
If something could be done about the overpricing aswell, since this is a TBC Set and it still costs as much as it did on release, that would be very appreciated aswell.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/b7J2jUp

**Comment by Aridam** [comment]
>Decription:
The NPC "Meminnie" (https://www.wowhead.com/npc=19857/meminnie) located in Blade's Edge Mountains is supposed to sell all the Vengeful Gladiator's Armor pieces, but she does not sell the Shoulders.

https://www.wowhead.com/npc=19857/meminnie#comments:id=728895
>she vanished. so s3 is no longer avaible to players

Comment from v3.1.2 (mid-Ulduar).

https://www.wowhead.com/npc=19857/meminnie#comments:id=728895:reply=121340
>Ty i was lookin for a response like this =( no longer avaliable

Reply from v3.2.0 (ToC).

She's not supposed to exist.

Furthermore, check S3 rewards off a Wiki source prior to Nov 29 '11 (v4.3.0, Cata) -- S3 is not available to players as a whole anymore.
However, check again as of Nov 29 '11:
https://wow.gamepedia.com/index.php?title=Season_3&direction=next&oldid=2817490
Available again.

This supports the comment:
https://www.wowhead.com/npc=19857/meminnie#comments:id=728895:reply=284505
>All Season 3 is now available again from the vendors in Area 52 in Netherstorm

Written during v4.3.0.

https://wow.gamepedia.com/Patch_4.3.0
>Release date | November 29, 2011

So it lines up.

**The fact she exists at all and sells all that Gear (excluding the Rings -- similar to Relentless Rings being available during Wrathful Season 8) is ironically a _confirmed bug_ in of itself right now, because we're running v3.3.5a. She and all those Items as pointed out should be gone.**

>The prices are still set like they were in TBC (900 Arena Points for hands for example), but that is not necessarily a bug.

That's true -- the prices for all Arena Set Items which were still available to players pre-Cata remained as they were back in Retail TBC, so not a bug.

>How it should work:
She should be selling the Shoulder pieces aswell

Refer to my first statement about that NPC and Vengeful as a whole.

Personally, I'd find it neat if Vengeful Items as a whole could be made available again, alongside reducing the prices of _all_ TBC Arena Set Items -- it could diversify L70+ PvP in the server and breathe it some more life (especially for non-78+s, and even _moreso_ given that #2589 isn't receiving staff feedback still). However, this in particular is something to suggest to the staff and make forum posts/polls and raise awareness if possible.

**Comment by RAZWANN** [comment]
I do know that this NPC is not supposed to exist during WotLK, but seeing her spawned i thought it was intentional by the developers so that we could use the set along with the Transmog feature.

Personally, i don't think they should remove it now since there is no point really, but we will see what the Developers decide to do about this situation.

**Comment by Dootz** [comment]
Hi.
We decided to leave npc in-game and add missing pieces. If you would like to see any changes to this please leave a comment in this thread. Thanks!
