### ISSUE TITLE
[Hunter][Warrior] Intercept going through deterrence

### ISSUE THREAD

**Issue by blazetrooper** [SunwellTracker/issues#2701]
Incorrect warrior fix ruined deterrence. https://github.com/SunwellTracker/issues/issues/2538

How it works: intercept is unparryable ability

How it should work: Intercept can't be parried because it's not melee attack and not require melee weapon, it should be regular physical spell that confront **deflection part** of deterrene or **ranged anti-hit**

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/spell=19263/deterrence#comments:id=1042488

> EDIT: Read all the comments, and want to answer a question. Yes, this DOES deflect warrior charge/intercept stuns, just like ANY other attack or spell, except for those which cannot be dodged/blocked/parried (like Overpower), and will not deflect or remove the DoT's or their ticks which are already on you, but will not allow to pop up some new until it's effect expires.

Other edits: Fixed some typos.
Enjoy ;)
Last edited by Wiliusas on 2010/05/28 (Patch 3.3.3)

**Comment by Aridam** [comment]
I'll test this out in a bit. Intercept is not supposed to be subject to Dodge, Parry etc., but Deterrence is an exception, as pointed out on the original report.

**Comment by Zeorgbugfinder** [comment]
nope
deterrence is something else than just parry
its like saying all spells like frostbolt, wrath, chaos bolt should go through deterrence

**Comment by Aridam** [comment]
>I'll test this out in a bit. Intercept is not supposed to be subject to Dodge, Parry etc., but Deterrence is an exception, as pointed out on the original report.

Confirming this. To add, not only does it happen with Intercept, it also happens with Charge.

**Comment by blazetrooper** [comment]
Update. Heroic throw bypass deterrence also

**Comment by Aridam** [comment]
Heroic Throw is supposed to bypass it.

**Comment by blazetrooper** [comment]
Wrath-Logo-Small Patch 3.3.0 (08-Dec-2009): Now also increases the chance for ranged attacks to miss the hunter by 100% while under its effect.

> Deterrence doesn't work while **stunned** (as far as spell damage goes)?
we are talking about normal situation without stun

**Comment by Aridam** [comment]
>Wrath-Logo-Small Patch 3.3.0 (08-Dec-2009): Now also increases the chance for ranged attacks to miss the hunter by 100% while under its effect.
All your "proofs" dated before 3.3.0 patch. Thx for your contribution.

Not sure if you're trolling or trying to incite something here (or both), because I made quite sure to give data as relevant to 3.3.5a as possible.

Did you not read the WoWHead comment (third link)?
![Screenshot (1)](https://user-images.githubusercontent.com/33205812/71448903-9986cc00-274b-11ea-93bc-c35eee7b1d4b.png)
Hell, read the reply below it. Read the Ability's description table too. For crying out loud it's not even a Ranged Ability, so that Hunter patchnote is actually irrelevant to it -- it's a **Melee Ability**, inheriting the **Melee Hit Chance Stat**. It's one of those Abilities _intended_ to ignore it. Just like Shattering Throw. And Overpower. And Chaos Bolt. And many more exclusive Abilities like that.

You're welcome, by the way. No thanks from me for your attempt at enforcing misinformation though.

**Comment by keepokappalul** [comment]
Add meme here: Charge through detterence.

**Comment by keepokappalul** [comment]
What a meme i found here .

**Comment by Soufly** [comment]
Intercept/Charge/EVERY KIND OF STUN goes through deterrence ..... @Wojtyas @lukaasm @Dootz HELLO ?

**Comment by Soufly** [comment]
How hard is to allow the movement path of the charge/intercept and deflect the stun ?
Still not fixed.Also HoJ goes through deterrence just like i said TEN days ago...

**Comment by dariuzsdk** [comment]
No update on this after this long? This is a HUGE bug guys cmon

**Comment by Soufly** [comment]
@Wojtyas @lukaasm @Dootz bump
