### ISSUE TITLE
Holy Priest talent  Spirit of Redemption

### ISSUE THREAD

**Issue by BlazeThunder** [SunwellTracker/issues#2713]
Decription: Been a problem a long time already  

How it works: If I die, any way the talent will trigger,  causing my character to become  a spirit healer for a  while.

How it should work: If you fall out of the world for example Outland or Eye of Eternity Phase 3. It shouldn't trigger, or at least it should let you release spirit without needing a relog. 

Source (you should point out proofs of your report, please give us some source): I play a holy priest myself.

**Comment by Aridam** [comment]
This is speculation -- as I **don't personally know with certainty** whether or not it's procced by dying to Fall Damage -- but, going by the "Going Down?" Achievement and Spirit of Redemption Talent pages on Wikis, it's implied that jumping to your death shouldn't proc the Talent, so if you proc the Talent whilst falling down, you're able to get the Achievement, as opposed to otherwise.

https://wowwiki.fandom.com/wiki/Going_Down%3F
https://wowwiki.fandom.com/wiki/Spirit_of_Redemption

Additionally, there're these:
https://www.wowhead.com/achievement=964/going-down#comments:id=1006046
https://www.wowhead.com/achievement=964/going-down#comments:id=490412
https://www.wowhead.com/achievement=964/going-down#comments:id=557276
https://www.wowhead.com/achievement=964/going-down#comments:id=639427
https://www.wowhead.com/achievement=964/going-down#comments:id=489370
https://www.wowhead.com/achievement=964/going-down#comments:id=565288
https://www.wowhead.com/achievement=964/going-down#comments:id=1010023

This:
https://www.wowhead.com/achievement=964/going-down#comments:id=490412:reply=176345
may as well confirm it.

**Comment by Aridam** [comment]
Why is this "invalid"?
