### ISSUE TITLE
OOC rescript and shifting

### ISSUE THREAD

**Issue by tii86** [SunwellTracker/issues#2737]
Decription: 
Omen of clarity was recently changed (closed issue #2500) to address issues regarding number of procs generated, as well as sources from which the procs can be generated from. Since the implementation of this fix, shifting (into cat/bear, not travel, untested for tree/moonkin) is now a source of OOC procs, but additionally it also erroneously consumes procs.

Regarding other incorrect sources of OOC generation I have seen tiger's fury, prowl incorrectly generate procs. There is very possibly other sources of generation that i missed. I have yet to see a proc generated by nature's grasp (should generate).

The change to generating procs from shifting is definitely the most important one that needs to be looked at though. Being able to spam fish for procs is a huge obviously unintended buff to feral, especially since the chance to get a proc from shifting seems very high.

**Comment by ganderxx** [comment]
Nature's Grasp works, shifting has 18% procs chance because leaders of the pact, cat form and natural shapeshifter aura atleast i think its because of that basically almost any buff u make on Yourself procs it.

**Comment by styxel** [comment]
Nature's Grasp works, shifting has 18% procs chance because leaders of the pact, cat form and natural shapeshifter aura atleast i think its because of that

Basically almost any buff u make on Yourself procs it like for example switching between rep tabards but u cant Do that In combat so cant rly abuse that. Yeah shifting part is pretty iffy atm if u play with it correctly its can be pretty good dps up.

One thing thats worrysome is If there is some aura u can spam without any gcd and cd u could get procs 24/7 :D idk If there is such items If tabards were usable In combat those would work.

But all tht said most stuff also works nicely faerie fire, barkskin buffs etc are working guess the fix just is a bit more complicated.

AND regarding resto spec its worse than anything i saw 110 procs on sapphiron and thaddius and most other bosses also 90+ procs unsure whats proccing it its NOT the heals something else i think. I can give logs private If u want @Riztazz

**Comment by Riztazz** [comment]
Could you give it a shot now? Realm has been restarted a few minutes ago and i implemented one more check

**Comment by styxel** [comment]
Cant test it myself now im at work but later today.

**Comment by Aridam** [comment]
This reminds me of how the Dying Curse Trinket from Naxx also had this weird behavior on Retail - - could proc from almost _anything_.

**Comment by Riztazz** [comment]
Closing then :) If anything else happens, do let me know please
