### ISSUE TITLE
[Enchant Weapon] Crusader wrong value on proc

### ISSUE THREAD

**Issue by kmkmkm0** [SunwellTracker/issues#2739]
Decription: Enchant proc dont give the right str bonus.

How it works: the proc only give 23 str at lvl 80.

How it should work: should give 100 str.

Source (you should point out proofs of your report, please give us some source): 
https://ibb.co/Q6mb5xL
https://ibb.co/wdyjkDb
https://wowwiki.fandom.com/wiki/Enchant_Weapon_-_Crusader

**Comment by Aridam** [comment]
https://www.wowhead.com/spell=20034/crusader#comments:id=19571
> Since Crusader is a level 60 spell, it does less every level you are above 60. The exact amount is -4% effectiveness per level.
So at level 70 (a 40% reduction), Crusader only gives +60 Strength and only heals for 45-75 health. The tooltip still states you're getting 100 Strength, but if you look upon your character sheet, the increase is only by 60. Of course, this is the same for any tooltip in the game.

Reply below:
> Following this formula, we get only 20 strength and 15-24 heals at level 80, making it very useless. Also, in Wrath this will proc for druids in feral forms.

Your WoWWiki page says:
> At level 70, Crusader heals for 45-75 health and gives +60 Strength.

You seem to have overlooked that.

I'm guessing you're gaining 23STR and not 20STR because of Talents.

Either way, Crusader's supposed to scale down for every Level from 60 by 4% -- both the Healing component and the +STR component. At L70 that's 40%, at L80 that's 80% less.

**Comment by kmkmkm0** [comment]
alright thanks
