### ISSUE TITLE
[Warlock] Demonic Pact does not refresh itself

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#2783]
Decription: Demonic Pact does not refresh itself after the 20s Internal Cooldown passes.
Talent ID's = {47236, 47237, 47238, 47239, 47240}

How it works: Demonic Pact talent/buff seems to be broken after the fix to: [Link to Bugtracker](https://github.com/SunwellTracker/issues/issues/1108). Right now the buff does not refresh itself after the pet crits and 20s of internal cooldown passes if the next Demonic Pact would give LESS Spell Power than the previous one.

How it should work: Demonic Pact Talent/Buff should proc even if the second Demonic Pact would give smaller amount of Spell Power than the previous one.

Source (you should point out proofs of your report, please give us some source): 

Please find in attachments below that the Demonic Pact buff was never refreshed earlier than 45 seconds from prior proc:

![demo1](https://user-images.githubusercontent.com/13186009/71788456-a8f6f680-3022-11ea-9e8f-2e6f365ef9d9.png)

![demo2](https://user-images.githubusercontent.com/13186009/71788457-ad231400-3022-11ea-8774-e544637dc075.png)

> **Smaller Demonic Pact procs **can overwrite larger demonic pact procs****
Due to this behavior a demonic pact proc granting less spellpower than the current demonic pact proc can still overwrite the current proc. While this is not ideal, it should be noted that this is also not 'horrible' by any means. Without this behavior demonic pact would show a fairly notable amount of downtime, and despite this behavior each demonic pact proc will last on average the same amount of time, what this essentially means is that if you have a temporary spellpower proc that when averaged out would mean a constant 100 spellpower for your DPS, than the constant average demonic pact proc interval would cause you to (again, on average) benefit as much from the proc as the constant 100 spellpower otherwise would have.

[Elitist Jerks](https://web.archive.org/web/20100701132523/http://elitistjerks.com/f80/t100099-demonology_releasing_demon_you)

**Comment by Riztazz** [comment]
Fix you've linked is not related. It was simple formula change that excludes existing pact SP bonus.
Something else is causing issue here, i will take a look at it

**Comment by Ordeone** [comment]
Any news about that bug ?

**Comment by Soufly** [comment]
Hello,can u fix that already ? Now instead of using a demo warlock,u have to use demo and ele shaman,in order to keep up the spell power ...

**Comment by wonszopaionk** [comment]
Well update for the issue.

The problem described (that DP is not refreshed even if SP bonus is lower) causes another bug that I encountered.
If the pet crits while stronger DP is up and DP proc is not on CD - it causes DP to go on 20s CD without getting the proc. This causes downtimes of DP.
Below is the log in which you can see the situation:
![obraz](https://user-images.githubusercontent.com/28888570/86024071-d00c0f00-ba2c-11ea-986b-78e087157cfa.png)
1st DP:
19:10:34 - first DP comes up
19:10:54 - DP CD fades
19:11:00 - DP should be refreshed but isn't - stronger proc suppresses weaker DP from refreshing.
2nd DP:
19:11:22.87 - DP comes up
19:11:42.87 - DP CD fades
19:11:45.67 - DP not refreshed due to lower SP buff- CD comes up
19:12:05.67 - DP CD fades ?
19:12:06.72 - DP not refreshed due to lower SP buff? - CD comes up
19:12:07.8 - DP wears off
19:12:08 - 19:12:23 - **pet crits five times without popping DP** 
19:12:26.72 - DP CD is up
19:12:32 - DP comes up - it caused downtime of DP for about **25** seconds (6 of which were unlucky due to no crits between 19:12:26 - 19:12:32)

Here are Method's logs where DP is refreshed constantly (it just doesn't wears off - its 97% uptime for Marrowgar):

http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=%28spell+%3D+%22Demonic+Pact%22%0D%0AAND+sourceName+%3D+%22Flaaghun%22+AND+targetName%3D%22Plazma%22%29%0D%0AOR%0D%0A%28sourceName+%3D+%22Flaaghun%22+AND+isCritical%3DTRUE%29

![obraz](https://user-images.githubusercontent.com/28888570/86025793-ed41dd00-ba2e-11ea-9b37-0755fd5104d8.png)
18:22:26.43 - DP comes up
18:22:46.43 - DP CD fades
18:22:46.47 - DP is REFRESHED
18:23:06.47 - DP CD fades
18:23:14.06 - DP is REFRESHED 
18:23:34.06 - DP CD fades
18:23:34.6 - DP is REFRESHED
18:23:54.6 - DP CD fades
18:24:04 - DP is REFRESHED

It works both ways of course - its really good to have 560+ SP buff for full 45 seconds isn't it? But if you are unlucky, you won't get any buff for ~20 seconds.

If it could've refresh we would have 560-ish for 20 secs and then probably ~400 for another 20 secs. And another 500+ (trinks CDs wear off) for 20 secs etc. Current state are really unpredictable, due to godbless RNG you can have nearly all the time 550+ SP buff up, (each 45 secs ICD of trinks wear off) but if you have shit RNG - you get 550+ on start and then struggle to get ANY good Demonic Pact cause they constantly wear off due to not refreshing itselves.


Please fix Demonic Pact to refresh the buff regardless of SP gained as retail logs show us.

**Comment by wonszopaionk** [comment]
@Riztazz can you assign anyone to this? I gave my explanation in the post above.
