### ISSUE TITLE
Feral Aggression

### ISSUE THREAD

**Issue by Crabbyx** [SunwellTracker/issues#2791]
**Decription:** 
0/5 [Feral Aggression] = 408 (debuff ap)
1/5 [Feral Aggression] = 441 (debuff ap)
2/5 [Feral Aggression] = 473 (debuff ap)
3/5 [Feral Aggression] = 506 (debuff ap)
4/5 [Feral Aggression] = 539 (debuff ap)
5/5 [Feral Aggression] = 571 (debuff ap)
[Feral Aggression](https://wotlk-twinhead.twinstar.cz/?spell=16862)

**How it works:** 
After casting on target [Demoralizing Roar] which has been buffered by 5 points [Feral Aggression] gives 411 (debuff ap)

**How it should work:** 
After casting on target [Demoralizing Roar] which has been buffered by 5 points [Feral Aggression] should give 571 (debuff ap)

Source (you should point out proofs of your report, please give us some source): 
![ap1](https://user-images.githubusercontent.com/59671424/72026159-d807a500-327a-11ea-8a3c-73914ca2a6e8.jpg)
![ap2](https://user-images.githubusercontent.com/59671424/72026160-d807a500-327a-11ea-9b41-57b9468ebe70.jpg)
![ap3](https://user-images.githubusercontent.com/59671424/72026161-d807a500-327a-11ea-9e57-7699e0785410.jpg)

**Comment by Azathothh** [comment]
It works fine - just check it on duel and compare AP without Roar and with Roar.
Buffs and Debuffs tooltips are not updated with values modified by talents (it's same with all spells like that, for example Improved Blessing of Might would show 550ap in tooltip while it gives 687 at 2/2) and that's because of the way that game client works - it was same on retail.
Also 408ap value in Demoralizing Roar spell tooltip is slighty off, as it's 411 - "For every level gained, the AP reduction for both Roar and the warrior's Shout increases by 1, making both skills equivalent at level 80, with a reduction value of 411. (This undocumented change was likely made in Patch 3.0) "
so at 5/5 it does reduce 411x1.4 = 575ap
