### ISSUE TITLE
Warlock desctruction backdraft talents bugged

### ISSUE THREAD

**Issue by BIaireau** [SunwellTracker/issues#2809]
Decription: we closes my previous issues but i will bring more proof. The talents backdraft that reduce the next 3 destruction is bugged for rain fire. making his aoe less important, im in love with this spec since i dont love affliction. i dont want to stop playing just because my aoe is less better :(
they made rain of fire like this on this patch usually , or seed of corrutpion is even better as destruction, thats not normal

How it works: its not reduce 30% rain of fire casting speed

How it should work: suppose to be reduce rain of fire 30% casting speed

![WoWScrnShot_011620_230320](https://user-images.githubusercontent.com/29809137/72583771-83d17600-38b5-11ea-8545-f1fee5e82b14.jpg)
on the first screen its on another server wotlk dalaran-wow, the talents work fine.

![WoWScrnShot_011420_025632](https://user-images.githubusercontent.com/29809137/72583793-9c419080-38b5-11ea-8352-bdcab00634c7.jpg)
on the second screenshot its on sunwell frosthold, the talent not affect rain of fire.

https://wotlk.evowow.com/?spell=47820
on the data base wotlk, we see below its show all spell and talents that affect rain of fire , we see the backdraft :)

Source (you should point out proofs of your report, please give us some source):

**Comment by Aijena** [comment]
Refusing to actually look into the facts and truth and just closing a legitimate issue is just so unpleasent to see...
On your own database https://db.darkwizard.pl/?spell=47820 [Rain of Fire] shows as affected by Backdraft aswell as https://db.darkwizard.pl/?spell=54277 [Backdraft] itself shows modifying all Hellfire Ranks and variations aswell as for Rain of Fire...

If you don't fix this you legit kill a good amount of players who enjoy destruction warlock, i know 2 friends in my circles who respecced and play an inferior experience now because of this...

Please fix it instead of just closing it and looking away.

Thanks.

**Comment by Azathothh** [comment]
"but i will bring more proof" and you didn't provide any proofs, only posted screenshot from different private server on which this talent is bugged.
https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire  just check this topic to see that's how it was working on retail... It works fine now.

"the **cast time** and **global cooldown** of your next three Destruction spells is reduced by 30%"
Rain of Fire doesn't have cast time - it's channeling. It does reduce global cooldown though and that's why "On your own database https://db.darkwizard.pl/?spell=47820 [Rain of Fire] shows as affected by Backdraft "

**Comment by Aijena** [comment]
Thanks for clearing it up and explaining it properly in detail why RoF and Hellfire show up in the database.

https://www.wowhead.com/forums&topic=111336 - here another discussion to read for "how it was"
