### ISSUE TITLE
World boe items

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#2830]
Decription: 
https://db.darkwizard.pl/?item=37835 , https://db.darkwizard.pl/?item=44308 should have higher % drop rate during naxx.

How it works: Low % drop.

How it should work: 
https://db.darkwizard.pl/?item=37835 , https://db.darkwizard.pl/?item=44308 should have higher % drop rate during naxx,just like the latest fixes: https://github.com/SunwellTracker/issues/issues/2815 

EDIT:https://db.darkwizard.pl/?item=37835 Should drop from https://www.wowhead.com/npc=29844/icebound-revenant as well - 0.01% but during naxx i guess should be 1% like the other ones.
Source (you should point out proofs of your report, please give us some source):

**Comment by Dominiklas** [comment]
how do u know it should have higher dropchance during naxx content, can you show proof? 
Also every class should have different talents during naxx, so let's change talents accordingly :)

Please stop making stupid changes, same goes for tears of bitter anguish as the drop rate is already fucked up.

**Comment by Soufly** [comment]
''yep it exists i got it on the 4th kill which was a Nascent Val'kyr while doing dailies around the area''
random wowhead comment yeah ?

**Comment by HealingEmpress** [comment]
Please do not take anecdotes as evidence. Randomness does work like that. You can get a 0.05% drop rate on the first kill. You can also never get it, no matter how many you kill.

Please thoroughly research your suggestions instead of "it feels low, because I don't get it". There are archived drop rates you can find through https://archive.org/ that goes against feelings and suggest pseudo-empirical data.
