### ISSUE TITLE
[Quest] Hampering Their Escape

### ISSUE THREAD

**Issue by Jorlain** [SunwellTracker/issues#291]
Decription: 
Quest - Hampering Their Escape in Borean Tundra requires to destroy 3 platforms with grenades to complete objective. Out of the 3 platforms, 2 of them I could destroy but the 3rd one (northern platform) is permanently on fire. I've tried throwing the grenade from all directions, closer & further away with no luck. Just got the message "You can't do that yet". Tried waiting around, and even after 30 minutes, the platform was still on fire. 

How it works: 
The Northern Platform is permanently on fire, making it unable to throw the grenade at it to complete objective.

How it should work: 
The Northern Platform shouldn't be on fire so the grenade could be thrown at it to destroy it (set it on fire) and complete objective.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=11617/hampering-their-escape#comments

**Comment by Dootz** [comment]
i tested it and turns out that fire deals no damage, so it is possible to land on this platform and throw grenade to complete objective. Probably range should be increased to help players without flying mounts to complete this quest. Also platform shouldn't be on fire all the time, but only after explosion.

**Comment by Dootz** [comment]
It is possible to use grenade while standing on ground under platform

**Comment by Dootz** [comment]
we'll be applied with next update
