### ISSUE TITLE
[Warlock] drain soul

### ISSUE THREAD

**Issue by ozzyian** [SunwellTracker/issues#299]
Decription: 
Drain soul does not refresh corruption with everlasting affliction talent.

How it works: 
Use drain soul on a target with corruption and nothing happens when drain soul damage ticks.

How it should work: 
Corruption duration should be refreshed on every drain soul tick

Source (you should point out proofs of your report, please give us some source): read the everlasting affliction talent description.

**Comment by Cwiercpasiec** [comment]
Drain Soul shouldn't refresh Corruption on every tick, not even the description of Everlasting Affliction says that, but that's not the point, since as most of us know, tooltip is no evidence. Here is the link to BQL 25 hc played by warlock, you can see that Corruption is refreshed only by the first tick. So actually its a bit bugged, cause on sunwell Corruption is refreshed with the beggining of Drain Soul and should be refreshed with ONLY first tick of Drain Soul. 
https://www.youtube.com/watch?v=MHYRjHUcGI8

**Comment by Kokaina** [comment]
Drain Soul should refresh Corruption with first tick instead of channeling start

**Comment by set-theorist** [comment]
Drain Soul should refresh corruption with channeling start, exactly at 4:49 in the linked video you see channel begin while shadowbolt is flying and corruption was refreshed. 

The reason Cwiercpasiec thought that it was on first tick is because the first tick of the first happened exactly at the same time as the shadowbolt that warlock had casted traveled to and hit the boss. But if you look carefully, the channel start of the first drain soul also refreshed corruption duration.
