### ISSUE TITLE
Damage dont break cc when absorb

### ISSUE THREAD

**Issue by velarmag** [SunwellTracker/issues#2997]
Decription:
Damage dont break cc when absorb

How it works: 
CC like sap, blind, repentance, etc dont break with damage when target have absorb.
How it should work: 
Should brake cc instantly.

Source (you should point out proofs of your report, please give us some source): 
1. BLIND https://www.youtube.com/watch?v=GyEoB_7EzP4&feature=youtu.be
2. REPENTANCE https://www.youtube.com/watch?v=AXU4B0fLsN8&feature=youtu.be
3. SAP https://www.youtube.com/watch?v=pnJkg8WxpyQ
4. SWD https://www.youtube.com/watch?v=zRIU8xubUyQ

**Comment by Shragenator** [comment]
Huge issue.  Definitely needs fixing asap

**Comment by Shragenator** [comment]
Anyone have some definitive proof that break-on-damage CC would break during WOTLK live if the damage is fully absorbed?    I looked through old vids and couldn't find any evidence of this.  
 Also, I remember having /cancelaura macroes for shields on my holy pala and disc so that sac and death would break cc, which indicates that it was NOT breaking on absorbed damage.

**Comment by lastrowy** [comment]
its not fixed, still dont work with scatter shot
