### ISSUE TITLE
Spell Reflect Warrior bug

### ISSUE THREAD

**Issue by yuript** [SunwellTracker/issues#3034]
Hi,

The spell reflect is malfunctioning because the warrior should be able to use "spell reflect" while the spell is moving in mid-air. The way it is working at the moment is wrong because it is only possible to reflect the enemie's spell if you use the "spell reflect" before the enemy cast his spell.

Best Regard's,

**Comment by Rosenkrantz** [comment]
Working as intended.

/rant: sure, because Warriors really do need custom PvP buffs to give them upper hand against any spellcaster. Take your example and think about interaction between Warlock's Death Coil and Spell Reflect, look at both abilities' cooldown and tell me why it would be balanced to counter every 2m cooldown with a 10/9s cooldown. It makes any projectile-based spell useless against Warrior, because they get to choose every time which one hits them.
