### ISSUE TITLE
Shaman: Lava Burst (flame shock crit bug)

### ISSUE THREAD

**Issue by Floow1993** [SunwellTracker/issues#3072]
Decription: 
There is Lava burst crit bug (Usually on private servers), It works when u put flame shock on the target and then cast lava burst, but it dont work when u Cast lava burst and when Lava burst fly to the target u instantly cast Flame shock there is no crit.

How it works: 
When u cast Lava Burst and then flame shock while Lava burst flying there is no crit from lava burst.

How it should work: 
It should crits while flame shock is on target so, better combo is to Lava burst and then instantly use flame shock.

Source (you should point out proofs of your report, please give us some source): 
There is easy to test

**Comment by Vaxsysl** [comment]
In WotLK expansion, casting Lava Burst **requires** you to have Flame Shock active on the target when you **cast it** in order to benefit from 100% crit chance talent. It's not about when the spell lands but when its cast.

So - sorry. Find proof of otherwise for WotLK from legit source to prove it.

**Comment by Floow1993** [comment]
Maybe you are right.  I was playing at global and thought this is a bug

wt., 14 kwi 2020, 10:04 użytkownik Vaxsysl <notifications@github.com>
napisał:
