### ISSUE TITLE
Consecration damage

### ISSUE THREAD

**Issue by akinfenwa10** [SunwellTracker/issues#3098]
Decription: 
Consecration damage reduces to 33 per hit when u pull many mobs like in low level dungeons, 2 days ago it used to hit 253 per target

How it works: 
consecration dealing low damage compared to what it used to be lately, it drops to 33 even

How it should work: 
spell was nerfed or smth, days ago it was dealing way more damage

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/7wzdtDe

**Comment by Afgann** [comment]
Area-of-Effect Damage Caps: We've redesigned the way area damage is capped when hitting many targets. Instead of a hard cap on total damage done, the game now caps the total damage done at a value equal to the damage the spell would do if it hit 10 targets. In other words, if a spell does 1000 damage to each target, it would hit up to 10 targets for 1000 each, but with more than 10 targets, each target would take 10,000 damage divided by the number of targets. 20 targets would be hit for 500 damage each in that example.
https://wowwiki.fandom.com/wiki/Area_damage_caps , patch 3.3
