### ISSUE TITLE
Hand of Freedom won't remove Gouge(Stun)

### ISSUE THREAD

**Issue by Warglaive** [SunwellTracker/issues#3266]
Decription: 
Hand of Freedom won't remove Incapacitated (Stun) caused by **Couge** rogue spell.
https://wotlk.evowow.com/?spell=1776#see-also

How it works: 
Well it simply do NOT remove the Incapacitated stun effect. 

How it should work: 
It should remove the Incapacitated effect caused from **Couge** rogue spell.
**Effect #3 Apply Aura: Stun
Mechanic: Incapacitated**
So I guess it should remove it.

Source (you should point out proofs of your report, please give us some source): 
https://prnt.sc/t516o1
I will try to find a rogue for more clear source, but that is all I have at the moment.

**Comment by Warglaive** [comment]
Okay so, on the first **two** screenshots you can see the rogue stuns me **Gouge** then I cast Hand Of Freedom, but the Gouge remains.

On the last two screenshots you can see that I casted Hand of Freedom, then the rogue stunned me (I should be immune, because of freedom.

**I forgot to state that I also have Divine Purpose talent, which leads me to the thought that the Talent might be bugged as well to some extend.**
https://wotlk.evowow.com/?search=Divine+Purpose
https://prnt.sc/t51f2z

**Comment by Soufly** [comment]
''Hand of freedom can be cast on teammates when you are Cyclone’d, Sapped, and Gouged.  It can be cast upon yourself when you are stunned, but this is best used toward the end of the stun in order to save yourself a global cool down for when you come out of the stun'' - http://web.archive.org/web/20140603215325/http://www.skill-capped.com/content/3790/retribution-paladin-pvp-abilities - 
Yes the info is from cataclysm,but up to MOP there was no changes for the ability.
https://wow.gamepedia.com/Hand_of_Freedom -
Mists of Pandaria Patch 5.0.4 (2012-08-28): Range increased from 30 to 40 yards.
Wrath of the Lich King Patch 3.2.2 (2009-09-22): This ability now correctly removes the snaring component of  [Infected Wounds] and  [Frostfire Bolt].

**Comment by Azathothh** [comment]
> Okay so, on the first **two** screenshots 
> On the last two screenshots
You've posted only 2 screenshots: https://prnt.sc/t516o1, https://prnt.sc/t51f2z
Screenshot from combatlog doesn't show anything, because it's missing timestamps (but that's just info for future reports).

Gouge is not a stun, like you've mentioned in your report this mechanic is called Incapacitated (also DR category for Gouge is Disorient, not Controlled Stun or Random Stun).
