### ISSUE TITLE
Warrior: Hamstring bug

### ISSUE THREAD

**Issue by sunwellplayer** [SunwellTracker/issues#3288]
Decription: Hamstring maims the enemy, reducing movement speed by 50 % for 15 sec.

How it works: Doing pvp hamstring slows the target for 10 sec. regardless if he has or not some  talents for slow reduction time, but in pve works perfectly fine and slows the target for 15 sec.

How it should work: Hamstring should slow the target for 15 sec. unless the player has talent for slow reduction time.

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_070820_171250](https://user-images.githubusercontent.com/68015419/86930785-10ac0c80-c140-11ea-949d-99c347fcbd99.jpg)
![WoWScrnShot_070720_231451](https://user-images.githubusercontent.com/68015419/86930818-1ace0b00-c140-11ea-8540-0413edebd5f9.jpg)

**Comment by Rosenkrantz** [comment]
I'll just throw it here because I can't find a source, but I remember investigating it a few years ago in context of Mage's spell Slow being suspiciously short in PvP - snares have a maximum base duration of 10 seconds in PvP. Think of it like Polymorph or Sap. You don't really expect to Poly someone for 50s, it only works for 10s, but it's never written in the game that it works like that.

Got some kind of source before I finished writing:
https://wow.gamepedia.com/Crowd_control
Though I'm aware that this could be from after WotLK, I'll keep searching for a bit.

**Comment by sunwellplayer** [comment]
Works normal it seems from further research
