### ISSUE TITLE
PVP Combat Bug

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#3312]
Decription: Problems with Combat in PVP. 

How it works: Player A enters Combat. Player B heals Player A. Player B **does not** get in combat. 

How it should work: Player B should get into combat by healing Player A that is in combat. Healing/buffing/dispeling on a player who is in combat should give you combat-tag. 

Source (you should point out proofs of your report, please give us some source): Any pvper knows this is how it should work (mostly if you played any healer vs a rogue)

**Comment by Shragenator** [comment]
Really important fix to get out, makes rogues super broken if they know how to abuse this

**Comment by Shragenator** [comment]
I just tested this in a skirmish and it is definitely not fixed. 

[https://imgur.com/a/KQjNUuZ](url)

In this screenshot my warlock is spamming shadowbolt on the enemy while I heal him then I am able to immediately drink

**Comment by Shragenator** [comment]
From what I can see, it might SEEM fixed because in some situations it works.  I have noticed in battlegrounds that is Player A is attacking Player B (the attacking causes player A to enter into combat), if I heal player A then I do not necessarily enter into combat if they aren't hit.   Might have something to do with that
