### ISSUE TITLE
[Mage] Invisibility bug

### ISSUE THREAD

**Issue by lowbur** [SunwellTracker/issues#333]
Decription: When a Mage pops invisiblity, he/she becomes un-stunnable and un-slowable. They should not be immune to stuns and slows while they are fading away.

How it works: https://db.darkwizard.pl/?spell=66      Here is the description for invisiblity. No where does it say you become immune to stuns and slows when fading.

How it should work:  Mages should still be stunnable/slowable while fading away.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?spell=66

**Comment by Cwiercpasiec** [comment]
What spell were the mage exactly immune to?

Just tested it on Feronis on my frost mage lvl 80. Chains of Ice did slow me during the buff (I tried throwing Chains before using Invi and after using Invi, always slowed me), same goes for Crippling poison. I wasn't immune to stuns either (tried Cheap Shot and Kidney Shot, casted both after using Invisibility, during Invisibility buff). Are you sure mage wasn't on immune to stuns because of diminishing returns or Free Action Potion for example?

**Comment by lowbur** [comment]
This is on Angrathar, we tested it in a duel, intercept was the spell used.

**Comment by Azathothh** [comment]
Stuns/slows working without problem on mage fading into invisibility.
