### ISSUE TITLE
Who list always shows current online players

### ISSUE THREAD

**Issue by Eksekk** [SunwellTracker/issues#3335]
Decription: Who list doesn't work correctly, while it shows normal list of players, the amount is calculated incorrectly (always as 50 shown from [current fraction online]).

How it works: See above.

How it should work: Amount should be [displayed player amount] from [players matched by query].

Source (you should point out proofs of your report, please give us some source): Just take a look ingame.

**Comment by Azathothh** [comment]
Hello. It's not showing "current online players" number _.server info_ does show that. This number in /who is something else and it's done like that on purpose to help the faction balance stay on healthy level. It's 55% / 45% now and it's perfectly fine, but many new players seeing this would chose horde EVEN if they wanted to play ally - that's why faction ratio isn't displayed, so players don't make a choice based on it, but rather play what they want.
