### ISSUE TITLE
Hand of Protection not instantly reset aggro

### ISSUE THREAD

**Issue by snaplife** [SunwellTracker/issues#3428]
Decription: 
when I use hop it doesn't immediately reduce its aggro

How it works: 
when using hoop on a target its numeric value of treath is not instantly dropped to zero

How it should work: 
when using hop a target's treath drops to zero instantly, even if it uses the macro to remove the aura,
an example :
target has 90% treath use hop drops to zero

currently this effect does not occur

but this happens

target has 90% treath, I use hop and stays at 90% treath, same thing if you use macro to remove aura

target 90% treath use hop, target use macro to remove aura effect, stay at 90%.

The effect is applied when using the ability instantly after, the effect of the ability is also applied with the macro to remove the aura with its effects

Source (you should point out proofs of your report, please give us some source):

**Comment by Platinumcoated** [comment]
You have any source to prove your statement?

As far as I know it shouldn't do anything to threat, it simply makes you immune to physical damage, making mobs turn on somebody else for the duration

**Comment by snaplife** [comment]
I did it several times even in dungeons, apply the divine shield debuff, sometimes it works and sometimes it doesn't, I don't know how I can prove it with evidence because it is something very difficult to show, we talk about programming code, the the only introduction that comes to me is playing with a paladin and making df together and try to see this interaction too

**Comment by Platinumcoated** [comment]
You're supposed to provide a source proving that the ability worked the way you describe on retail WotLK.

https://wowwiki.fandom.com/wiki/Hand_of_Protection?oldid=2232036

"Tips & Tricks
  ( ... )
Players protected lose aggro while under its duration. Tanking paladins can use this as a last resort method of aggro management, or because of a player's inability to perform melee actions through the shield, an effective way to reign in a melee dps class who is unable to control their own aggro. The threat reduction only lasts for the duration of the hand however, so a tanking paladin needs to make sure they are able to generate enough threat to keep aggro when the hand expires."

it doesn't modify threat, it only makes you drop aggro

**Comment by snaplife** [comment]
exactly, you found it, in fact in the ticket I explained this

**Comment by Azathothh** [comment]
It works exactly as it should - if you think otherwise please provide some proofs (link to wowwiki posted by Platinumcoated confirms that your report is incorrect)
