### ISSUE TITLE
Libram of Truth is decreasing armor instead of Increasing

### ISSUE THREAD

**Issue by Zoiaum** [SunwellTracker/issues#3485]
Decription: 
The item Libram of Truth https://db.darkwizard.pl?item=22400 is actually decreasing the armor stats instead of Increases by 110.

How it works: 
The Libram is decreasing the armor value while using the devotion aura by 110

How it should work: 
The Libram should increase the armor value while using the devotion aura by 110

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_030321_214114](https://user-images.githubusercontent.com/80013947/109892403-3fe03280-7c69-11eb-9f62-3c83e43d212a.jpg)

![WoWScrnShot_030321_214159](https://user-images.githubusercontent.com/80013947/109892635-51293f00-7c69-11eb-9429-26c9acc3a1c2.jpg)

![WoWScrnShot_030321_214224](https://user-images.githubusercontent.com/80013947/109892816-669e6900-7c69-11eb-9f37-a07689c77352.jpg)

**Comment by Azathothh** [comment]
This is not true - it does increase armor by 110 like it should.
Please look at your armor value(on character tab, below spirit) without the libram and then equip libram (make sure that you have devotion aura active). You will see that it's increased by 110.

If you're looking at the tooltip in your buffs - it won't change, because that's how wotlk client is made, and it was like that on retails as well. We can't change that without changing the client.
