### ISSUE TITLE
[Druid] Flight Form Trajectory and velocity issues.

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#352]
Decription: As most druid players know, when you are flying and then you shapeshift (out of flight form) you keep your velocity and trajectory. Currently, you just drop down as a solid rock when you shapeshift out of flight form, without keeping your trajectory and velocity.
This is a really major issue because it limits your movements mid-air as a druid, which should never happen.

How it works: Currently you drop down as a rock, you lose all of your momentum, all of your velocity and your trajectory goes to the ground.

How it should work: When you shapeshift mid-air you keep your trajectory and your velocity in the same direction that you were faced.

Source (you should point out proofs of your report, please give us some source): 
I can provide a video with further proofs of how it works/ and how it should work if needed.
But i think it won't be needed, can just be tested by getting a druid with flight form.

**Comment by Cwiercpasiec** [comment]
If you can provide source video, then do so. But don't forget, that it should be from WotLK.

**Comment by Avarishd** [comment]
bump, here is a picture that explains it:
https://gyazo.com/a31fe606112137f93cca0806d8165621

**Comment by Afgann** [comment]
That's not a proof.

**Comment by Avarishd** [comment]
https://youtu.be/cGrGEfDh15w It shows how it WORK NOW and how it SHOULD WORK.

**Comment by Bliste** [comment]
I played druid during retail (tbc+wotlk relevant) and several private servers - it occured only two times that i lost momentum during shapeshift - on a private server called lordaeron which was a bug that was fixed after 1 day and on this server. Avarishd is right about the issue and the linked video shows how its supposed to work.

**Comment by Afgann** [comment]
I still don't see any retail evidence.

**Comment by Avarishd** [comment]
@Afgann Retail evidence? LK was released November 13, 2008, cata was released December 7, 2010. Will be hard for me to travel time back to LK on retail and record some "evidence". This bug is literally making druids a wheelchair class when it comes to world farming/pvp. I've provided enough "evidence" for a specific bug which has been here since the beginning of the realm and it has been annoying ever since.

**Comment by Afgann** [comment]
It doesn't mean that you need to go back in time and record it. All "evidence" that you provided is your images/videos and that means nothing.

**Comment by Avarishd** [comment]
@Afgann https://www.youtube.com/watch?v=Q_zJLDE1-sk You are welcome :^) Hope it gets fixed now. 
Published on Aug 21, 2010

**Comment by ice-92** [comment]
Can also confirm that you're definitely not supposed to fall down like a rock. I'm sure pretty much every druid who has played the game for a while can also confirm.

**Comment by Avarishd** [comment]
@Afgann added **bug**  labels on Feb 13 
Any information about this? It has been some time

**Comment by M0dinstaller** [comment]
Can this get fixed ? A server more than one year old with such a big class bug does not encourage druids who make it to 60 to keep playing. At this point in the game any druid is really looking forward to his flight form, and still relatively new enough to the server that they'd consider switching to another one where the bug was fixed.
