### ISSUE TITLE
[Item] Flask of the North

### ISSUE THREAD

**Issue by Shaquiloheal** [SunwellTracker/issues#3563]
Decription: I think this flask working wrong. Rolling random stat but i used this item about 50 times today and get only spell power or str (as feral druid with items for feral). I just cant get AP buff. If you want check it write to im in game (the same nick) and we can make test for proof.

How it works:  Rolling random buff but only spell power or str.

How it should work: Should give one stat from three (sp, ap or str)

Source (you should point out proofs of your report, please give us some source):  https://www.wowhead.com/item=47499/flask-of-the-north#comments:id=798521

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/112393992-3b54ea00-8cfc-11eb-92b4-69b6e184c1fe.png)
^ This is the comment that you've linked, it says that druids can get STR or SP, so i'm not sure where are you getting part about AP from.
Also keep in mind that 1str is better than 2ap for druids, so i'm not sure why you want to get AP buff instead of STR.

Everything is working fine with it.
