### ISSUE TITLE
Judgement Day Comes!

### ISSUE THREAD

**Issue by Kalysia** [SunwellTracker/issues#386]
Decription: 
The Quest Judgement Day Comes! http://wowwiki.wikia.com/wiki/Quest:Judgment_Day_Comes!

How it works: 
Fly to Tirion in Argent Venguard and speak to him

How it should work: 
When I fly to Argent Venguard Tirion doesnt stand there. When i Fly to Tirion in Crusader Pinnance I cant talk to him for this quest

**Comment by Dootz** [comment]
according to to wowhead comments (http://www.wowhead.com/quest=13227/judgment-day-comes#comments) that's intended behaviour that you can't complete it once you progressed in quest chain. Bug then you shouldn't be able to pick up this quest. It'll be fixed so that you can't pick up this quest once you started Argent Vanguard chain.

**Comment by Kokaina** [comment]
Fixed.

**Comment by Kokaina** [comment]
Fixed.
