### ISSUE TITLE
Ghoul Leap ability is bugged, jumps randomly at party members or even master

### ISSUE THREAD

**Issue by Vidia2** [SunwellTracker/issues#389]
UPDATE: it seems there is a problem with ghoul since it jumps back to me too. Basically Leap is useless.

Decription: 
While in a fight, the ghoul constantly jumps at party members and leave the target he is assigned on.

How it works: 
The ghoul leaves his target and jumps at party members or other places

How it should work: 
The ghoul should never jump and leave his target, unless ordered to

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
Simply turn off auto cast on Leap (https://db.darkwizard.pl/?spell=47482). Your ghoul jumps on random party members, because it is to close to it's target. Not a bug.

**Comment by Vidia2** [comment]
excuse me ? why would I ditch a perfectly usefull spell just because of bad coding ? I signaled a bug, I expect it to be looked into, not band-aid fixed with "turn the skill off". Obviously there is something wrong with it since it jumps without me changing target, which shouldn't ever happen, no matter the cirscumstances.

**Comment by Afgann** [comment]
He meant turning off auto casting of this spell.

**Comment by Vidia2** [comment]
I know but thing is, the leap spell doesn't work correctly so I don't think turning autocast off will help much.

**Comment by Afgann** [comment]
It still makes saying that leap is useless a big exaggeration, it works fine without autocast.

**Comment by Vidia2** [comment]
Honestly, the whole purpose of Leap is for your pet to close the distance to something you want stuned. And if you can't do this in a reliable way because you don't know if the skill is going to be correctly 
this is not reliable and you don't know if the pet will Leap correctly or not, it's pretty much useless. 

Leap without autocast is overkill, I was 3 times glad in wotlk retail and never heard of anyone who used Leap this way. Maybe I am not skilled enough but well...

**Comment by winNixz** [comment]
It's not an intended behaviour that the pet autocasts Leap on friendly targets, it should never cast Leap on friendly targets by itself. This is a problem for PvP and PvE aswell, the main purpose of Leap in PvP is to Leap onto the focus target for Gnaw, in PvE its main purpose is to close the gap between mobs and the ghoul, much like warriors using charge. Turning off autocast on Leap doesn't help this really, since it's just way too tedious to cast this manually.

My current workaround is a macro like : /cast Gnaw /cast Leap for PvP
and a macro like : /petattack /cast Leap for PvE
This is still suboptimal since I won't spam petattack in PvE and will miss out on damage from this.

Proof isn't really necessary, just look at any kind of wrath dk video and look for ghouls jumping around in a fight... you won't find any.

**Comment by Vidia2** [comment]
word, totally agreed. he who said "put it with autocast off" clearly doesn't play a dk as main. Bottom line, we need this fixed asap.

**Comment by tekarsis** [comment]
I can confirm, I'm having this issue too; two times i ninja pulled groups of mobs without intending too and leap disabled. Ghoul goes where it wants
