### ISSUE TITLE
[SPELL] Shadowmeld

### ISSUE THREAD

**Issue by Aqua1234** [SunwellTracker/issues#39]
Decription: 
Umiejetność Night Elfów [Shadowmeld](http://www.wowhead.com/spell=58984/shadowmeld) powoduje utracenie combatu w trakcie walki w przypadku zaatakowania wroga przez dwie lub wiecej osoby. 

How it works: 
Zakladamy, ze sa dwie osoby ktore maja combat od tego samego wroga.  Osoba A, ktora ma na sobie agroo przeciwnika uzywa raciala, w tym momencie traci ona agroo, co jest poprawne, ale rowniez **traci combat**. Przeciwnik przechodzi na osobe B. W momencie gdy osoba B uzyje Shadowmeld **gubi combat**, a przeciwnik powraca do osoby A.

How it should work: 
Zgodnie z opisem skilla: " Activate to slip into the shadows, reducing the chance for enemies to detect your presence. Lasts until cancelled or upon moving. Any threat is restored versus enemies **still in combat** upon cancellation of this effect. " osoba nie powinna tracic combat. 

Tracenie combat powoduje resetowanie cooldown'u z potionow i umozliwia jego kolejne uzycie podczas walki. Moze to pomagac niektorym klasom na nadchodzacym progressie ICC.

Source (you should point out proofs of your report, please give us some source): 
[Shadowmeld](http://www.wowhead.com/spell=58984/shadowmeld)
[Shadowmeld](https://wotlk.evowow.com/?spell=58984)

**Comment by sitowsky** [comment]
http://www.wowhead.com/spell=58984/shadowmeld#comments

Warriors can leave combat to charge again; rogues have an extra vanish; hunters have an extra feign death (and the enemy can't simply retarget you, he have to AoE you out of stealth); all healers have a VERY powerfull tool (since they can make enemies loose target before starting a heal).

Komentarzy znajdziesz tam wiele, sporo z czasów WotLK. Odnośnie przywracania threat, tyczy się to wyłącznie encounterów - patrz screenshot shadowmeld z combatem.
![wowscrnshot_020218_070334](https://user-images.githubusercontent.com/35101706/35718976-3f45c6ea-07e7-11e8-86a2-73359f621560.jpg)
