### ISSUE TITLE
Hot and Cold

### ISSUE THREAD

**Issue by ivanlink** [SunwellTracker/issues#591]
Decription:  Im reporting this as an issue because there are alot of mobs missing .

How it works:  So I know its not a big issue but it is for me and it's really frustrating since that area in retail is crowded with "Brittle Revenant" mobs but there are only 5 or 6 spwning every 5 minutes or so ... also the drop rate is really low and makes this quest a pain in the ass to complete if you want to grind reputation for Sons of Hodir. 

How it should work:  The area should be crowded with "Brittle Revenant" and make the quest easier to complete for everybody.

Thanks.

**Comment by bongobg** [comment]
Here is so more acurate data: http://sunwell-community.com/index.php?/topic/628-rediculously-slow-spawn-rates/&tab=comments#comment-2957

http://www.wowhead.com/npc=30160 - a lot more spawns, loot table incomplete, drop % has to be increased as well
Video from the appropriate patch: https://www.youtube.com/watch?v=IFpjc-pQ0UM
Since patch 3.3.0 the elements should not cast Shield Bash and the drop chance of the Q item should be 100%.

http://wowwiki.wikia.com/wiki/Brittle_Revenant

**Comment by Dootz** [comment]
Will be fixed with next update
