### ISSUE TITLE
[Druid] Activating Cat Form replaces tracking of Low Level Quest with Track Humanoids

### ISSUE THREAD

**Issue by dmoelgaard** [SunwellTracker/issues#656]
Decription: 

Whenever I shape into cat form as a female night-elf druid, it changes my current tracking to Track Humanoids despite already tracking another item, specifically Low Level Quests. This only happens when I change into cat form, and no other forms are affected by this.

Bonus: Exiting Cat Form disables all tracking, including Low Level Quests.
 
How it works: 

Assuming the druid has learned Track Humanoids and Cat Form. The problem has also been replicated without any addons loaded.

1: select tracking Low Level Quests at your minimap.
2: change your shape into Cat Form.
3: current tracking should now be Track Humanoids.

How it should work: 

1: select tracking Low Level Quests at your minimap.
2: change your shape into Cat Form.
3: current tracking should now be Low Level Quests.

Source (you should point out proofs of your report, please give us some source): 

Please view the following album: https://imgur.com/a/iAKY6?

In addition, I was in contact with GM Nadiir, who was able to replicate the problem.

**Comment by bongobg** [comment]
Ok I also play feral druid and I think the case is not exactly like you explain it. I don't think there is an bug at all actually. First of all - Track Humanoids spell is only available on Cat Form, you can't use it on other forms as you mentioned in your report. Therefore comes the 'issue': by default your character doesn't track anything but when you switch to cat form you gain this tracking active automatically. If you track something else though while in no form or bear form (mining, herbs or something else) this will not change when activating cat form. I know that because I'm a miner and usually stay on Track Minerals which does't not change when switching forms. Same for tracking flight masters. Probably the bug more about tracking low level quests.

Please do not try to fix this unless 100% sure there is an actual bug involved.

**Comment by Avarishd** [comment]
Not a bug:
http://www.wowhead.com/spell=5225/track-humanoids#comments
By Rlnshadow (2,490 – 9·30) on 2007/04/08 (Patch 2.0.12)
"It now autocasts when you enter Cat Form, unless you're already tracking something else."
(There are no changelogs about this ability from:
Patch 0.10 (2004-09-18): Now lasts until canceled, like other tracking abilities.  **to** Patch 6.0.2

**Comment by dmoelgaard** [comment]
The pictures show tracking of Low Level Quests which gets replaced by Track Humanoids. So if the correct behaviour is for the tracking to not change if an item is already tracked, then there is a bug present, relating to the tracking of Low Level Quests and Cat Form.

I will edit the ticket now to reflect the proper aim of the ticket.

**Comment by bongobg** [comment]
Ok, I confirm the bug. I just tested it. I works only for gathering tracking skills like minerals. Changing tracking to something default and cat form replace it with track humanoids. All of the blizzard's default tracking get replaced.

**Comment by Dootz** [comment]
http://www.wowhead.com/spell=5225/track-humanoids#comments
> Ninoa on 2008/11/29 (Patch 3.0.3)
> As mentioned below, this skill will override tracking of non-profession tracking options. I'll keep my vein tracking and fish tracking, but it'll override, for example, my low level quest tracking if I shift to Cat Form. Highly annoying if you're trying to finish low level quests for achievements and such.
