### ISSUE TITLE
Titans Grip and talent trees as a whole

### ISSUE THREAD

**Issue by Dolice1990** [SunwellTracker/issues#714]
Decription: since the patch on the server is ment to be Pre 3.1.0 so somewhere in the range of 3.0.2 to 3.0.9 the whole talent trees are fucked including Titans Grip

**If i get this closed and say it's intended at least confirm what patch the server is running on because at the moment it defiantly is Patch 3.3.5a and you've ghetto closed all dungeons and raids that aren't supposed to be available yet *cough* ICC *cough* FoS / PoS / HoR *cough* Ulduar *cough* ToC**

it's not only me that's suffering it's other classes too

How it works: Currently we are using patch 3.3.0 - 3.3.5 talent trees which results in Titans Grip being Nerfed to Minus 10% damage decrease in the Prepatch - Beta / Release of 3.0.2 Titans Grip Had Minus 10% hit rating,  then changed to 5% penalty of hit, then removed to no penalty, then the 10% nerf were seeing now

How it should work: if it is before Patch 3.1.0 which it's supposed to be because Ulduar isn't out yet then it should be either no penalty at all 10% miss chance or 5% miss chance this wouldn't normally be a problem but fury warrior are getting fucked over in the ass because were doing low dps because of this 10% nerf which was to balance fury warriors for the Ulduar patch in which the minus 10% damage nerf was compensated for the better Ulduar gear we are playing with a 10% nerf in content that doesn't give us enough gear in order to compensate for the damage loss

Source (you should point out proofs of your report, please give us some source):  http://wowwiki.wikia.com/wiki/Titan%27s_Grip
http://wowwiki.wikia.com/wiki/Patch_3.0.2
http://wowwiki.wikia.com/wiki/Patch_3.0.3
http://wowwiki.wikia.com/wiki/Patch_3.0.8
http://wowwiki.wikia.com/wiki/Patch_3.1.0
https://wow.gamepedia.com/Patches/3.x

**Comment by ujellyx** [comment]
This server is meant to be on a earlier patch content-wise, not mechanic-wise.

**Comment by Dolice1990** [comment]
retarded if u ask me, they've just ghetto closed every non content dungeon / raid and called it a progression server

**Comment by ujellyx** [comment]
Not really retarded. Just think of the amount of work people would need to put into getting every mechanic on every "patch"-progression the way it was on retail.
It would also require you to have a client of each WotLk-version ready to play.
It's handled this way on every progression server.

**Comment by Dolice1990** [comment]
it is retarded, why call it a progression server when it isn't really and then to have the audacity to call it blizzlike when it isn't either and nobody said making a private server was easy if they wanted to take the easy way out and just download any old trinity core repack on google, host it close all non content dungeons then why bother in the first place if your going to do it at all, do it properly, what's going to happen when ICC comes out if they have this attitude are we going to have the instant 30% buff inside ICC on release or what?

**Comment by ihcTactics** [comment]
This is how the majority of all private servers work. There are literally only a handful that do it otherwise. Light's Hope, Elysium, Kronos, etc all work the same as this server. It's not lazy, it's literally not feasible to start on an early patch and progress not just through content but through the mechanics as well.

If that were the case, every time new content was released, not only would the content have to be checked, but all patch updates as well affecting mechanics, many of which went listed, but enough of which didn't. This is a whole extra world of effort that would be required by the dev team to implement.

Also, and more importantly, it would require there to be CLIENT distrubutions of EACH AND EVERY patch. We are using the 3.3.5 client. Just like 99% of vanilla servers use the 1.12.1 and TBC uses 2.4.3. So a clean client of every patch would not only have to be found (many of which don't exists anymore publicly), but they would then have to be distributed to the THOUSANDS of players on this realm every time we hit new content/patch update. So either every time we'd have to download an entirely new client (or just the data files), or they'd have to be able to implement a patch update system into the current client, which is more custom scripting.

I'm not sure if you're new to the private scene, or just have an insane sense of entitlement, but I think you need to realize the effort that already goes into these private servers and how over the top your request is.

**Comment by Dolice1990** [comment]
i'm hardly new to the private server scene having played private servers for 14 years on and off over those years so id say around 12 years of actual play time and if you anything about SQL scripting at all and modifying the database it isn't as hard as you think you can run the game on a patch 3.3.5 client and have older patch content in the database without players having to download anything extra your just modifying spell values in the database my point is it is doable i bet if another talent was completely broken and unusable it would get fixed in a heartbeat more or less but because of this 10% nerf every Fury warrior is not viable in Naxxramas not to mention that Death Knight have it made since Death Knights on Release did 30% more damage than any other class untill ToC, with the current talent setup they do 50% more damage than any other class untill ToC

**Comment by ihcTactics** [comment]
http://wowwiki.wikia.com/wiki/Timeline_(World_of_Warcraft)
So I assume you mean non-wow private servers.

And if you've been playing them that long, then you'd know that this is common place and you wouldn't have posed your original question as if it was a mystery that we're running 3.3.5 mechanics with 3.0.9 content ( or somewhere between 3.0.2 and 3.0.9).

So ultimately what you're requesting is that this server switch to a full retail like progression, mechanics and content. And that negates your original comment about Titan's Grip since it's not a bug with current mechanics.

If you want that level of content creation (because it is creation, they have to re-do hundreds of values across all the patches), then I suggest you make a suggestion post on their forums. And since you seem to have the skills, I would offer to help out since it's something you seem to heavily desire.

**Comment by Dolice1990** [comment]
to be quite blunt and to the point i'm just salty nobody wants a Fury Warrior untill ICC because there dps is too low and i enjoy the playstyle of the class too much to simply swap to another class, Fury Warrior is my go-to class on any wotlk server and i've played Fury warrior for most of wotlk on retail when it was relevant and on various servers so around 8 or 9 years i know from my experience that they do Blow untill ICC but now because of this 10% nerf a few patches early then they Blow even harder maybe i wen't off the rails a bit whining but nobody likes being refused to a raid through no fault of your own because your doing low dps and i'm pretty certain i'm hitting the most damage i can at my gear level just because i play it perfectly
