### ISSUE TITLE
explosive trap hunter

### ISSUE THREAD

**Issue by rocketfuell** [SunwellTracker/issues#732]
Decription: with glyph of explosive trap

How it works: crit rating based on spell crit 20 - 30%

How it should work: should be based on physical crit as for example serpent sting with t9 is

Source (you should point out proofs of your report, please give us some source): spoke to GM from blizzard

**Comment by Soufly** [comment]
I agree,the crit chance should based on ranged critical strike,not on spell.With average of 50% crit ,my glyphed explosive trap barely crits. Prove: https://imgur.com/a/hNsPk .

**Comment by knasen88** [comment]
How is that proof, you don't show other abilites having same %crit. And why don't you just link the worldoflogs in question instead of making a bad paint image where you scratch with the smallest eraser you could possibly find

If you want it fixed provide retail source of explosive crit% being the same as their auto-shot or something.

**Comment by Soufly** [comment]
U can easily see how many times auto shot hit/crit and own calculation.

**Comment by knasen88** [comment]
You obviously don't understand what source in this context means

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
