### ISSUE TITLE
Warlock Voidwalker Sacrifice Shield In Arena

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#834]
Decription: In arena before the gate opens you can summon a voidwalker and use its sacrifice ability to grant yourself a shield that will last for 30 secs. Then you can summon another pet before the gates are open.

How it works: You summon voidwalker to get a shield then have your shield removed as the arena starts.

How it should work: You should be able to keep your shield for the duration of it instead of it being removed when the arena starts. Its the same as a priest using a shield or a mage the only difference is I need the pet to do it.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Sacrifice_(voidwalker_ability)

**Comment by ujellyx** [comment]
"After 60 seconds of preparation, the match commences. All buffs with fewer than 30 seconds remaining are removed and rage/runic power is reset to 0."
https://wow.gamepedia.com/Arena

so it's working as intended.

**Comment by moonsado** [comment]
http://www.blizzardguides.com/warlock_tips.html

From WOTLK:
"Voidwalker Sacrifice ---> First off, you make your partner a Healthstone, do Detect Magic, Underwater Breathing and all of that stuff, summon an Imp, put a fire shield on both of you, and then summon a Voidwalker. When the timer hits 11 seconds, summon a Felhunter, and start mass clicking Sacrifice. Right before the Fulhunter comes out, your Voidwalker should Sacrifice itself."
So by this guide the lock gets a voidshield before arena starts.

From vanilla:
"* Regarding sacrifice void before arena start. Summon your void, when time is short you can start summon the demon you want, and SPAMM click sacrifice, when you summoned demon its about 0,5 sec before it gets up so you can sacrifice exactly at the point before you get your new pet. Whollaa 30 sec shield."

**Comment by ujellyx** [comment]
Yeah, this means you have to hit the sacrifice button so that it's activated right after the preparation-time is over so that you can keep the buff and summon a new pet (e.g. Felhunter) about 1 second into the match. You just have to time it right. When you sacrifice during the preparation-time the buff fades, which is correct.

**Comment by moonsado** [comment]
She is stunned for only 3-4secs and my cast time is 5.4secs for new pet.

**Comment by ujellyx** [comment]
Then just time it right? Start the summoning of a new pet at around 5 seconds before the game starts and then use sacrifice right before the next pet goes off and after the gates open?

**Comment by moonsado** [comment]
I will try that next time yeah BUT if I see it doesn't work ill be back here.

**Comment by set-theorist** [comment]
Your link is from TBC (wotlk was released november 13 2008). I also found this other link from TBC:
http://www.arenajunkies.com/topic/23087-what-are-you-doing-before-a-match-starts/page-2
"[...]
Make sure I'm in the gear I'm supposed to be
Summon Voidwalker
Create Soulstone
[...]"

On top of that, if you check videos from popular pvp players (not sure about that hadouken guy since he just ever released BG movies as far as i know), you will see that none of them used voidshield before arena start, even when the benefits would be huge: 

https://youtu.be/buLNkD4uw0o?t=1m37s

I cannot think of any reason why warlock here wouldn't have void shielded before match start and then swapped to felhunter vs the shaman rogue. Would have given him a huge advantage instead of his voidwalker that did nothing most of the game.

Unless you could find some evidence from actual wotlk I'd be tempted to say that void shield fading on arena start is working as intended (the <60 second buff rule for arenas was added in wotlk).
