### ISSUE TITLE
[Paladin] Divine Sacrifice TALENT

### ISSUE THREAD

**Issue by Kenaowar** [SunwellTracker/issues#888]
Description: 30% of all damage taken by party members redirected to the Paladin

How it works: On sunwell, that buff can be dispellable (actually the only server i've seen that)

How it should work: It shouldn't be dispellable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
If found this on wowwiki
http://wowwiki.wikia.com/wiki/Divine_Sacrifice
> Wrath-Logo-Small Patch 3.1.2 (2009-05-19):
Damage done to the Paladin while this is active will no longer cause the effect to break early, and if it is **dispelled** or canceled early, the damage counter will reset correctly the next time the spell is cast.

So perhaps it could be dispelled. I'm not Paladin expert and small patch note is not enough proof, but so is statement  

> (actually the only server i've seen that)

thus more data is required.

**Comment by Semper-Numquam** [comment]
The addon "Dispel Border" shows that the damage redirection can be dispelled, but not the damage reduction effect (from the improved talent). It even has "Magic" on the tooltip, like all dispellable buffs.

**Comment by Kenaowar** [comment]
Give me a single video on Retail when someone got divine sacrifice dispell'd, i never seen such things.
And on AT you couldn't dispell that spell, and nobody ever reported it as a bug.

**Comment by Semper-Numquam** [comment]
Dootz just quoted a patchnote that implies it can be dispelled. It's up to you to PROVE it cannot be dispelled via any source.

**Comment by Kenaowar** [comment]
http://www.warcraftmovies.com/movieview.php?id=160761
At 3min30 they spam dispell the warrior that have divine sacrifice, they can get only the sacred shield.
Means Divine Sacrifice can't be dispelled

**Comment by Kenaowar** [comment]
http://www.warcraftmovies.com/movieview.php?id=183377
At 17min46, Hydra, who was the best priest back in time, couldn't dispell the divine sacrifice. Let me guess why ? Oh yeah, you can't dispell it.

**Comment by ujellyx** [comment]
The ability is split into two different buffs.
The damage redirection-part is dispellable as it should be - you can even see one of the two parts of the buff is removed in above Hydra movie. The damage-reduction-part however can't be dispelled.

**Comment by Kenaowar** [comment]
Are you stupid ? There is 1 buff duration which is 6sec and the other is 10sec, OFC one of the two parts is removed before the other one is finished, check again before you comment like that. 
If you have no clue how a spell work, don't write on a bugtracker, ty.

**Comment by Kenaowar** [comment]
http://www.arenajunkies.com/topic/67687-divine-sacrifice-is-shit/
As they saying on this thread, divine sacrifice is remove only when the paladin get cloned (only for the duration of the clone obviously)

**Comment by Semper-Numquam** [comment]
Let's see:

1-The fact that he did not dispel it in that video doesn't mean it is not dispellable. You can see Hydra was applying DoTs, popping fiend and even casting PW:S and Holy Fire in that very timeframe, aiming for the kill. That's more than enough time for the buff to fade without casting a single dispel. This video is insufficient.

2-The post about Clone doesn't mean it's dispelled. It means cancelled because Clone cancels alls casts from-toward that target. The same happens with Soul Link from warlocks to their pets, which gets removed on clone but doesn't mean it is dispelable. This is just poor wording from the people comenting.

3-If you mouseover the aura from Divine Sacrifice, you can see the damage redirection has a nice MAGIC in the tooltip, particular to any dispelable buff. The Divine Protection (the dmg reduction) doesn't have that in it's tooltip and thus cannot be dispelled.

4-If it cannot be dispelled, you can find a source where it states "it cannot be dispelled", be it patchnotes or a post confirming this instead of asking. Dootz above linked a patchnote that implies it can be dispelled AND removed early, meaning these are two different things and both can happen.

5-There are addons based in 3.3.5a client that confirm this can be dispelled. I use one myself, DispelBorder. This one shows a nice border on dispellable buffs and includes Divine Sacrifice among the dispellable auras, while divine protection is not included.

6-As a rule of thumb, all buffs with "Magic" on their buff tooltip can be dispelled. Blizz pretty much removed this from the auras that can't be dispelled. Even Ice Block and Divine Shield, which are inmunities and require special dispels include this on their buffs.

**Comment by Kenaowar** [comment]
Tell me why he dispell sacred shield and not divine sacrifice then ? It's a rank1 player, and sacrifice redirect 30% of the dmg which is huge.
On Arena-Tournament, you couldn't dispell sacrifice divine EVER, and nobody, either Hydra, Raiku, Flyn ever complained about it.
Give me a single, A SINGLE VIDEO where someone dispell divine sacrifice please to justify everything you writing

**Comment by Afgann** [comment]
But it's up to you to prove it.

**Comment by Semper-Numquam** [comment]
All I can see is that in video he uses many GCDs not dispelling, but using offensive spells. It could be RNG resist too. One video where something is not dispelled doesn't prove anything and the patchnote says clearly it can be dispelled. Game mechanics support this theory too.

**Comment by Kenaowar** [comment]
How can i prove that someone can't dispell Divine Sacrifice ? Since NOBODY EVER DISPELLED IT ON RETAIL ???????
If he used others spells than dispell it's maybe because it can't be dispelled ? Use your brain just a second.

**Comment by Semper-Numquam** [comment]
Wrath-Logo-Small Patch 3.1.2 (2009-05-19): Damage done to the Paladin while this is active will no longer cause the effect to break early, and if it is >dispelled< or canceled early, the damage counter will reset correctly the next time the spell is cast.

Clone doesn't mean dispel. I already mentioned Soul Link as an example of a spell (which does pretty much the same as DS) that's cancelled when cloned but that doesn't imply it's dispelable. It's poor wording on the post.

On videos you can see priest doing other stuff than dispelling when sacrifice is up. Why? Because sometimes dispel is not better than doing damage and going for the kill.

Finally, the spell tooltip says it's Magic and all spells and auras with "Magic" can be dispelled. The improved talent doesn't say it's magic and thus it cannot be dispelled.

The proof that it can be dispelled is the PATCHNOTE OF THE GAME DEVELOPERS that say it can be dispelled. DISPELLED means DISPEL. It is not a word used to reference Cyclone inmunity.

**Comment by Kenaowar** [comment]
Explain to me why the priest can't dispell the Divine Sacrifice in the video then ?

**Comment by Semper-Numquam** [comment]
@9:50 I am seeing the video, and I'm clearly noticing things you aren't. For example, in the window that paladin is there using Divine Sacrifice, you can see the priest using, in this order: 
Flash Heal -> Binding Heal -> Mending -> PW:S -> Penance all this time targetting rogue, if you can see his target bars.

You don't see him target warrior, priest or paladin at all during the time frame of 9:50 to 9:59, where he switches to enemy priest (and dispels mending on priest) and then to palading to try and dispel Divine Plea.

Yes, I am watching video. Closely. The paladin by this time only has about 1 second left in Divine Sacrifice, and it ends @the time he gets the Mending and RF dispel messages, giving no time to dispel it.

@10:33. You can see priest going offensive instead of dispelling so that's why he doesn't even try to remove the plea. Stop thinking dispelling is a prio every single time as a priest.

Btw, let me clarify something. Divine Sacrifice works as a damage transfer aura, which means the paladin gets the buff and everyone else the effect. Noone can dispel the sacrifice on other targets because it's the buff on the paladin that causes this constantly, so only dispelling the paladin will get rid of the aura on the other players.

The fact that you are telling me "why noone dispels warrior" shows me you have no understanding on how this spell works.
