### ISSUE TITLE
[Arms] Bladestorm, Death Grip [DK] Interaction.

### ISSUE THREAD

**Issue by Juiceyyhi** [SunwellTracker/issues#928]
Decription: 
If you are bladestorming, a death knight can grip you inside of it, which is a bug.
You're supposed to be immune to any slow / disorient movement abilities such as knockback on Ele shamans.

How it works: 
You get gripped away from your target while being affected by the Bladestorm buff, which is a bug.

How it should work: 
You're supposed to be immune to the death grip, I used to bladestorm death grips all the time, now i'm forced to spell reflect it and then bladestorm, which makes ur sync with rotation horrible for many reasons.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I'm not pvp player but literally 5 sec long google search and i found this:
http://www.arenajunkies.com/topic/96335-blade-storm-death-grip/
https://us.battle.net/forums/en/wow/topic/19891439655
So that's probably how it works on official servers asweel. There's long debate where DG is CC or just forced movement. 

So unless you provide an evidence that you should be immune to DG during bladestorm - looks to work as intended to me.
