### ISSUE TITLE
Writhing choker doesn't allow me to start quest

### ISSUE THREAD

**Issue by Krrl** [SunwellTracker/issues#939]
Decription: Writhing choker doesn't allow me to start quest

How it works: item drops, doesnt start quest. do not meet requirements

How it should work: item drops, i should be able to accept quest

looked @ #337. Seems to be different, as the item drops but i cannot take quest.

**Comment by Dootz** [comment]
Hi!
Only requirements for quest http://www.wowhead.com/quest=12633/darkness-calling ( are min. level of 74 and completed quest http://www.wowhead.com/quest=12238/cleansing-draktharon . Do you meet these conditions?

**Comment by Krrl** [comment]
Not this:  http://www.wowhead.com/quest=12238/cleansing-draktharon

I didn't do that quest on my last character and I was able to start the chain

**Comment by Dootz** [comment]
Is there any chance you started this chain on other character from http://www.wowhead.com/item=38660/unliving-choker instead of http://www.wowhead.com/item=38673/writhing-choker ? Because i'm sure that it's intended that you need to complete http://www.wowhead.com/quest=12238/cleansing-draktharon before taking quest from http://www.wowhead.com/item=38673/writhing-choker, and you don't need to complete it when you start from http://www.wowhead.com/item=38660/unliving-choker

**Comment by Krrl** [comment]
possible. I suppose this is working as intended then.

**Comment by heracro** [comment]
Cleansing Drak'Tharon quest (part 8) can't be active. It doesn't need to be completed, if you can't progress with choker, just cancel cleansing or complete it first. Later on you can pick cleansing again.
