### ISSUE TITLE
Quest-Sorlofs Booty

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#96]
Decription: Cannot dmg Sorlof  to make the booty drop

How it works: 
1. Sorlof comes to shore, 
2. we attack with cannon and he clips on terrain
3. probably evades while doing so wich cause him to reset stay full hp
4. booty doesnt drop because sorlof resets and eventually despawn without dying wich makes the booty impossible to be dropped

How it should work: Mob should not clip during its pathing, it looks like its trying to interact with the player who is attacking him on the boat

Source (you should point out proofs of your report, please give us some source): Dredd witnessed the event.

**Comment by Kokaina** [comment]
+
https://www.youtube.com/watch?v=_zoAEAdsoRY

**Comment by Zarant** [comment]
This quest also have an issue with draw distance, for the most part you can't see Sorlof, although the cannon does hit him even if you can't see him in your screen. I completed it by accident by right clicking the cannon because I was bored. From what I recall, some specific mobs don't follow the same standard draw distance rules, and should be seen from very far away, Sorlof being one of them.

**Comment by artemmavrich** [comment]
Guys, if you can’t make this quest blizzlike, so just increase cannon damage that it will be equal to Sorlof HP, so you shoot him once and kill without spamming on cannon as it was at official server

**Comment by Dootz** [comment]
We're in process of rewriting some core systems. Until they are ready we'll implement temporary fix. Sorlof will roam along the coast, and it'll take two hits to kill from cannon to kill him.

**Comment by Dootz** [comment]
Temporary fix will be applied with next server update.
