### ISSUE TITLE
Spirit of redemption Fall to the abyss issue  

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#983]
Decription: Hi
When you fall down in EOE or ICC lich king fight you can't revive since Spirit of redemption bugs it out for you
How it works: if you fall down in EOE or ICC lich king you can't revive yourself you stay at 2hp down there

How it should work: you should be able to release 

Source (you should point out proofs of your report, please give us some source):

**Comment by xys007** [comment]
I confirm this bug still exist.
When a player falls out of the map he hit some invisible plane and he should instantly die. Nothing should prevent player from dieing. Even paladin's Divine Shield cannot prevent him from dieing instantly. But when a priest with Spirit of Redemption talent hit this plane, he does not instantly die. Spirit of redemption triggers turning priest into a Spirit of Redemption. It does not cause problem yet, but after Spirit of Redemption fades or is manually removed, priest is turned into ghost form with 2 hp, but he is not moved to nearest graveyard. He is stuck on this plane, can move, can logout because game says can logout while falling. The only solution is ALT+F4 but it also removes player from battleground or raid.
Proper behavior is that Spirit of Redemption should not be triggered when falling out of map. (Why should it anyway). Easiest way to reproduce this bug is to dismount from flying mount somewhere outside the edges of Outland. But it happens anywhere where player falls out of map. For example in The Oculus instance which is specifically designed in this way to kill falling players. Also happened to me when i was feared into textures in Warsong Gulch battleground.
