### ISSUE TITLE
[Hunter] Freezing Trap [PVP][PVE]

### ISSUE THREAD

**Issue by Maadguy** [SunwellTracker/issues#993]
Decription: 
Hunter Freezing Trap is not working as intended at all.

How it works: 
Right now, it can activate on targets that are beyond the normal radius and picks a target randomly selected between all possible targets within that radius.
How it should work: 
It should have a smaller range (a bit bigger then the size of the trap gameobject), and target the player thats nearest to it.

This is really gamebreaking in PVP.

Source (you should point out proofs of your report, please give us some source): 
Any hunter wotlk PVP hunter video.

**Comment by dathremar** [comment]
Range is fine (on Warmane trap range is about 3x smaller than it should be and i guess ppl just got used to their scripting hence the report ;s )
proof:
http://www.warcraftmovies.com/movieview.php?id=145315  -  2:05, the hunter is a retard who cant aim, yet he gets many traps because the range was huge.

Random target selection is an issue with scatter shot and movement system - when hunter scatters someone the server treats him as if he was standing still in place, so visually the scattered person may seem to be the one further away from the trap, when actually hes standing directly on the trap and intervening warrior etc. cant eat it.

**Comment by Maadguy** [comment]
Nope, random target selection happens without scatters as well

**Comment by helofriend** [comment]
bump, random targetting still happening in PvP.

**Comment by Hulsuk** [comment]
Ok happen to be unlucky when someone cover a trap, it's a 50% chance.
But you just can't say random targetting it's ok when you watch his clip (https://clips.twitch.tv/FriendlyFantasticNuggetsYee), it's competely random.

On all server you can do some tricks with the frost trap, like use the snake trap for secure when 2 enemys are close, you just put the trap closer to the desired target. But with this script, that will be always random :/

I have not found any evidence that this is a bug, but when you read the spell description 
"It causes the first enemy to approach the trap to be frozen"
It seems to mean the closest

**Comment by Hulsuk** [comment]
I tested by myself
https://youtu.be/VC6qA6bEAc0
100% luck / random mechanic
The lucky guys will appreciate

**Comment by Maadguy** [comment]
Bump, this is still a pretty big thing

**Comment by Zarant** [comment]
Contributing to this report with some proof:
https://www.youtube.com/watch?v=cZBemXyvHys

At the 3 minute mark you can have an idea of how big the trap trigger radius is, basically the freezing arrow ice blast animation is a pretty good visual indication.

At 9:19 you can see both the paladin and the dk within the trap trigger radius, the paladin get trapped there because he is the closest one to the trap when the 1 second arming time finishes.

**Comment by Azathothh** [comment]
Fixed, will be updated soon.

**Comment by blazetrooper** [comment]
Reducing activation range is not a fix. Now every single trap ahve super low activation range, even aoe traps. https://youtu.be/RtkraBQbpgI?t=153 look at range of freezing trap and look at range on angrathar https://streamable.com/s2mbj. Same with frost trap and frost arrow, activation radius is too small.

**Comment by Azathothh** [comment]
Trap activation range wasn't touched at all - this fix had nothing to do with that. Also it's report about Freezing Trap - you're posting videos with Frost Trap.
If there's bug with activation range of traps please create new report about it.

**Comment by Chryslol** [comment]
Duplicate of #
